### ISSUE TITLE
ComfyUI will relaunch after shutdown but StabilityMatrix won't recognize that it has restart, acts like it's still open causing problems.

### ISSUE THREAD

**Issue by GeminiSquishGames** [LykosAI/StabilityMatrix#1004]
### What happened?

If I update with CUI Manager and it asks for a relaunch, if I do it from the interface it will shut the server down and relaunch it however in the Stability Matrix server console, it doesn't seem to quite get the memo and half acts like it isn't launched, keeping the green launch button there and not notifying the Inference UI that Comfy is open. This can cause other problems like it trying to open another server on 8189, but usually Inference just times out when I try to use it to load Comfy.

The ComfyUI interface in the browser seems to work after this. But in order to keep working normally, especially if Inference is needed for a quick change, I have to restart StabilityMatrix

### Steps to reproduce

Start a ComfyUI package

Restart it from the ComfyUI... UI. 

Note that the Launch button doesn't turn to red for shut down but comfy still will be reporting to the console. 

Note that Infernce doesn't think comfy is open.

Note that if you do try to Launch ComfyUI it will now act like the other package isn't open. You can sometimes bug this and have it open on port 8189 but the usual error is below in the relevant logs box. It loses the connection to the one ComfyUI opens itself. (?)

### Relevant logs

```shell
Traceback (most recent call last):
  File "D:\Graphics\stability matrix\Data\Packages\ComfyUI\main.py", line 262, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\Graphics\stability matrix\Data\Packages\ComfyUI\main.py", line 167, in run
    await asyncio.gather(server.start_multi_address(addresses, call_on_start), server.publish_loop())
  File "D:\Graphics\stability matrix\Data\Packages\ComfyUI\server.py", line 840, in start_multi_address
    await site.start()
  File "D:\Graphics\stability matrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "asyncio\base_events.py", line 1519, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted
```

### Version

2.12.3

### What Operating System are you using?

Windows

**Comment by miurgh** [comment]
same.
I have to exit Stability Matrix every time.
