### ISSUE TITLE
Could not install ComfyUI

### ISSUE THREAD

**Issue by dxkyy** [LykosAI/StabilityMatrix#1018]
### What happened?

When trying to install ComfyUI, I get this Error:
```
Could not install ComfyUI (StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1
   at StabilityMatrix.Core.Python.PyVenvRunner.Setup(Boolean existsOk, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.SetupVenvPure(String installedPackagePath, String venvName, Boolean forceRecreate, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.InstallPackage(String installLocation, InstalledPackage installedPackage, InstallPackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps))
```

### Steps to reproduce

1. Try to install ComfyUI in the packages tab

### Relevant logs

```shell
Unpacking resources
Unpacking resources
Download Complete
Could not install ComfyUI (StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1
   at StabilityMatrix.Core.Python.PyVenvRunner.Setup(Boolean existsOk, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.SetupVenvPure(String installedPackagePath, String venvName, Boolean forceRecreate, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.InstallPackage(String installLocation, InstalledPackage installedPackage, InstallPackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps))
```

### Version

v2.12.3

### What Operating System are you using?

Windows

**Comment by AtomProgramm** [comment]
Same

```
(StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1
   at StabilityMatrix.Core.Python.PyVenvRunner.Setup(Boolean existsOk, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.SetupVenvPure(String installedPackagePath, String venvName, Boolean forceRecreate, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.StableDiffusionDirectMl.InstallPackage(String installLocation, InstalledPackage installedPackage, InstallPackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps))
```
