### ISSUE TITLE
ComfyUI crashed - Unobserved Task Exception ConfigParserException:  Multi-line values are explicitly disallowed by parser settings. Please consider changing them.. On the line no. #2.

### ISSUE THREAD

**Issue by andrej-ka** [LykosAI/StabilityMatrix#1019]
### Package

 ComfyUI

### When did the issue occur?

Running the Package

### What GPU / hardware type are you using?

i9-13900K, 64 GB memory, NVIDIA GeForce RTX 4070 Ti SUPER 16.0 GB

### What happened?

Hello, I’m experiencing an issue with StabilityMatrix + ComfyUI.

After installing a couple of new nodes, when I restarted ComfyUI within StabilityMatrix, my computer crashed with a blue screen.

After rebooting the computer, ComfyUI stopped launching within StabilityMatrix, and I now see the following error message:

Unobserved Task Exception ConfigParserException:
Multi-line values are explicitly disallowed by parser settings. Please consider changing them.. On the line no. #2.

I would greatly appreciate any ideas on how to restore ComfyUI.

Thank you! 

### Console output

2024-11-28 23:15:57.4873|ERROR|StabilityMatrix.Avalonia.Program|Unobserved Task Exception|Salaros.Configuration.ConfigParserException: Multi-line values are explicitly disallowed by parser settings. Please consider changing them.. On the line no. #2.
   at Salaros.Configuration.ConfigParser.AppendValueToKey(ConfigSection& currentSection, ConfigLine& currentLine, String lineRaw, Int32 lineNumber)
   at Salaros.Configuration.ConfigParser.Read(String configContent)
   at Salaros.Configuration.ConfigParser..ctor(String configFile, ConfigParserSettings settings)
   at StabilityMatrix.Core.Python.PyVenvRunner.SetPyvenvCfg(String pythonDirectory, Boolean force)
   at StabilityMatrix.Core.Python.PyVenvRunner.RunDetached(ProcessArgs args, Action`1 outputDataReceived, Action`1 onExit, Boolean unbuffered)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.RunPackage(String installLocation, InstalledPackage installedPackage, RunPackageOptions options, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Avalonia.Services.RunningPackageService.StartPackage(InstalledPackage installedPackage, String command, CancellationToken cancellationToken)

### Version

v2.12.3

### What Operating System are you using?

Windows

**Comment by se7enth** [comment]
I meet it ,the pyvenv.cfg was wrong in venv, just copy it from  another package

**Comment by Jbarriga93v** [comment]
> I meet it ,the pyvenv.cfg was wrong in venv, just copy it from another package

Worked for me, thank you
