### ISSUE TITLE
Installation failed: package modification failed

### ISSUE THREAD

**Issue by acgc99** [LykosAI/StabilityMatrix#1020]
### What happened?

Tried to install Stability Matrix in portable mode with ComfyUI.

### Exception Details

![image](https://github.com/user-attachments/assets/58792528-12c3-4f6a-b013-3c5498b9ae84)

```
mingw64\share\git\git-wrapper.exe
usr\bin\msys-edit-0.dll
usr\bin\msys-tasn1-6.dll
usr\lib\perl5\core_perl\auto\Devel\Peek\Peek.dll
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'C:\Users\acgc99\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 3175 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageOptions options, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps)
```

### Version

2.12.3

### What Operating System are you using?

Windows

**Comment by LadyFlames** [comment]
this same error happens when either reinstalling Forge or ReForge or on a Fresh First time install of Forge or ReForge its not limited just to ComfyUI

**Comment by acgc99** [comment]
It seemed to be a connection issue, later that day, I moved to a room with better wifi quality, and the issue disappeared.

**Comment by Veia7e** [comment]
I had the same problem, it was solved after I turned off the proxy
