### ISSUE TITLE
SeargeSDXL Custom Nodes Supported?

### ISSUE THREAD

**Issue by PresTrembleyIIIEsq** [LykosAI/StabilityMatrix#104]
This might be a longshot, but I just updated both Stability Matrix and my SeargeSDXL custom nodes folder located in /ComfyUI/custom_nodes/SeargeSDXL.

However, now when I launch ComfyUI from within Stability Matrix, I get the following errors. I'm still able to launch the GUI, but the custom nodes aren't working, and I wanted to check here and see if there's anything I can do on the Stability Matrix side to avoid these errors (I'm also checking Searge's page for help, but I'm not sure which side the problem is on).

--
```
[...]
Adding extra search path diffusers /home/[myuser]/.config/StabilityMatrix/Models/Diffusers
Adding extra search path gligen /home/[myuser]/.config/StabilityMatrix/Models/GLIGEN
Adding extra search path vae_approx /home/[myuser]/.config/StabilityMatrix/Models/ApproxVAE
Traceback (most recent call last):
  File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/nodes.py", line 1596, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/__init__.py", line 33, in <module>
    from .modules._legacy import LEGACY_CLASS_MAPPINGS, LEGACY_DISPLAY_NAME_MAPPINGS
  File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/__init__.py", line 29, in <module>
    from .ui import Defs
  File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/ui.py", line 37, in <module>
    from .custom_sdxl_ksampler import CfgMethods
  File "/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL/modules/custom_sdxl_ksampler.py", line 38, in <module>
    from comfy.model_management import get_torch_device, batch_area_memory, load_models_gpu
ImportError: cannot import name 'batch_area_memory' from 'comfy.model_management' (/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/comfy/model_management.py)

Cannot import /home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL module for custom nodes: cannot import name 'batch_area_memory' from 'comfy.model_management' (/home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/comfy/model_management.py)

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /home/[myuser]/.config/StabilityMatrix/Packages/ComfyUI/custom_nodes/SeargeSDXL

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by PresTrembleyIIIEsq** [comment]
If anyone else runs into this, I ended up just uninstalling and reinstalling the whole ComfyUI package, and that fixed whatever the issue was.
