### ISSUE TITLE
Can`t use any interface when data folder isnt on system drive (linux)

### ISSUE THREAD

**Issue by VoidDave** [LykosAI/StabilityMatrix#1044]
### What happened?

As title say. After creating data folder on non system drive (yes it is mounted) I cant install or update any interface (I cant remember right now if its even starts if data folder is copied with successful installation but probably not). So its pretty much impossible to use it on non system drive. 
OS: Arch Linux
disc partition type (main and secondary one): ext4
secondary disc is sata one
yes I have permitions for that folder/ drive / tried on root 

### Steps to reproduce

1. Install / open installed Stability Matrix
2. Choose any location that isn't one system drive
3. start installing any interface
4. get error during installation (causing install to fail)

### Relevant logs

```shell
Unpacking resources
Unpacking resources
Download complete!
Error: System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/run/media/voiddave/Linux_games/Insanity/Assets/7zzs' with working directory '/home/voiddave'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at StabilityMatrix.Core.Processes.ProcessRunner.StartTrackedProcess(Process process)
   at StabilityMatrix.Core.Processes.ProcessRunner.GetProcessResultAsync(String fileName, ProcessArgs arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables)
   at StabilityMatrix.Core.Processes.ProcessResultTaskExtensions.EnsureSuccessExitCode(Task`1 task)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7Z(String archivePath, String extractDirectory)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7ZTar(String archivePath, String extractDirectory)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7ZAuto(String archivePath, String extractDirectory)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPythonIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPackageRequirements(List`1 prerequisites, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps)
```

### Version

2.12.4

### What Operating System are you using?

Linux

**Comment by Alastor-Ripley** [comment]
i'm getting the same error, but its whenever i try to update to the preview version, using the version from the aur but i've also had issues trying to update the appimage version as well.

**Comment by Alastor-Ripley** [comment]
I'm still having this same issue and haven't found a workaround

**Comment by VladKolerts** [comment]
up
