### ISSUE TITLE
AMD install does not detect mROC and just errors out asking for CUDA

### ISSUE THREAD

**Issue by BrechtCorbeel** [LykosAI/StabilityMatrix#1058]
### What happened?

I switched my 4090 to my Linux server and added my 7900XTX to my main machine as the 4090 just works and runs better, even with the AMD install for Comfy it did not run on Linux cannot get it to run on Windows either, I just get stuck being asked for CUDA:

Traceback (most recent call last):
  File "W:\smatrix\Data\Packages\ComfyUIAMD\main.py", line 132, in <module>
    import execution
  File "W:\smatrix\Data\Packages\ComfyUIAMD\execution.py", line 13, in <module>
    import nodes
  File "W:\smatrix\Data\Packages\ComfyUIAMD\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "W:\smatrix\Data\Packages\ComfyUIAMD\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "W:\smatrix\Data\Packages\ComfyUIAMD\comfy\sd.py", line 6, in <module>
    from comfy import model_management
  File "W:\smatrix\Data\Packages\ComfyUIAMD\comfy\model_management.py", line 145, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "W:\smatrix\Data\Packages\ComfyUIAMD\comfy\model_management.py", line 114, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "W:\smatrix\Data\Packages\ComfyUIAMD\venv\lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()
  File "W:\smatrix\Data\Packages\ComfyUIAMD\venv\lib\site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

### Version

v 2.14.4

### What Operating System are you using?

Windows

**Comment by brknsoul** [comment]
ROCm (AMD's version of CUDA) is not available for Windows.

**Comment by dlm21** [comment]
Several of us Linux users are getting this as of 1/29 , but it seems to not be related to a recent comfyUI update as upon further analysis even using a version of comfyUI that was working last week now is not working.

https://github.com/comfyanonymous/ComfyUI/issues/6649

**Comment by BrechtCorbeel** [comment]
> ROCm (AMD's version of CUDA) is not available for Windows.

Didn't work for me on Linux either, but rocM is installable on Windows.

I got a new pc odered which I will install my AMD card onto and try again.

U had issue with Ubuntu 24 is there a reason or something I should know when picking OS version?

**Comment by Sersys** [comment]
I'm having the same issue on my RX 7900 XT on linux. I couldn't get Comfy_ui working on previous PyTorch version because of the "Attempting to use hipBLASLt on a unsupported architecture!" bug. I was suggested to update PyTorch and now it's looking for Nvidia drivers. Ironically the only solution I've found so far is to downgrade PyTorch in which case I'm facing the hipBLASLt issue again.

**Comment by brknsoul** [comment]
There's a ZLUDA fork of ComfyUI here; https://github.com/patientx/ComfyUI-Zluda

I've written a [guide](https://github.com/brknsoul/ROCmLibs/wiki/Installing-ComfyUI%E2%80%90Zluda) to install it; it's not installable via SM.
Don't forget to install all dependencies first!

**Comment by mohnjiles** [comment]
> There's a ZLUDA fork of ComfyUI here; https://github.com/patientx/ComfyUI-Zluda
> 
> I've written a [guide](https://github.com/brknsoul/ROCmLibs/wiki/Installing-ComfyUI%E2%80%90Zluda) to install it; it's not installable via SM.

This has been available in SM since v2.13.0. If you aren't seeing it, try enabling the Show All Packages option or make sure you're on the latest version.
