### ISSUE TITLE
Models in Subfolders Cause Errors in SwarmUI on mac

### ISSUE THREAD

**Issue by AnbaiMei** [LykosAI/StabilityMatrix#1073]
### Package

SwarmUI

### When did the issue occur?

Other

### What GPU / hardware type are you using?

Apple M1 Max

### What happened?

In SwarmUI, I cannot load models that are not in the Root directory when loading checkpoints or Lora. 

For example, checkpoints like "Pony/test.safetensors" in the Pony folder cause an error. 
If I place "test.safetensors" in the Root without using folders, it works. 
However, this makes it impossible to organize the models. 

This issue does not occur in SwarmUI installed without StabilityMatrix, so it seems there is a problem on the StabilityMatrix side. 
Looking at the logs, it appears that there is a mix of / and \ suggesting that the path is not formatted for macOS.

### Console output

2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT] Traceback (most recent call last):
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]   File "/Users/anbaimei/Library/Application Support/StabilityMatrix/Packages/ComfyUI/execution.py", line 328, in execute
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]   File "/Users/anbaimei/Library/Application Support/StabilityMatrix/Packages/ComfyUI/execution.py", line 203, in get_output_data
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]   File "/Users/anbaimei/Library/Application Support/StabilityMatrix/Packages/ComfyUI/execution.py", line 174, in _map_node_over_list
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]     process_inputs(input_dict, i)
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]   File "/Users/anbaimei/Library/Application Support/StabilityMatrix/Packages/ComfyUI/execution.py", line 163, in process_inputs
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]     results.append(getattr(obj, func)(**inputs))
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]   File "/Users/anbaimei/Library/Application Support/StabilityMatrix/Packages/ComfyUI/nodes.py", line 567, in load_checkpoint
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]     ckpt_path = folder_paths.get_full_path_or_raise("checkpoints", ckpt_name)
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]   File "/Users/anbaimei/Library/Application Support/StabilityMatrix/Packages/ComfyUI/folder_paths.py", line 287, in get_full_path_or_raise
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT]     raise FileNotFoundError(f"Model in folder '{folder_name}' with filename '{filename}' not found.")
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT] FileNotFoundError: Model in folder 'checkpoints' with filename 'Pony\test.safetensors' not found.
2024-12-29 16:57:14.960 [Warning] [ComfyUI-0/STDOUT] 
2024-12-29 16:57:15.033 [Error] Error loading model '/Users/anbaimei/Library/Application Support/StabilityMatrix/Packages/SwarmUI/Models/Stable-Diffusion/Pony/test.safetensors' (arch=stable-diffusion-xl-v0_9-base) on backend 0 (ComfyUI Self-Starting): ComfyUI execution error: Model in folder 'checkpoints' with filename 'Pony\test.safetensors' not found.
2024-12-29 16:57:15.033 [Warning] Tried 1 backends but none were able to load model 'Pony/test.safetensors'

### Version

v2.13.0

### What Operating System are you using?

macOS

**Comment by AnbaiMei** [comment]
Upon re-examination, I have confirmed that this is an issue on the SwarmUI side. 
Therefore, I will close it.
