### ISSUE TITLE
Stability Matrix Model Browser crashes under Arch Linux

### ISSUE THREAD

**Issue by Davitox87** [LykosAI/StabilityMatrix#1075]
### What happened?

1. Open Stability Matrix
2. Open Model Browser
3. Crash

## Exception
```LiteAsyncException: LiteDB encounter an error. Details in the inner exception.```
```LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"sams/sam_vit_b_01ec64.pth"'.```
### Sentry ID
[`753323e3`](https://stability-matrix.sentry.io/issues/?query=id%3A753323e357454e54be5ea7f939b5096f&referrer=sm-app-ex&statsPeriod=90d)
### Stack Trace
```   at StabilityMatrix.Core.Services.ModelIndexService.RefreshIndexParallelCore()
   at StabilityMatrix.Avalonia.ViewModels.CheckpointsPageViewModel.Refresh()
   at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException](Task task, Boolean continueOnCapturedContext, Action`1 onException)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)```
```   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte insertLevels, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.SharedEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.Async.LiteDatabaseAsync.<>c__DisplayClass37_0`1.<EnqueueAsync>g__Function|0()```


### Version

v2.13.0

### What Operating System are you using?

Linux

**Comment by postcanonical** [comment]
Found this bug when reinstalling SM. 
## Workaround:

> '"sams/sam_vit_b_01ec64.pth"'.

remove this from `xxx/Data/Models/` . for AUR package path should be `/opt/stabilitymatrix/Data/Models/`
also remove `/opt/stabilitymatrix/Data/StabilityMatrix.db` before starting the app.
If other files gives this issue just remove them as well.
