### ISSUE TITLE
Stable Diffusion EasyNegative.safetensors installed but not visible?

### ISSUE THREAD

**Issue by miracle777** [LykosAI/StabilityMatrix#119]
When I installed Stable Diffusion WEB UI, I was able to generate images. However, after installing Fooocus, I get an error and can no longer generate images.

I am using a Windows 11 laptop. The VRAM is 6GB, and the graphics card is RTX3060. The VRAM setting is checked as "medvram". I was concerned that the VAE was not displayed from the beginning. However, I was able to generate an image once at the beginning. I would like to inform you about the VAE not being displayed and the error that occurred during image generation. I learned about the latest version 2.4 and updated it, but the issue was not resolved.

![スクリーンショット 2023-09-12 092830](https://github.com/LykosAI/StabilityMatrix/assets/13194391/133a1082-7437-4daf-9e67-770b485d2e71)

![スクリーンショット 2023-09-12 093009](https://github.com/LykosAI/StabilityMatrix/assets/13194391/028c7b66-52ec-4f5f-9c2c-88e8183a9cd7)

![スクリーンショット 2023-09-12 092906](https://github.com/LykosAI/StabilityMatrix/assets/13194391/71a98d80-08e5-441d-a219-b10f6d3552ce)

![スクリーンショット 2023-09-12 095714](https://github.com/LykosAI/StabilityMatrix/assets/13194391/c47af15c-b182-46ee-89f5-541d929fa48d)

`
*** Error completing request
*** Arguments: ('task(u18kudxmusn0p2c)', 'beautiful,girl', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x0000022F84C26B30>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 960, 64, True, True, True, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\processing.py", line 914, in process_images_inner
        x_sample = modules.face_restoration.restore_faces(x_sample)
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\face_restoration.py", line 19, in restore_faces
        return face_restorer.restore(np_image)
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\codeformer_model.py", line 81, in restore
        self.create_models()
      File "E:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\codeformer_model.py", line 58, in create_models
        checkpoint = torch.load(ckpt_path)['params_ema']
    TypeError: 'NoneType' object is not subscriptable
`

**Comment by miracle777** [comment]
Sorry.
The problem with Stable Diffusion not generating images has been fixed.
The cause was that in the settings screen of Stable Diffusion web UI (AUTOMATIC1111 version), the check box for face modification was checked.
After unchecking the check box, as shown in the image, I was able to generate the image.

But the VAE still does not show up in the Stable Diffusion UI.
![スクリーンショット 2023-09-12 113944](https://github.com/LykosAI/StabilityMatrix/assets/13194391/8a6d1640-1979-447a-b570-7097f37bf3ff)
