### ISSUE TITLE
who know how fix this issue  Process finished with exit code 1

### ISSUE THREAD

**Issue by YesserFA** [LykosAI/StabilityMatrix#138]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Couldn't determine Stable Diffusion's hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf, attempting autofix...
Fetching all contents for Stable Diffusion
Pruning Stable Diffusion
Traceback (most recent call last):
  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\modules\launch_utils.py", line 380, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\modules\launch_utils.py", line 172, in git_clone
    current_hash = run_git(dir, name, 'rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}", live=False).strip()
  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\modules\launch_utils.py", line 162, in run_git
    return run(f'"{git}" -C "{dir}" {command}', desc=desc, errdesc=errdesc, custom_env=custom_env, live=live)
  File "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't determine Stable Diffusion's hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf.
Command: "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\PortableGit\bin\git.exe" -C "C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\repositories\stable-diffusion-stability-ai" rev-parse HEAD
Error code: 128
stdout: HEAD

stderr: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Process finished with exit code 1

**Comment by mohnjiles** [comment]
Hi, could you try deleting the `repositories` folder located at `C:\Users\YFA_MFA\AppData\Roaming\StabilityMatrix\Packages\Packages\stable-diffusion-webui\repositories` and then re-try? It should re-download those folders the next time you launch.
