### ISSUE TITLE
pip install failed with code 2

### ISSUE THREAD

**Issue by illuculent** [LykosAI/StabilityMatrix#142]
pip install failed with code 2: 'Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118\r\nCollecting 

   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(String args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.BasePackage.InstallCudaTorch(PyVenvRunner venvRunner, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.InstallPackage(String installLocation, TorchVersion torchVersion)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.DoInstall()
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.Install()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)

**Comment by ionite34** [comment]
Can you try with the latest version v2.4.5? The console should stay open in event of any install errors and you should have the full output.
