### ISSUE TITLE
Invoke fails to import already downloaded ControlNET safepoint

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#196]
I don't know if this issue is related to #183 or not.

When I look at Checkpoints the only one that shows up under Invoke is control_v1p_sd15_brightness.saftensors, all others, which are in fact, are already downloaded and present under

D:\STABLEDIFF\Data\Models\ControlNet

_are available_ in all of the other installed packages (A1111, Fooocus-MRE, Inference-ComfyUI)

The import as Connected button is enabled.

On my 2nd computer, it took 4-5 series of updates over a 7-10 days before Invoke was able to launch successfully without writing 3 pages of complaints. On the current computer is appears to be in an earlier phase of getting things to work.

**Comment by drdancm** [comment]
[2023-10-09 16:23:03,866]::[InvokeAI]::INFO --> Patchmatch initialized
D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[2023-10-09 16:23:08,495]::[uvicorn.error]::INFO --> Started server process [9336]
[2023-10-09 16:23:08,496]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-10-09 16:23:08,496]::[InvokeAI]::INFO --> InvokeAI version 3.2.0
[2023-10-09 16:23:08,496]::[InvokeAI]::INFO --> Root directory = D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root
[2023-10-09 16:23:08,498]::[InvokeAI]::INFO --> Using database at D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root\databases\invokeai.db
[2023-10-09 16:23:08,506]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 3090
[2023-10-09 16:23:09,007]::[InvokeAI]::INFO --> Scanning D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root\models for new models
[2023-10-09 16:23:11,185]::[InvokeAI]::WARNING --> Failed to process 'D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control-lora-canny-rank128.safetensors': Unable to determine base type for {self.checkpoint_path}
[2023-10-09 16:23:11,840]::[InvokeAI]::WARNING --> Failed to process 'D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control-lora-canny-rank256.safetensors': Unable to determine base type for {self.checkpoint_path}
[2023-10-09 16:23:12,323]::[InvokeAI]::WARNING --> Failed to process 'D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control-lora-depth-rank128.safetensors': Unable to determine base type for {self.checkpoint_path}
[2023-10-09 16:23:12,801]::[InvokeAI]::WARNING --> Failed to process 'D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control-lora-depth-rank256.safetensors': Unable to determine base type for {self.checkpoint_path}
[2023-10-09 16:23:12,882]::[InvokeAI]::WARNING --> Failed to process 'D:\STABLEDIFF\Data\Packages\InvokeAI\invokeai-root\autoimport\controlnet\controlV1pSd15_v10.safetensors': 1 validation error for CheckpointConfig
config
  field required (type=value_error.missing)

There's a lot more

**Comment by LadyFlames** [comment]
[2023-10-17 08:15:51,711]::[InvokeAI]::INFO --> Patchmatch initialized
D:\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[2023-10-17 08:15:56,955]::[uvicorn.error]::INFO --> Started server process [2668]
[2023-10-17 08:15:56,956]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-10-17 08:15:56,971]::[InvokeAI]::INFO --> InvokeAI version 3.3.0post3
[2023-10-17 08:15:56,971]::[InvokeAI]::INFO --> Root directory = D:\StabilityMatrix\Packages\InvokeAI\invokeai-root
[2023-10-17 08:15:56,972]::[InvokeAI]::INFO --> Using database at D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\databases\invokeai.db
[2023-10-17 08:15:58,910]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 2060
[2023-10-17 08:15:58,913]::[InvokeAI]::INFO --> Scanning D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\models for new models
[2023-10-17 08:16:08,767]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11e_sd15_ip2p.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:16:17,441]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11e_sd15_shuffle.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:16:26,106]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11f1e_sd15_tile.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:16:34,879]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11f1p_sd15_depth.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:16:44,923]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15s2_lineart_anime.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:16:55,793]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_canny.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:17:05,658]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_inpaint.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:17:18,289]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_lineart.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:17:28,521]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_mlsd.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:17:36,680]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_normalbae.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:17:47,278]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_openpose.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:17:58,505]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_scribble.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:18:09,256]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_seg.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:18:18,305]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\controlnet\control_v11p_sd15_softedge.pth': Error while deserializing header: HeaderTooLarge
[2023-10-17 08:18:20,926]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\embedding\easynegative.safetensors': A model named "easynegative" is already installed.
[2023-10-17 08:18:21,254]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\embedding\FastNegative.safetensors': None is not a valid BaseModelType
[2023-10-17 08:18:23,076]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\embedding\unaestheticXLv1.safetensors': None is not a valid BaseModelType
[2023-10-17 08:18:23,101]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\embedding\unaestheticXLv13.safetensors': None is not a valid BaseModelType
[2023-10-17 08:18:23,119]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\embedding\unaestheticXLv31.safetensors': None is not a valid BaseModelType
[2023-10-17 08:18:23,136]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\embedding\unaestheticXL_AYv1.safetensors': None is not a valid BaseModelType
[2023-10-17 08:18:23,147]::[InvokeAI]::WARNING --> Failed to process 'D:\StabilityMatrix\Packages\InvokeAI\invokeai-root\autoimport\embedding\unaestheticXL_Sky3.1.safetensors': None is not a valid BaseModelType

Please select the scheduler prediction type of the checkpoint named 3dAnimationDiffusion_v10.safetensors:
[1] "epsilon" - most v1.5 models and v2 models trained on 512 pixel images
[2] "vprediction" - v2 models trained on 768 pixel images and a few v1.5 models
[3] Accept the best guess;  you can fix it in the Web UI later

select [3]> 
same issue cant select anything at all or press any buttons none what so ever but on that note i might have figured it out its because invoke itself doesnt Support Models imported directly From a Different Web UI at least not yet they dont theyr looking into it with the help of the Diffusers Team but it could take a very long time

**Comment by drdancm** [comment]
Invoke still won't load properly, even after several updates from Invoke.
I don't know if this is an issue with StabMatrix or Invoke.

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\api_app.py", line 1, in <module>
    from .services.config import InvokeAIAppConfig
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\services\config\__init__.py", line 5, in <module>
    from .config_base import PagingArgumentParser  # noqa F401
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\services\config\config_base.py", line 21, in <module>
    from pydantic import BaseSettings
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\pydantic\__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\pydantic\_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.4/u/import-error

Process finished with exit code 1

**Comment by LadyFlames** [comment]
thats because your not using the latest invoke version which is 3.4.1 you have to kind of do a tricky install theres a lauch button press the arrow on it and use update invoke then on the other side of it is a send input button just put a number on it and press either enter or send a few times

**Comment by Targren** [comment]
> thats because your not using the latest invoke version which is 3.4.1 you have to kind of do a tricky install theres a launch button press the arrow on it and use update invoke then on the other side of it is a send input button just put a number on it and press either enter or send a few times

Is there another step? I ran the "invokeai-update" to update to 3.4.0rc3 (what it says is the latest official release, which goes along with the github page), everything ran through fine, and repeat attempts tell me that everything is already satisfied, but when I try to launch, it still tells me I'm running 3.3.0post3 and gives me the same issue on all the controlnet models.

**Comment by drdancm** [comment]
I have trouble followingLadyFlames instructions. I finally got a strange update Window with choices 1 2 3 etc. to go to 3.3 or 3.4.xx, but no matter what I click or type I cannot get anything to effect, anything in this Window. 

I think I'll just uninstall and then re-install Invoke. Hopefully that will do the trick.

**Comment by Targren** [comment]
> I have trouble followingLadyFlames instructions. I finally got a strange update Window with choices 1 2 3 etc. to go to 3.3 or 3.4.xx, but no matter what I click or type I cannot get anything to effect, anything in this Window.
> 
> I think I'll just uninstall and then re-install Invoke. Hopefully that will do the trick.

There's a button in the top right of the interphase  you need to use to bring up a  "virtual input" bar, it looks like they keyboard switcher button on an android phone.

Reinstalling didn't work for me (this was a fresh install). Installing the main branch still installs 3.3.0post3, and running the update will upgrade the python packages but not the UI. Not sure if that's Invoke weirdness or StabilityMatrix

**Comment by mohnjiles** [comment]
Hi all, there are some issues we are aware of with the way we currently install InvokeAI. This should get fixed in v2.6, which we plan to release soon. Sorry about that!

**Comment by LadyFlames** [comment]
yea what targen said Reinstall and Fresh install wont work at all in a nutshell basically at the top right theres a button for a Virtual input Bar press that it should open a search bar then you put any of the numbers in it and you press the send button DO NOT PRESS ENTER that wont do anything at all it only works if you press the send button

**Comment by Targren** [comment]
> Hi all, there are some issues we are aware of with the way we currently install InvokeAI. This should get fixed in v2.6, which we plan to release soon. Sorry about that!

Are there any plans for the fix to address the prompt for the "Scheduler prediction" setup prompts, too, by any chance? The installer asks you the same question for every checkpoint you have installed (which is a few dozen in my case), which is kind of a PITA.

**Comment by mohnjiles** [comment]
> Are there any plans for the fix to address the prompt for the "Scheduler prediction" setup prompts, too, by any chance? The installer asks you the same question for every checkpoint you have installed (which is a few dozen in my case), which is kind of a PITA.

This is a quirk with the way InvokeAI's autoimport works, since they do a conversion process to make them work I believe. Though yes, the v2.6 update should address this during installation & updates. It may still happen if you run `invokeai-configure` on your own however.

**Comment by LadyFlames** [comment]
just tested it on stability matrix 2.6 aand the issue with invoke is still there

**Comment by hFULAveTeR** [comment]
InvokeAI uses a diffusion system, so you need to download the corresponding ControlNET version. You probably have the version in Pickle Tensor format installed. To make it work in InvokeAI, go to model manager, import models, and copy the ID of the model you want to install. You can get the models from here [.](https://huggingface.co/lllyasviel) An example ID could be the following: lllyasviel/control_v11p_sd15_openpose
