### ISSUE TITLE
Clean Ubuntu 23.04 install with Stability Matrix fails to run A1111

### ISSUE THREAD

**Issue by vleeuwenmenno** [LykosAI/StabilityMatrix#199]
Reproduce: 

- Installed Ubuntu 23.04
- Downloaded app image from https://github.com/LykosAI/StabilityMatrix/releases
- Opened the appimage and selected portable mode and desired path
- Installed A1111 from the menu
- Launched it and the following output appeared:

```Python 3.10.11 (main, May  7 2023, 19:26:31) [Clang 16.0.3 ]
Version: 1.6.0
Commit hash: <none>
Launching Web UI with arguments: --server-name 0.0.0.0 --port 8888 --xformers --api
Traceback (most recent call last):
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/launch.py", line 48, in <module>
    main()
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/launch.py", line 44, in main
    start()
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/modules/launch_utils.py", line 432, in start
    import webui
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/webui.py", line 13, in <module>
    initialize.imports()
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/modules/initialize.py", line 16, in imports
    import pytorch_lightning  # noqa: F401
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities import rank_zero_warn
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py", line 14, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.metric import Metric
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/metric.py", line 30, in <module>
    from torchmetrics.utilities.data import (
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/data.py", line 22, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchmetrics/utilities/imports.py", line 50, in <module>
    _TORCHAUDIO_GREATER_EQUAL_0_10: Optional[bool] = compare_version("torchaudio", operator.ge, "0.10.0")
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/lightning_utilities/core/imports.py", line 73, in compare_version
    pkg = importlib.import_module(package)
  File "/mnt/10tb/Applications/Data/Assets/Python310/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 49, in <module>
    _check_cuda_version()
  File "/mnt/10tb/Applications/Data/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 192, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 12.1 whereas TorchAudio has CUDA version 11.8. Please install the TorchAudio version that matches your PyTorch version.

Process finished with exit code 1
```

**Comment by vleeuwenmenno** [comment]
After another full reset and the new update this issue seems to have solved itself.
