### ISSUE TITLE
ImportError: Module use of python311.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by rpr13** [LykosAI/StabilityMatrix#231]
Cannot add sd-webui
```
Unpacking resources
Unpacking resources
Download complete!
Download Complete
created virtual environment CPython3.10.11.final.0-64 in 1182ms

  creator CPython3Windows(dest=D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv, clear=False, no_vcs_ignore=False, global=False)

  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\rpr\AppData\Local\pypa\virtualenv)

    added seed packages: pip==23.3.1, setuptools==68.2.2, wheel==0.41.2

  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Traceback (most recent call last):

  File "runpy.py", line 196, in _run_module_as_main

  File "runpy.py", line 86, in _run_code

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\__main__.py", line 22, in <module>

    from pip._internal.cli.main import main as _main

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>

    from pip._internal.cli.autocompletion import autocomplete

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>

    from pip._internal.cli.main_parser import create_main_parser

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>

    from pip._internal.build_env import get_runnable_pip

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\build_env.py", line 15, in <module>

    from pip._vendor.packaging.requirements import Requirement

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 10, in <module>

    from pip._vendor.pyparsing import (  # noqa

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_vendor\pyparsing\__init__.py", line 130, in <module>

    from .exceptions import *

  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_vendor\pyparsing\exceptions.py", line 14, in <module>

    from .unicode import pyparsing_unicode as ppu

ImportError: Module use of python311.dll conflicts with this version of Python.

Error: StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'Traceback (most recent call last):\r\n  File "runpy.py", line 196, in _run_module_as_main\r\n  File "runpy.py", line 86, in _run_code\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\__main__.py", line 22, in <module>\r\n    from pip._internal.cli.main import main as _main\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>\r\n    from pip._internal.cli.autocompletion import autocomplete\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>\r\n    from pip._internal.cli.main_parser import create_main_parser\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>\r\n    from pip._internal.build_env import get_runnable_pip\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_internal\build_env.py", line 15, in <module>\r\n    from pip._vendor.packaging.requirements import Requirement\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_vendor\packaging\requirements.py", line 10, in <module>\r\n    from pip._vendor.pyparsing import (  # noqa\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_vendor\pyparsing\__init__.py", line 130, in <module>\r\n    from .exceptions import *\r\n  File "D:\Applications\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pip\_vendor\pyparsing\exceptions.py", line 14, in <module>\r\n    from .unicode import pyparsing_unicode as ppu\r\nImportError: Module use of python311.dll conflicts with this version of Python.\r\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(String args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.BasePackage.InstallCudaTorch(PyVenvRunner venvRunner, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

**Comment by rpr13** [comment]
It was related to pyenv for windows.
After removing pyenv and it's PATH everything working again.

**Comment by catshitz** [comment]
> It was related to pyenv for windows. After removing pyenv and it's PATH everything working again.

but the vapoursynth for svp4 tensor rife won't work.
