### ISSUE TITLE
Invoke Cannot Run, Invoke Updates fail to fix problem

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#233]
It has been weeks and probaby 6-8 updates from Invoke and it still exits with exit code 1
Invoke support says the problem must be solved at the StabMatrix level:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\api_app.py", line 1, in <module>
    from .services.config import InvokeAIAppConfig
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\services\config\__init__.py", line 5, in <module>
    from .config_base import PagingArgumentParser  # noqa F401
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\services\config\config_base.py", line 21, in <module>
    from pydantic import BaseSettings
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\pydantic\__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\pydantic\_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.4/u/import-error

Process finished with exit code 1

At this point Invoke is unusable.

**Comment by drdancm** [comment]
I gave up on Invoke quite a number of months ago.
