### ISSUE TITLE
Inability to install any package

### ISSUE THREAD

**Issue by TomLucidor** [LykosAI/StabilityMatrix#243]
It seems that after the first install package everything else is locked up assuming installing A1111 as initial loading screen, but similar occurrence happens with ComfyUI as the first install in the initial loading screen

For A1111
```
Done extracting
Tkinter install complete
Error: System.IO.IOException: The response ended prematurely, with at least 34383076 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Services.DownloadService.DownloadToFileAsync(String downloadUrl, String downloadPath, IProgress`1 progress, String httpClientName, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Services.DownloadService.DownloadToFileAsync(String downloadUrl, String downloadPath, IProgress`1 progress, String httpClientName, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Services.DownloadService.DownloadToFileAsync(String downloadUrl, String downloadPath, IProgress`1 progress, String httpClientName, CancellationToken cancellationToken)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallGitIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```
For ComfyUI
```
Unpacking resources
Unpacking resources
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Assets\7za.exe failed with exit-code 2. stdout: '7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28Scanning the drive for archives:  0M Scan C:\Users\t\Downloads\Stabi . 4\StabilityMatrix-win-x64\Data\                                                                          1 file, 21837980 bytes (21 MiB)Extracting archive: C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exe  0%    Can't open as archive: 1Files: 0Size:       0Compressed: 0', stderr: 'ERROR: C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exeC:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exeOpen ERROR: Can not open the file as [7z] archiveERRORS:Unexpected end of archive'
   at StabilityMatrix.Core.Processes.ProcessRunner.ValidateExitConditionAsync(Process process, Int32 expectedExitCode, String stdout, String stderr)
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7Z(String archivePath, String extractDirectory, IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.UnzipGit(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallGitIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```
For Kohya
```
Unpacking resources
Unpacking resources
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Assets\7za.exe failed with exit-code 2. stdout: '7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28Scanning the drive for archives:  0M Scan C:\Users\t\Downloads\Stabi . 4\StabilityMatrix-win-x64\Data\                                                                          1 file, 21837980 bytes (21 MiB)Extracting archive: C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exe  0%    Can't open as archive: 1Files: 0Size:       0Compressed: 0', stderr: 'ERROR: C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exeC:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exeOpen ERROR: Can not open the file as [7z] archiveERRORS:Unexpected end of archive'
   at StabilityMatrix.Core.Processes.ProcessRunner.ValidateExitConditionAsync(Process process, Int32 expectedExitCode, String stdout, String stderr)
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7Z(String archivePath, String extractDirectory, IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.UnzipGit(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallGitIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```
For InvokeAI
```
Unpacking resources
Unpacking resources
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Assets\7za.exe failed with exit-code 2. stdout: '7-Zip (a) 18.01 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28Scanning the drive for archives:  0M Scan C:\Users\t\Downloads\Stabi . 4\StabilityMatrix-win-x64\Data\                                                                          1 file, 21837980 bytes (21 MiB)Extracting archive: C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exe  0%    Can't open as archive: 1Files: 0Size:       0Compressed: 0', stderr: 'ERROR: C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exeC:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit.7z.exeOpen ERROR: Can not open the file as [7z] archiveERRORS:Unexpected end of archive'
   at StabilityMatrix.Core.Processes.ProcessRunner.ValidateExitConditionAsync(Process process, Int32 expectedExitCode, String stdout, String stderr)
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7Z(String archivePath, String extractDirectory, IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.UnzipGit(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallGitIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```
Is the ZIP tool broken or is it the downloader? The folder seems mangled?

**Comment by TomLucidor** [comment]
Deleting the `PortableGit.7z.exe` helps but I hope that this bug would not land on someone else's table

**Comment by TomLucidor** [comment]
Currently this pops up when trying ComfyUI, appears to be a bug for Git?
```
Unpacking resources
Unpacking resources
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process C:\Users\t\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit\bin\git.exe failed with exit-code 128. stdout: '', stderr: ''
   at StabilityMatrix.Core.Processes.ProcessRunner.ValidateExitConditionAsync(Process process, Int32 expectedExitCode, String stdout, String stderr)
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(String workingDirectory, Action`1 onProcessOutput, String[] args)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageVersionOptions versionOptions, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

**Comment by NdlelaYami** [comment]
New to SD. I can't seem to install any packages. I get this error:

Unpacking resources
Unpacking resources
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'C:\Users\thoug\AppData\Roaming\StabilityMatrix\Packages\ComfyUI'...
fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageVersionOptions versionOptions, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

Any suggestions on how to fix?

**Comment by TomLucidor** [comment]
If it is "server was offline" then you will need to retry later, since a lot of these server has spam limits
