### ISSUE TITLE
Kohya's GUI install failed (v.2.6.0)

### ISSUE THREAD

**Issue by kaitas** [LykosAI/StabilityMatrix#246]
Dear
Thhaks for v2.6.0 release. It looks great updates.

I'm trying to install new package Kohya's gui on Windows11, which is already installed with portable mode.
But it failed.

Here is also a new install log (failed). What is the problem? Is this on my own environment?

```
Unpacking resources
Unpacking resources
Download complete!
Python download complete
Download complete!
Tkinter download complete
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Extracting
Done extracting
Tkinter install complete
Download complete!
Git download complete
mingw64\lib\tcl8.6\encoding\macDingbats.enc
mingw64\lib\tcl8.6\tzdata\Africa\Maseru
mingw64\lib\tcl8.6\tzdata\Asia\Macao
mingw64\lib\tcl8.6\tzdata\Etc\GMT-5
mingw64\lib\tcl8.6\tzdata\Europe\Vaduz
mingw64\lib\tcl8.6\tzdata\Pacific\Niue
mingw64\lib\tcl8\8.5\tcltest-2.5.3.tm
mingw64\lib\tk8.6\demos\paned1.tcl
mingw64\lib\tk8.6\msgs\it.msg
mingw64\libexec\git-core\git-sh-setup
mingw64\share\doc\expat\AUTHORS
mingw64\share\doc\git-doc\git-for-each-ref.html
mingw64\share\doc\git-doc\git-lfs-post-merge.html
mingw64\share\doc\git-doc\git-rerere.html
mingw64\share\doc\git-doc\gitweb.html
mingw64\share\doc\xz\THANKS
mingw64\share\doc\xz\faq.txt
mingw64\share\licenses\gcc-libs\README
mingw64\share\perl5\Git\SVN\Editor.pm
usr\bin\zegrep
usr\lib\perl5\vendor_perl\auto . eay\set_server_cert_and_key.al
usr\lib\terminfo\78\xterm-1006
usr\share\awk\getopt.awk
usr\share\gtk-doc\html\p11-kit\p11-kit.html
usr\share\licenses\vim\license.txt
usr\share\misc\magic.mgc
usr\share\nano\lua.nanorc
usr\share\nano\xml.nanorc
usr\share\perl5\core_perl\App\Prove\State\Result.pm
usr\share\perl5\core_perl\Filter\Simple.pm
usr\share\perl5\core_perl\JSON\PP.pm
usr\share\perl5\core_perl\Params\Check.pm
usr\share\perl5\core_perl\Test2\Event\V2.pm
usr\share\perl5\core_perl\bytes.pm
usr\share\perl5\core_perl\unicore\lib\CWCM\Y.pl
usr\share\perl5\core_perl\unicore\lib\In\13_0.pl
usr\share\perl5\core_perl\unicore\lib\InSC\Vowel.pl
usr\share\perl5\core_perl\unicore\lib\NFKDQC\N.pl
usr\share\perl5\core_perl\unicore\lib\Nv\5.pl
usr\share\perl5\core_perl\unicore\lib\SB\FO.pl
usr\share\perl5\core_perl\unicore\lib\Scx\Gran.pl
usr\share\perl5\core_perl\unicore\lib\WB\EX.pl
usr\share\perl5\vendor_perl\Date\Language\Norwegian.pm
usr\share\perl5\vendor_perl\IO\Socket\SSL\Utils.pm
usr\share\perl5\vendor_perl\MIME\Field\ConTraEnc.pm
usr\share\perl5\vendor_perl\URI\file\FAT.pm
usr\share\terminfo\73\screen.linux-m1b
usr\share\terminfo\78\xterm+r6f2
usr\share\vim\vim90\autoload\ccomplete.vim
usr\share\vim\vim90\autoload\typeset.vim
usr\share\vim\vim90\autoload\zip.vim
usr\share\vim\vim90\compiler\gfortran.vim
usr\share\vim\vim90\compiler\rustc.vim
usr\share\vim\vim90\delmenu.vim
usr\share\vim\vim90\doc\builtin.txt
usr\share\vim\vim90\doc\pi_netrw.txt
usr\share\vim\vim90\doc\uganda.txt
usr\share\vim\vim90\doc\usr_toc.txt
usr\share\vim\vim90\ftplugin\config.vim
usr\share\vim\vim90\ftplugin\framescript.vim
usr\share\vim\vim90\ftplugin\help.vim
usr\share\vim\vim90\ftplugin\manconf.vim
usr\share\vim\vim90\ftplugin\poefilter.vim
usr\share\vim\vim90\ftplugin\rmd.vim
usr\share\vim\vim90\ftplugin\ssa.vim
usr\share\vim\vim90\ftplugin\zig.vim
usr\share\vim\vim90\indent\fish.vim
usr\share\vim\vim90\indent\jsp.vim
usr\share\vim\vim90\indent\obse.vim
usr\share\vim\vim90\indent\rst.vim
usr\share\vim\vim90\indent\teraterm.vim
usr\share\vim\vim90\keymap\armenian-eastern_utf-8.vim
usr\share\vim\vim90\keymap\hebrewp_iso-8859-8.vim
usr\share\vim\vim90\keymap\tamil_tscii.vim
usr\share\vim\vim90\lang\ja\LC_MESSAGES\vim.mo
usr\share\vim\vim90\lang\menu_czech_czech_republic.1252.vim
usr\share\vim\vim90\lang\menu_da.latin1.vim
usr\share\vim\vim90\lang\menu_pt_br.utf-8.vim
usr\share\vim\vim90\lang\menu_zh.big5.vim
usr\share\vim\vim90\lang\uk.cp1251\LC_MESSAGES\vim.mo
usr\share\vim\vim90\macros\maze\poster
usr\share\vim\vim90\pack\dist\opt\shellmenu\plugin\shellmenu.vim
usr\share\vim\vim90\plugin\rrhelper.vim
usr\share\vim\vim90\spell\fixdup.vim
usr\share\vim\vim90\syntax\ch.vim
usr\share\vim\vim90\syntax\css.vim
usr\share\vim\vim90\syntax\dnsmasq.vim
usr\share\vim\vim90\syntax\falcon.vim
usr\share\vim\vim90\syntax\gprof.vim
usr\share\vim\vim90\syntax\inform.vim
usr\share\vim\vim90\syntax\kscript.vim
usr\share\vim\vim90\syntax\m4.vim
usr\share\vim\vim90\syntax\msidl.vim
usr\share\vim\vim90\syntax\ora.vim
usr\share\vim\vim90\syntax\po.vim
usr\share\vim\vim90\syntax\r.vim
usr\share\vim\vim90\syntax\sensors.vim
usr\share\vim\vim90\syntax\sqlforms.vim
usr\share\vim\vim90\syntax\treetop.vim
usr\share\vim\vim90\syntax\xquery.vim
usr\share\vim\vim90\tutor\tutor.de
usr\share\vim\vim90\tutor\tutor.pt
mingw64\bin\Avalonia.Controls.dll
mingw64\bin\adig.exe
mingw64\bin\git-lfs.exe
mingw64\bin\libSkiaSharp.dll
mingw64\bin\libwinpthread-1.dll
mingw64\bin\scalar.exe
mingw64\libexec\git-core\SkiaSharp.dll
mingw64\libexec\git-core\libbrotlicommon.dll
mingw64\libexec\git-core\libcurl-openssl-4.dll
mingw64\libexec\git-core\libidn2-0.dll
mingw64\libexec\git-core\msalruntime_x86.dll
mingw64\libexec\git-core\scalar.exe
mingw64\libexec\git-core\scalar.exe
usr\bin\arch.exe
usr\bin\basename.exe
usr\bin\bash.exe
usr\bin\chroot.exe
usr\bin\echo.exe
usr\bin\getconf.exe
usr\bin\msys-aprutil-1-0.dll
usr\bin\msys-psl-5.dll
usr\bin\msys-serf-1-0.dll
usr\bin\nohup.exe
usr\bin\timeout.exe
usr\lib\gawk\fork.dll
usr\lib\perl5\core_perl\auto\Digest\MD5\MD5.dll
usr\lib\perl5\core_perl\auto\Storable\Storable.dll
usr\lib\perl5\vendor_perl\auto\SVN\_Client\_Client.dll
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process C:\Users\(User)\Downloads\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\PortableGit\bin\git.exe failed with exit-code 128. stdout: '', stderr: ''
   at StabilityMatrix.Core.Processes.ProcessRunner.ValidateExitConditionAsync(Process process, Int32 expectedExitCode, String stdout, String stderr)
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(String workingDirectory, Action`1 onProcessOutput, String[] args)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageVersionOptions versionOptions, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

```

**Comment by bigmouth-GD** [comment]
I have the same problem；

the previous version of the update after the fooocus update also appeared this error

**Comment by mohnjiles** [comment]
Hi all, `git.exe failed with exit-code 128` means that the directory already exists and is not empty. Could you please check your `Packages` folder inside your SM install directory and delete the `kohya_ss` folder (or whichever package is failing), then try the install again please.

We will be making improvements to this in the future to help mitigate this issue, sorry about that.
