### ISSUE TITLE
How can i add python path to other hdd loc ?

### ISSUE THREAD

**Issue by merolaika** [LykosAI/StabilityMatrix#299]
Hello there, i get this error. My matrix install Y: driver and my python is C: driver 

`Unpacking resources
Unpacking resources
Download complete!
Python download complete
Error: System.IO.FileNotFoundException: Could not find file 'Y:\Yapay Zeka\StableMatrix\Assets\Python310\python310._pth'.
File name: 'Y:\Yapay Zeka\StableMatrix\Assets\Python310\python310._pth'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.AsyncStreamReader(String path, Encoding encoding)
   at System.IO.File.InternalReadAllTextAsync(String path, Encoding encoding, CancellationToken cancellationToken)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallPythonIfNecessary(IProgress`1 progress)`

**Comment by merolaika** [comment]
Copying the Python files to the asset in the matrix fixed the problem

**Comment by merolaika** [comment]
Copying the Python files to the asset in the matrix fixed the problem
