### ISSUE TITLE
Update to v2.7.0-pre.1 (Error)

### ISSUE THREAD

**Issue by Manniala** [LykosAI/StabilityMatrix#300]
v2.7.0-pre.1

My OS:
![image](https://github.com/LykosAI/StabilityMatrix/assets/32381860/e5a409b2-6284-4fad-a44f-5a30d13a21b2)

![image](https://github.com/LykosAI/StabilityMatrix/assets/32381860/5e731e1c-0bf6-4d82-a9f6-167f8597cab1)

![image](https://github.com/LykosAI/StabilityMatrix/assets/32381860/607f4bb3-fd3c-4377-b665-c41a7eb25b91)

An error occurred trying to start process 'F:\StabilityMatrix.StabilityMatrixUpdate\StabilityMatrix.exe' with working directory 'C:\Windows\system32'. The specified executable is not a valid application for this OS platform.

-------------

   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.UpdateViewModel.InstallUpdate()
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.UpdateViewModel.InstallUpdate()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)

**Comment by ionite34** [comment]
Should be fixed in autoupdater CI
