### ISSUE TITLE
ComfyUI updates fail silently because of a PortableGit error

### ISSUE THREAD

**Issue by jennygreene88** [LykosAI/StabilityMatrix#301]
I'm on the Windows build of 2.6.6.

When I click to update ComfyUI, it instantly reports success (without actually checking for updates), and this error is logged:

```
Error: System.ComponentModel.Win32Exception (267): An error occurred trying to start process 'C:\Users\gal\Downloads\StabilityMatrix-win-x64\Data\PortableGit\bin\git.exe' with working directory 'init'. The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at StabilityMatrix.Core.Processes.ProcessRunner.StartTrackedProcess(Process process)
   at StabilityMatrix.Core.Processes.ProcessRunner.StartAnsiProcess(String fileName, String arguments, String workingDirectory, Action`1 outputDataReceived, IReadOnlyDictionary`2 environmentVariables)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, Action`1 onProcessOutput, String workingDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.Update(InstalledPackage installedPackage, TorchVersion torchVersion, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Boolean includePrerelease, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.UpdatePackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

```

**Comment by Sceptero** [comment]
Having same issue but with Stable Diffusion WebUI updates:

```
Error: System.ComponentModel.Win32Exception (267): An error occurred trying to start process 'E:\ai\stabilitymatrix\Data\PortableGit\bin\git.exe' with working directory 'init'. The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at StabilityMatrix.Core.Processes.ProcessRunner.StartTrackedProcess(Process process)
   at StabilityMatrix.Core.Processes.ProcessRunner.StartAnsiProcess(String fileName, String arguments, String workingDirectory, Action`1 outputDataReceived, IReadOnlyDictionary`2 environmentVariables)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, Action`1 onProcessOutput, String workingDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.Update(InstalledPackage installedPackage, TorchVersion torchVersion, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Boolean includePrerelease, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.UpdatePackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

Tried removing the `PortableGit` directory hoping it might get redownloaded, but it only resulted in change of error message to:
```
An error occurred trying to start process 'E:\ai\stabilitymatrix\Data\PortableGit\bin\git.exe' with working directory 'init'. The system cannot find the file specified.
```

Perhaps the `init` working directory is the culprit?
