### ISSUE TITLE
Crash when installing or accessing packages (or settings)

### ISSUE THREAD

**Issue by Citaborg** [LykosAI/StabilityMatrix#303]
When I run the StabilityMatrix exe. I am on latest windows 11, running v 2.6.6 of StabilityMatrix.exe. The applications seems to start fine. It shows the "First install" screen. If I click on install (automatic1111 or comfyUI), or if I click "skip first time setup" and proceed to packages and click "Add Package" it crashes.

The Exception window opens with these:

Details:
The type initializer for 'System.Net.Quic.MsQuicApi' threw an exception.

Stack trace:
at System.Net.Http.HttpConnectionPool..ctor(HttpConnectionPoolManager poolManager, HttpConnectionKind kind, String host, Int32 port, String sslHostName, Uri proxyUri)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(HttpRequestMessage request, Uri proxyUri, Boolean async, Boolean doRequestAuth, Boolean isProxyConnect, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Sentry.Internal.Http.GzipBufferedRequestBodyHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Sentry.Internal.Http.RetryAfterHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Sentry.Internal.Http.HttpTransport.SendEnvelopeAsync(Envelope envelope, CancellationToken cancellationToken)
   at Sentry.Internal.BackgroundWorker.SendFinalClientReportAsync(CancellationToken cancellationToken)
   
   And inner exception:
   System.EntryPointNotFoundException: Entry point was not found.
   at System.Runtime.InteropServices.NativeLibrary.GetExport(IntPtr handle, String name)
   at System.Net.Quic.MsQuicApi..cctor()
   
Is it the program or system setup? Any hope to fix?

**Comment by ionite34** [comment]
Not sure what it is at the moment but could you try seeing if the https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.6.7 release fixes it?

**Comment by Citaborg** [comment]
No, sorry, same error on 2.6.7. 

### Debug
I cloned and pulled last main branch. Visual Studio doesn't run it out of the box. Should I be able to simply hit F5 on any of the profiles - or is this not intended? :-)

### Publish
If I publish and then run `StabilityMatrix.Avalonia.exe` it does not fail with the `System.Net.Quic.MsQuicApi` error but instead it fails unpacking and resolving asset (probably not running it correctly?) (se stack/error below).

#### Assets
Copying assets manually and modifying the `ExtractTo` method in `AvaloniaResource.cs` to not extract/write the files that exists in the assets folder the program works and is able to install packages.

#### Error running published
```
Unpacking resources
Error: System.IO.FileNotFoundException: The resource avares://StabilityMatrix.Avalonia/Assets/win-x64/7za.exe could not be found.
   at Avalonia.Platform.StandardAssetLoader.OpenAndGetAssembly(Uri uri, Uri baseUri)
   at Avalonia.Platform.StandardAssetLoader.Open(Uri uri, Uri baseUri)
   at Avalonia.Platform.AssetLoader.Open(Uri uri, Uri baseUri)
   at StabilityMatrix.Avalonia.Models.AvaloniaResource.ExtractTo(FilePath outputPath, Boolean overwrite) in X:\Repos\StabilityMatrix\StabilityMatrix.Avalonia\Models\AvaloniaResource.cs:line 49
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.UnpackResourcesIfNecessary(IProgress`1 progress) in X:\Repos\StabilityMatrix\StabilityMatrix.Avalonia\Helpers\WindowsPrerequisiteHelper.cs:line 138
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress) in X:\Repos\StabilityMatrix\StabilityMatrix.Avalonia\Helpers\WindowsPrerequisiteHelper.cs:line 117
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress) in X:\Repos\StabilityMatrix\StabilityMatrix.Core\Models\PackageModification\SetupPrerequisitesStep.cs:line 21
```

### UI-tests
I also noticed the UI unit-tests are failing. For example `StabilityMatrix.UITests.MainWindowTests.MainWindowViewModel_ShouldOk`

Comparing ´MainWindowTests.MainWindowViewModel_ShouldOk.received.txt´ with ´MainWindowTests.MainWindowViewModel_ShouldOk.verified.txt´ yields these diffs:

>    *Url: https://example.org,* (in _received_)
>    *DownloadUrl: https://example.org,* (in _verified_)

>    *Changelog: https://example.org,* (in _received_)
>    *ChangelogUrl: https://example.org,* (in _verified_)

>    *IsProgressIndeterminate: false,* (only in _received_)

>    *CurrentVersionText: v1.0.0+43430e71272d95dd4400f11c7d4c9f1da68ae307,* (in _received_)
>    *CurrentVersionText: v1.0.0,* (in _verified_)
