### ISSUE TITLE
Finding Connected Metadata (An Unexpected error occurred)

### ISSUE THREAD

**Issue by Manniala** [LykosAI/StabilityMatrix#311]
When i run the Find Connected Metadata, it go trug the scan, and same point every time, it pops the error.

```
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at StabilityMatrix.Core.Helper.ModelFinder.RemoteFindModel(String hashBlake3)
   at StabilityMatrix.Core.Services.MetadataImportService.ScanDirectoryForMissingInfo(DirectoryPath directory, IProgress`1 progress)
   at StabilityMatrix.Avalonia.ViewModels.CheckpointsPageViewModel.FindConnectedMetadata()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```
-------------

I than tried to run "Updating Existing Metadata".

```
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at StabilityMatrix.Core.Helper.ModelFinder.RemoteFindModel(String hashBlake3)
   at StabilityMatrix.Core.Services.MetadataImportService.UpdateExistingMetadata(DirectoryPath directory, IProgress`1 progress)
   at StabilityMatrix.Avalonia.ViewModels.CheckpointsPageViewModel.UpdateExistingMetadata()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)

```

I went trug every single "tab" and looked, i found 1 "Textual Inversion", i than could not scan (ofc i did not get the name ARRRG), i deleted it and, ran the scan again, this time there were NO crash or error, a shame i did not think off getting the name, or make a backup, and could not find it in Recycle Bin.

But still chose to post the error, just in case.

**Comment by ionite34** [comment]
We've added more options for connected model imports (per file with right click, per folder, or for all models) since https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.7.0, please try and let me know if the issue still occurs
