### ISSUE TITLE
1080ti cuda It's not working can't load model in package Stable Diffusion Web Ul master@03eec17

### ISSUE THREAD

**Issue by Romanio1997** [LykosAI/StabilityMatrix#314]
![zuWvwpPJu1](https://github.com/LykosAI/StabilityMatrix/assets/6834366/96b86839-1551-4a29-9977-1468694ce300)

NVIDIA driver was found. Automatically changed backend to 'cuda'. You can manually select which backend will be used through '--backend' argument. fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.1
Commit hash: 03eec1791be011e087985ae93c1f66315d5a250e
Launching Web UI with arguments: --lowvram --xformers --api --skip-python-version-check
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Loading weights [6ce0161689] from C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\configs\v1-inference.yaml
Startup time: 20.1s (prepare environment: 0.6s, import torch: 6.8s, import gradio: 2.3s, setup paths: 1.8s, initialize shared: 0.2s, other imports: 1.9s, setup codeformer: 0.2s, load scripts: 3.4s, create ui: 1.1s, gradio launch: 1.4s, add APIs: 0.4s).
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
![zuWvwpPJu1](https://github.com/LykosAI/StabilityMatrix/assets/6834366/0b231a09-4107-48f8-a55a-3781b47be8b9)

  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\initialize.py", line 147, in load_model
    shared.sd_model  # noqa: B018
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\shared_items.py", line 110, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\sd_models.py", line 544, in get_sd_model
    load_model()
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\sd_models.py", line 691, in load_model
    load_model_weights(sd_model, checkpoint_info, state_dict, timer)
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\sd_models.py", line 398, in load_model_weights
    model.load_state_dict(state_dict, strict=False)
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\sd_disable_initialization.py", line 223, in <lambda>
    module_load_state_dict = self.replace(torch.nn.Module, 'load_state_dict', lambda *args, **kwargs: load_state_dict(module_load_state_dict, *args, **kwargs))
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\sd_disable_initialization.py", line 221, in load_state_dict
    original(module, state_dict, strict=strict)
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 2027, in load_state_dict
    load(self, state_dict)
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  [Previous line repeated 4 more times]
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 2009, in load
    module._load_from_state_dict(
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\sd_disable_initialization.py", line 226, in <lambda>
    conv2d_load_from_state_dict = self.replace(torch.nn.Conv2d, '_load_from_state_dict', lambda *args, **kwargs: load_from_state_dict(conv2d_load_from_state_dict, *args, **kwargs))
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\modules\sd_disable_initialization.py", line 191, in load_from_state_dict
    module._parameters[name] = torch.nn.parameter.Parameter(torch.zeros_like(param, device=device, dtype=dtype), requires_grad=param.requires_grad)
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_meta_registrations.py", line 1780, in zeros_like
    return aten.empty_like.default(
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_ops.py", line 287, in __call__
    return self._op(*args, **kwargs or {})
  File "C:\AI\StabilityMatrix\Data\Packages\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_refs\__init__.py", line 4254, in empty_like
    return torch.empty_strided(
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 58982400 bytes.

**Comment by Thomasblod** [comment]
Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
^ I had this error and this site helped.
Also you have C++ installed right?
