### ISSUE TITLE
None of the packages are installing.

### ISSUE THREAD

**Issue by Alinka291111** [LykosAI/StabilityMatrix#316]
Hello. After starting the program and selecting any package I get this error:

Unpacking resources
Unpacking resources
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'C:\Users\mmmrrr\AppData\Roaming\StabilityMatrix\Packages\InvokeAI'...
fatal: unable to access 'https://github.com/invoke-ai/InvokeAI/': getaddrinfo() thread failed to start
}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageVersionOptions versionOptions, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

Running with administrator privileges does not help. Can you please tell me if there is a solution?

**Comment by Alinka291111** [comment]
I deleted Proxyfier, all is well >_<
