### ISSUE TITLE
Impossible to start it !

### ISSUE THREAD

**Issue by JTorresConsulta** [LykosAI/StabilityMatrix#348]
Selecting any package, this error is launched in initial package installing: 

```
.
.
.
Extracting
Extracting
Extracting
Done extracting
Tkinter install complete

Error: StabilityMatrix.Core.Exceptions.ProcessException: Process 7za failed with exit-code 2.
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7Z(String archivePath, String extractDirectory, IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.UnzipGit(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallGitIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

**Comment by JTorresConsulta** [comment]
Error launching Stable DIfusion Web UI: 


```
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.1
Commit hash: 03eec1791be011e087985ae93c1f66315d5a250e
Launching Web UI with arguments: --api --skip-torch-cuda-test --skip-python-version-check
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\AI\StabilityMatrix App\Data\Packages\Stable Diffusion Web UI\launch.py", line 48, in <module>
    main()
  File "C:\AI\StabilityMatrix App\Data\Packages\Stable Diffusion Web UI\launch.py", line 44, in main
    start()
  File "C:\AI\StabilityMatrix App\Data\Packages\Stable Diffusion Web UI\modules\launch_utils.py", line 676, in start
    import webui
  File "C:\AI\StabilityMatrix App\Data\Packages\Stable Diffusion Web UI\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\AI\StabilityMatrix App\Data\Packages\Stable Diffusion Web UI\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "C:\AI\StabilityMatrix App\Data\Packages\Stable Diffusion Web UI\modules\shared_init.py", line 26, in initialize
    dml.do_hijack()
  File "C:\AI\StabilityMatrix App\Data\Packages\Stable Diffusion Web UI\modules\dml\__init__.py", line 74, in do_hijack
    if not torch.dml.has_float64_support(device):
AttributeError: module 'torch' has no attribute 'dml'

Process finished with exit code 1
```

**Comment by JTorresConsulta** [comment]
The packages that can be installed, running in the browser launch the next error alert when generating: 

```
error
Connection errored out.
```

Then, I never can use Stability Matrix  :(
