### ISSUE TITLE
Permission Error for ComfyUI

### ISSUE THREAD

**Issue by Marcus-Arcadius** [LykosAI/StabilityMatrix#35]
![image](https://github.com/LykosAI/StabilityMatrix/assets/78793842/8aaad857-cb5b-43ae-b490-e3cabc20e63f)

Traceback (most recent call last):
  File "E:\Stable_Diffusion\Data\Packages\ComfyUI\main.py", line 123, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\Stable_Diffusion\Data\Packages\ComfyUI\main.py", line 47, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "E:\Stable_Diffusion\Data\Packages\ComfyUI\server.py", line 548, in start
    await site.start()
  File "E:\Stable_Diffusion\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "asyncio\base_events.py", line 1519, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 8188): an attempt was made to access a socket in a way forbidden by its access permissions
Venv process exited with code 1

**Comment by ionite34** [comment]
Can you check if any existing servers / webuis are running on port 8188? Try using a different port in the launch options window.
