### ISSUE TITLE
Package Modification Failed - failed to load library 'libcurl-4.dll'(v2.7.6)

### ISSUE THREAD

**Issue by MrBagietek** [LykosAI/StabilityMatrix#368]
I have problem with any interface instalation. Here is install log. Can you help me with?

Error: StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'C:\Users\UĹĽytkownik\Desktop\stabltiy\Packages\ComfyUI'...
fatal: failed to load library 'libcurl-4.dll'
}
at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageVersionOptions versionOptions, IProgress`1 progress)
at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

**Comment by MrBagietek** [comment]
The problem was with wrong non-ascii character encoding (Użytkownik in eng is user). Moving folder to C/: removed problem.
