### ISSUE TITLE
Comfyui updates seems to be broken

### ISSUE THREAD

**Issue by ethanfel** [LykosAI/StabilityMatrix#370]
Traceback (most recent call last):

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/runpy.py", line 187, in _run_module_as_main

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/runpy.py", line 146, in _get_module_details

    return _get_module_details(pkg_main_name, error)

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/runpy.py", line 110, in _get_module_details

    __import__(pkg_name)

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/site-packages/virtualenv/__init__.py", line 3, in <module>

    from .run import cli_run, session_via_cli

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/site-packages/virtualenv/run/__init__.py", line 7, in <module>

    from virtualenv.app_data import make_app_data

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/site-packages/virtualenv/app_data/__init__.py", line 11, in <module>

    from .read_only import ReadOnlyAppData

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/site-packages/virtualenv/app_data/read_only.py", line 5, in <module>

    from virtualenv.util.lock import NoOpFileLock

  File "/media/p5/StabilityMatrix/Assets/Python310/lib/python3.10/site-packages/virtualenv/util/lock.py", line 12, in <module>

    from filelock import FileLock, Timeout

ModuleNotFoundError: No module named 'filelock'

Error: StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1
   at StabilityMatrix.Core.Python.PyVenvRunner.Setup(Boolean existsOk, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.Update(InstalledPackage installedPackage, TorchVersion torchVersion, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Boolean includePrerelease, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.UpdatePackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

**Comment by ionite34** [comment]
Hm, this is quite strange, seems the embedded python's virtualenv is missing dependencies. Could you open a command prompt in the SM Data directory and run
```
./Assets/Python310/python.exe -m pip install virtualenv --force-reinstall
```

**Comment by ethanfel** [comment]
> Hm, this is quite strange, seems the embedded python's virtualenv is missing dependencies. Could you open a command prompt in the SM Data directory and run
> 
> ```
> ./Assets/Python310/python.exe -m pip install virtualenv --force-reinstall
> ```
> 
> Then if that is successful try running the update again.

Worked, thank you very much
