### ISSUE TITLE
[issune] git.exe error in extentions installing [and solution]

### ISSUE THREAD

**Issue by kaitas** [LykosAI/StabilityMatrix#372]
It caused error since a few months in git.exe error when I tried to install new extensions.
I tried to install something new extentions via "Install from URL" tab in extentions (instead of git clone command, outside of SM)

> GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --filter=blob:none -- [https://github.com/(extention's](https://github.com/(extentions) repo) D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\tmp\(extention's name) stderr: 'Cloning into 'D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\tmp\(extention's name)'... fatal: unable to access 'https://github.com/miZyind/sd-webui-latent-couple/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) '

I could solve this error by using this command in cmd.exe,
```git config --global http.sslVerify false```

a case of error log in console:
```
*** Error completing request
*** Arguments: ('', 'https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper', '') {}
    Traceback (most recent call last):
      File "D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\ui_extensions.py", line 638, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\ui_extensions.py", line 367, in install_extension_from_url
        with git.Repo.clone_from(url, tmpdir, filter=['blob:none']) as repo:
      File "D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1327, in clone_from
        return cls._clone(
      File "D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1236, in _clone
        finalize_process(proc, stderr=stderr)
      File "D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\util.py", line 419, in finalize_process
        proc.wait(**kwargs)
      File "D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 604, in wait
        raise GitCommandError(remove_password_if_present(self.args), status, errstr)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git clone -v --filter=blob:none -- https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\tmp\Stable-Diffusion-Webui-Civitai-Helper
      stderr: 'Cloning into 'D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\tmp\Stable-Diffusion-Webui-Civitai-Helper'...
    fatal: unable to access 'https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013)
    '
```
Do ```git config --global http.sslVerify false```

> Installed into D:\StabilityMatrix-win-x64\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper. Use Installed tab to restart.

Don't forget to set this config after this force installing :-)
```git config --global http.sslVerify true```

**Comment by kaitas** [comment]
for future references, maybe user need to add 
> --share --enable-insecure-extension-access
for launch valuables.
