### ISSUE TITLE
Unable to Install in Windows 11 - getting VEnv creation error

### ISSUE THREAD

**Issue by RJSavell** [LykosAI/StabilityMatrix#378]
When I try to install the current StabilityMatrix I am getting the following error messages:

Error: StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1:

Error: StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1
   at StabilityMatrix.Core.Python.PyVenvRunner.Setup(Boolean existsOk, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.SetupVenv(String installedPackagePath, String venvName, Boolean forceRecreate, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

I can create VEnv's manually from Python so I am not sure what is causing this issue.

Any help would be greatly appreciated.

**Comment by RJSavell** [comment]
I was able to resolve this issue by removing the AppData\Roaming\StabilityMatrix directory and reinstalling
