### ISSUE TITLE
[V2.7.6] Package Modification Failed

### ISSUE THREAD

**Issue by sunlery** [LykosAI/StabilityMatrix#384]
Unpacking resources
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process 7za failed with exit-code 2.
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Core.Helper.ArchiveHelper.Extract7Z(String archivePath, String extractDirectory, IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.UnzipGit(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallGitIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

**Comment by Lxrdew** [comment]
Создай папку на другом диске и перенеси туда exe файл, потом в настройках матрикса путь укажи в эту же папку
