### ISSUE TITLE
Stable Diffusion Extensions fail to update due to UKNOWN

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#386]
I don't know if this is a Stab Matrix or Stable Diffusion 1.7 issue so I am posting in both places.

SD models: 0.3s, load scripts: 32.7s, create ui: 2.0s, gradio launch: 13.1s, add APIs: 0.2s).
*** Failed reading extension data from Git repository (sd-webui-replacer)
    Traceback (most recent call last):
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\extensions.py", line 129, in do_read_info_from_repo
        commit = repo.head.commit
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\refs\symbolic.py", line 226, in _get_commit
        obj = self._get_object()
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\refs\symbolic.py", line 219, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\objects\base.py", line 94, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\db.py", line 40, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\gitpython_hack.py", line 18, in get_object_header
        ret = subprocess.check_output(
      File "subprocess.py", line 421, in check_output
      File "subprocess.py", line 505, in run
      File "subprocess.py", line 1154, in communicate
      File "subprocess.py", line 1546, in _communicate
    subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds

Here is a screen capture of more:
![adetailer, a person generator, sdface editor, etc UKNOWN](https://github.com/LykosAI/StabilityMatrix/assets/132060667/48373065-b52f-4f45-babc-f9becf5bbc90)

**Comment by drdancm** [comment]
> I don't know if this is a Stab Matrix or Stable Diffusion 1.7 issue so I am posting in both places. Unfortunately my post in Stable Diff failed due to an inability for them to accept one of the required fill in windows.
> 
> SD models: 0.3s, load scripts: 32.7s, create ui: 2.0s, gradio launch: 13.1s, add APIs: 0.2s). *** Failed reading extension data from Git repository (sd-webui-replacer) Traceback (most recent call last): File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\extensions.py", line 129, in do_read_info_from_repo commit = repo.head.commit File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\refs\symbolic.py", line 226, in _get_commit obj = self._get_object() File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\refs\symbolic.py", line 219, in _get_object return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path))) File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\objects\base.py", line 94, in new_from_sha oinfo = repo.odb.info(sha1) File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\git\db.py", line 40, in info hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha)) File "D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\modules\gitpython_hack.py", line 18, in get_object_header ret = subprocess.check_output( File "subprocess.py", line 421, in check_output File "subprocess.py", line 505, in run File "subprocess.py", line 1154, in communicate File "subprocess.py", line 1546, in _communicate subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds
> 
> Here is a screen capture of more: ![adetailer, a person generator, sdface editor, etc UKNOWN](https://private-user-images.githubusercontent.com/132060667/294435011-48373065-b52f-4f45-babc-f9becf5bbc90.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODg0ODEsIm5iZiI6MTcwNDY4ODE4MSwicGF0aCI6Ii8xMzIwNjA2NjcvMjk0NDM1MDExLTQ4MzczMDY1LWI1MmYtNGY0NS1iYWJjLWY5YmVjZjViYmM5MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQwNDI5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjUwYmI4MjlhYzAxM2IwY2RkNTM3MWQyZjg1N2ExYTI3NmFlNjU0NWUxMjE4ZGQ2ZTg1ZDA2ZTVjMWI2MDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OwLcu_SLGnFBPFc7augNPwnxxk1bYEP7iUvRVOAzZfs)
