### ISSUE TITLE
Argument Out of Range Exception on Showing all Packages.

### ISSUE THREAD

**Issue by MonsterAzi** [LykosAI/StabilityMatrix#403]
I get this error upon checking the "Show all Packages" checkbox in package installation:
```
ArgumentOutOfRangeException.
Details
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Callstack
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.InstallerViewModel.<>c__DisplayClass100_1.<OnSelectedVersionChanged>b__1()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
   ```

**Comment by MonsterAzi** [comment]
This may also be the cause of a bug which prevents me from installing Fooocus-MRE (It has no versions and the display name copies the name of the last selected package).

**Comment by MonsterAzi** [comment]
(Sorry, accidentally closed).
