### ISSUE TITLE
Package Modication Failed：Failure when receiving data from the peer

### ISSUE THREAD

**Issue by sunlery** [LykosAI/StabilityMatrix#406]
`Done extracting
Node install complete
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'E:\AI\Soft\StabilityMatrix\StabilityMatrix\Data\Packages\Stable Diffusion WebUI'...
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/': Failure when receiving data from the peer
}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageVersionOptions versionOptions, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)`
![1](https://github.com/LykosAI/StabilityMatrix/assets/20901030/086ae3c3-90c8-4d7d-a83b-a84848613043)

**Comment by ionite34** [comment]
Seems like a temporary network issue with git, check that `https://github.com/AUTOMATIC1111/stable-diffusion-webui` is accessible on your network and retry.
