### ISSUE TITLE
Issue starting InvokeAI 3.6.0

### ISSUE THREAD

**Issue by MedTaha4Ever** [LykosAI/StabilityMatrix#410]
Launch gives:
```
<string>:14: UserWarning: Could not patch terminal size for InvokeAINo module named 'npyscreen'
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\app\api_app.py", line 43, in <module>
    from .api.dependencies import ApiDependencies
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\app\api\dependencies.py", line 5, in <module>
    from invokeai.app.services.shared.sqlite.sqlite_util import init_db
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\app\services\shared\sqlite\sqlite_util.py", line 7, in <module>
    from invokeai.app.services.shared.sqlite_migrator.migrations.migration_2 import build_migration_2
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\app\services\shared\sqlite_migrator\migrations\migration_2.py", line 14, in <module>
    from .util.migrate_yaml_config_1 import MigrateModelYamlToDb1
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\app\services\shared\sqlite_migrator\migrations\util\migrate_yaml_config_1.py", line 15, in <module>
    from invokeai.app.services.model_records import (
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\app\services\model_records\__init__.py", line 2, in <module>
    from .model_records_base import (  # noqa F401
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\app\services\model_records\model_records_base.py", line 10, in <module>
    from invokeai.backend.model_manager.config import AnyModelConfig, BaseModelType, ModelFormat, ModelType
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\backend\model_manager\__init__.py", line 14, in <module>
    from .probe import ModelProbe
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\backend\model_manager\probe.py", line 25, in <module>
    from .hash import FastModelHash
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\backend\model_manager\hash.py", line 16, in <module>
    from imohash import hashfile
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\venv\lib\site-packages\imohash\__init__.py", line 1, in <module>
    from .imohash import hashfile, hashfileobject
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\venv\lib\site-packages\imohash\imohash.py", line 10, in <module>
    import varint
ModuleNotFoundError: No module named 'varint'

Process finished with exit code 1
```
Configure gives:
```
<string>:14: UserWarning: Could not patch terminal size for InvokeAINo module named 'npyscreen'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: DLL load failed while importing libtriton: The specified module could not be found.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\frontend\install\invokeai_configure.py", line 4, in <module>
    from ...backend.install.invokeai_configure import main as invokeai_configure  # noqa: F401
  File "C:\SDXL\StabilityMatrix-win-x64\Data\Packages\InvokeAI\invokeai\backend\install\invokeai_configure.py", line 24, in <module>
    import npyscreen
ModuleNotFoundError: No module named 'npyscreen'

Process finished with exit code 1
```

**Comment by illuculent** [comment]
Same Issue
