### ISSUE TITLE
Package Modification Failed (Every Time Without Fail)

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [LykosAI/StabilityMatrix#414]
No matter where I put the AppImage, and even after attempting to remove all the files, deleting the directory and then trying again, it won't let me modify any packages anymore. This is the error:

`Unpacking resources
Unpacking resources
Download complete!
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process  exited with code 127. {StdOut = , StdErr = /home/username/Documents/Stability Matrix/Data/Assets/Python310/bin/pip3: line 2: /home/username/Documents
Matrix/Data/Assets/Python310/bin/python3.10: No such file or directory
}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Core.Python.PyRunner.InstallPackage(String package)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPythonIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
`

**Comment by KUPOinyourWINDOW** [comment]
Figured it out, the issue was that the directory I was storing everything in had a space. Changing it from "Stability Matrix" to "Stability-Matrix" solved it.
