### ISSUE TITLE
ERROR INSTALL INVOKE, MACOS M1MAX

### ISSUE THREAD

**Issue by thienbaogithub** [LykosAI/StabilityMatrix#464]
Unpacking resources
Unpacking resources
Download Complete
created virtual environment CPython3.10.11.final.0-64 in 145ms

  creator CPython3Posix(dest=/Applications/Data/Packages/InvokeAI/venv, clear=False, no_vcs_ignore=False, global=False)

  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/thienbao/Library/Application Support/virtualenv)

    added seed packages: pip==23.3.2, setuptools==69.0.3, wheel==0.42.0

  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Could not install InvokeAI (StabilityMatrix.Core.Exceptions.ProcessException: npm command [/Applications/Data/Assets/nodejs/bin/npm i vite] failed with exit code 254:

npm ERR! code ENOENTnpm ERR! syscall spawn shnpm ERR! path /Applications/Data/Packages/InvokeAI/node_modules/esbuildnpm ERR! errno -2npm ERR! enoent spawn sh ENOENTnpm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent npm ERR! A complete log of this run can be found in: /Users/thienbao/.npm/_logs/2024-02-16T01_15_42_992Z-debug-0.log
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.RunNpm(ProcessArgs args, String workingDirectory, Action`1 onProcessOutput, IReadOnlyDictionary`2 envVars) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Avalonia/Helpers/UnixPrerequisiteHelper.cs:line 301
   at StabilityMatrix.Core.Models.Packages.InvokeAI.SetupAndBuildInvokeFrontend(String installLocation, IProgress`1 progress, Action`1 onConsoleOutput, IReadOnlyDictionary`2 envVars) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/InvokeAI.cs:line 300
   at StabilityMatrix.Core.Models.Packages.InvokeAI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/InvokeAI.cs:line 193
   at StabilityMatrix.Core.Models.Packages.InvokeAI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/InvokeAI.cs:line 283
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/PackageModification/InstallPackageStep.cs:line 37
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/PackageModification/PackageModificationRunner.cs:line 35)

**Comment by dagaz** [comment]
After changing the AppImage file (to a newer version; updating the old one did not work) I have the same Problem with installing and also with starting an installed InvokeAI.

![grafik](https://github.com/LykosAI/StabilityMatrix/assets/2174841/eff52da4-944f-42a0-8ecf-eddf40b829a9)

**Comment by os-coder** [comment]
Same error here with Linux. InvokeAI runs fine stand alone.

**Comment by Morethanevil** [comment]
Same here

```
Unpacking resources
Unpacking resources
Download Complete
created virtual environment CPython3.10.11.final.0-64 in 100ms

  creator CPython3Posix(dest=/home/user/tools/stabilitymatrix/Data/Packages/InvokeAI/venv, clear=False, no_vcs_ignore=False, global=False)

  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mte/.local/share/virtualenv)

    added seed packages: pip==24.0, setuptools==69.1.0, wheel==0.42.0

  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Could not install InvokeAI (StabilityMatrix.Core.Exceptions.ProcessException: npm command [/home/user/tools/stabilitymatrix/Data/Assets/nodejs/bin/npm i vite] failed with exit code 254:

npm ERR! code ENOENTnpm ERR! syscall spawn shnpm ERR! path /home/user/tools/stabilitymatrix/Data/Packages/InvokeAI/node_modules/esbuildnpm ERR! errno -2npm ERR! enoent spawn sh ENOENTnpm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent npm ERR! A complete log of this run can be found in: /home/mte/.npm/_logs/2024-02-28T08_06_01_159Z-debug-0.log
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.RunNpm(ProcessArgs args, String workingDirectory, Action`1 onProcessOutput, IReadOnlyDictionary`2 envVars)
   at StabilityMatrix.Core.Models.Packages.InvokeAI.SetupAndBuildInvokeFrontend(String installLocation, IProgress`1 progress, Action`1 onConsoleOutput, IReadOnlyDictionary`2 envVars)
   at StabilityMatrix.Core.Models.Packages.InvokeAI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.InvokeAI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))

```
