### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by TheSrBig** [LykosAI/StabilityMatrix#465]
2024-02-15 22:20:32,945 - ControlNet - INFO - unit_separate = False, style_align = False
*** Error running process: C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 894, in controlnet_main_entry
        model_net, control_model_type = Script.load_control_model(p, unet, unit.model)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 367, in load_control_model
        control_model = Script.build_control_model(p, unet, model)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 377, in build_control_model
        raise RuntimeError(f"You have not selected any ControlNet Model.")
    RuntimeError: You have not selected any ControlNet Model.

---
*** Error completing request
*** Arguments: ('task(xxgc99rh0p26bh0)', '1girl, long hair, blonde hair, yellow eyes, demon horns, long hair, masterpiece, bikini, beach, sunlight, arms up, lying,', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x0000020BADBC1ED0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, UiControlNetUnit(enabled=True, module='none', model='None', weight=1, image={'image': array([[[ 21,  21,  21],
***         [ 20,  20,  20],
***         [ 20,  20,  20],
***         ...,
***         [  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0]],
*** 
***        [[ 20,  20,  20],
***         [ 20,  20,  20],
***         [ 19,  19,  19],
***         ...,
***         [  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0]],
*** 
***        [[ 19,  19,  19],
***         [ 19,  19,  19],
***         [ 19,  19,  19],
***         ...,
***         [  0,   0,   0],
***         [  0,   0,   0],
***         [  0,   0,   0]],
*** 
***        ...,
*** 
***        [[230, 230, 230],
***         [230, 230, 230],
***         [230, 230, 230],
***         ...,
***         [136, 136, 136],
***         [136, 136, 136],
***         [137, 137, 137]],
*** 
***        [[230, 230, 230],
***         [230, 230, 230],
***         [230, 230, 230],
***         ...,
***         [137, 137, 137],
***         [138, 138, 138],
***         [138, 138, 138]],
*** 
***        [[231, 231, 231],
***         [230, 230, 230],
***         [230, 230, 230],
***         ...,
***         [138, 138, 138],
***         [139, 139, 139],
***         [139, 139, 139]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
*** 
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
*** 
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
*** 
***        ...,
*** 
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
*** 
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
*** 
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Crop and Resize', low_vram=True, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='My prompt is more important', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\processing.py", line 857, in process_images_inner
        p.setup_conds()
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\processing.py", line 1308, in setup_conds
        super().setup_conds()
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\processing.py", line 469, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\processing.py", line 455, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\prompt_parser.py", line 188, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
        c = self.cond_stage_model(c)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\sd_hijack_clip.py", line 234, in forward
        z = self.process_tokens(tokens, multipliers)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\sd_hijack_clip.py", line 273, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\modules\sd_hijack_clip.py", line 326, in encode_with_transformers
        outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 822, in forward
        return self.text_model(
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 740, in forward
        encoder_outputs = self.encoder(
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 654, in forward
        layer_outputs = encoder_layer(
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 382, in forward
        hidden_states = self.layer_norm1(hidden_states)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 531, in network_LayerNorm_forward
        return originals.LayerNorm_forward(self, input)
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\normalization.py", line 196, in forward
        return F.layer_norm(
      File "C:\Users\Diego\Downloads\Compressed\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2543, in layer_norm
        return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
    RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

---

**Comment by mohnjiles** [comment]
Depending on which GPU you use, you may need to enable the `--no-half` command line option. You can find these in the cogwheel button next to the Launch button.
