### ISSUE TITLE
Install packages on linux is impossible.

### ISSUE THREAD

**Issue by Strawberrycake1417** [LykosAI/StabilityMatrix#484]
Hello,

Tested on Arch and Fedora, any package that i try to install return me an error : 

Unpacking resources
Unpacking resources
Download complete!
Error: System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
 ---> System.DllNotFoundException: Could not load /home/user/Downloads/StabilityMatrix-linux-x64/Data/Assets/Python310/lib/libpython3.10.so with flags RTLD_NOW | RTLD_GLOBAL: libcrypt.so.1: cannot open shared object file: No such file or directory
   at Python.Runtime.Platform.PosixLoader.Load(String dllToLoad)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.PythonEngine.<>c.<set_PythonHome>b__27_0()
   at Python.Runtime.Runtime.<>c__DisplayClass106_0.<TryUsingDll>b__0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.TryUsingDll(Action op)
   at Python.Runtime.PythonEngine.set_PythonHome(String value)
   at StabilityMatrix.Core.Python.PyRunner.Initialize()
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPythonIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPackageRequirements(List`1 prerequisites, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

**Comment by dougvan1701** [comment]
Install libxcrypt-compat
