### ISSUE TITLE
(on Mac Book M2 Max) Failed to launch ComfyUI with AttributeError: module 'mpmath' has no attribute 'rational'

### ISSUE THREAD

**Issue by taoxu0903** [LykosAI/StabilityMatrix#490]
on Mac book M2 Max, After installing ComfyUI and tried to launch it, met below error:

Total VRAM 32768 MB, total RAM 32768 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Traceback (most recent call last):
  File "/Applications/Data/Packages/ComfyUI/main.py", line 76, in <module>
    import execution
  File "/Applications/Data/Packages/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/Applications/Data/Packages/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/Applications/Data/Packages/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/Applications/Data/Packages/ComfyUI/comfy/sd.py", line 7, in <module>
    from .ldm.cascade.stage_c_coder import StageC_coder
  File "/Applications/Data/Packages/ComfyUI/comfy/ldm/cascade/stage_c_coder.py", line 19, in <module>
    import torchvision
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torchvision/ops/poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torchvision/ops/roi_align.py", line 4, in <module>
    import torch._dynamo
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 31, in <module>
    from torch.fx.experimental.symbolic_shapes import (
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/fx/experimental/symbolic_shapes.py", line 63, in <module>
    from torch.utils._sympy.functions import FloorDiv, Mod, IsNonOverlappingAndDenseIndicator
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_sympy/functions.py", line 1, in <module>
    import sympy
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/sympy/__init__.py", line 30, in <module>
    from sympy.core.cache import lazy_function
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/sympy/core/__init__.py", line 9, in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/sympy/core/expr.py", line 4159, in <module>
    from .mul import Mul
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/sympy/core/mul.py", line 2193, in <module>
    from .numbers import Rational
  File "/Applications/Data/Packages/ComfyUI/venv/lib/python3.10/site-packages/sympy/core/numbers.py", line 4567, in <module>
    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
AttributeError: module 'mpmath' has no attribute 'rational'

Process finished with exit code 1

**Comment by adityaprakashucd** [comment]
Newest release of mpmath seems to be the issue. Downgrading to 1.3.0 fixed it for me.

`source /Applications/Data/Packages/ComfyUI/venv/bin/activate
pip install mpmath==1.3.0`

**Comment by taoxu0903** [comment]
thanks and it works well! shall it point to 1.3.0 mpmath on master/main branch until latest mpmatch fixed its bug? today StabilityMatrix can only allow to select master/main when installing ComfyUI, while installing SD webUI both version and branch can be freely selected.
