### ISSUE TITLE
What is the correct way to install ControlNet for A1111 using Stability Matrix

### ISSUE THREAD

**Issue by p-veloso** [LykosAI/StabilityMatrix#493]
I have just started exploring Stability Matrix as a way for my students to quickly install Automatic1111, ComfyUI, etc. So far, the experience has been fantastic. 

However, there are some small details that do not seem to be working. For example, I am able to install the ControlNets models from Hugging Face using the tab model browser and I can load them in ComfyUI with the nodes However, the ControlNet A1111 extension/menu is not available. Therefore, I decided to install it by loading A1111 and using its own extension tab and the url https://github.com/Mikubill/sd-webui-controlnet. After that, the ControlNet menu is available when I load A1111 but it is not able to work properly. Is this the right way of proceeding?

**Comment by p-veloso** [comment]
I assume the answer is the same as in #494 - i.e., using the extensions installer in the menu packages.

**Comment by p-veloso** [comment]
However, in this case it does not work as it triggers a RuntimeError...

```
2024-03-03 14:41:02,000 - ControlNet - INFO - unit_separate = False, style_align = False
*** Error running process: C:\Users\pedro\OneDrive\BK documents\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\pedro\OneDrive\BK documents\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "C:\Users\pedro\OneDrive\BK documents\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1275, in process
        self.controlnet_hack(p)
      File "C:\Users\pedro\OneDrive\BK documents\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1260, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\pedro\OneDrive\BK documents\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 936, in controlnet_main_entry
        model_net, control_model_type = Script.load_control_model(p, unet, unit.model)
      File "C:\Users\pedro\OneDrive\BK documents\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 367, in load_control_model
        control_model = Script.build_control_model(p, unet, model)
      File "C:\Users\pedro\OneDrive\BK documents\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 377, in build_control_model
        raise RuntimeError("You have not selected any ControlNet Model.")
    RuntimeError: You have not selected any ControlNet Model.
```
