### ISSUE TITLE
An unexptected error occured: when searching for "Space"

### ISSUE THREAD

**Issue by zeonos** [LykosAI/StabilityMatrix#50]
![image](https://github.com/LykosAI/StabilityMatrix/assets/6930544/e0ee82e1-c2c3-42a7-8fe8-1bf167e19eec)

I reproduced this error 3 times, all i did was go into the model browser and search for **space**

```
at System.Collections.Generic.List`1.get_Item(Int32 index)
   at StabilityMatrix.Avalonia.ViewModels.CheckpointBrowserCardViewModel.CheckIfInstalled()
   at StabilityMatrix.Avalonia.ViewModels.CheckpointBrowserCardViewModel..ctor(CivitModel civitModel, IDownloadService downloadService, ISettingsManager settingsManager, ServiceManager`1 dialogFactory, INotificationService notificationService)
   at StabilityMatrix.Avalonia.ViewModels.CheckpointBrowserViewModel.<UpdateModelCards>b__35_0(CivitModel model)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at StabilityMatrix.Avalonia.ViewModels.CheckpointBrowserViewModel.UpdateModelCards(IEnumerable`1 models, CivitMetadata metadata)
   at StabilityMatrix.Avalonia.ViewModels.CheckpointBrowserViewModel.SearchModels()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```

**Comment by CodeZombie** [comment]
Quick note:
I was able to reproduce this, but only with when I had `Sort` set to `MostDownloaded` or `HighestRated`, and `Model Type` set to  `LORA`.
Every other model type, and sorting mode `Newest` seems to work without error.

**Comment by zeonos** [comment]
> Quick note: I was able to reproduce this, but only with when I had
> 
> * `Sort` set to `MostDownloaded` or `HighestRated`, and
> * `Model Type` set to  `LORA`.
> 
> Every other model type, and sorting mode `Newest` seems to work without error.

I can confirm, but if i go to page 4 it crashes, so there must be a Lora name or something that breaks it.

**Comment by mohnjiles** [comment]
Thanks for the report! I think I found the issue, should get fixed in the next release.
