### ISSUE TITLE
Could not install stable-diffusion-webui (StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1

### ISSUE THREAD

**Issue by funkinaoki** [LykosAI/StabilityMatrix#501]
Trying to install Stable Diffusion WebUI from StablityMatrix, but this error "Package Modification Failed" comes out. I could install and use ComfyUI.
Error code:
```
Unpacking resources
Unpacking resources
Download Complete
C:\Users\my_name\AppData\Local\Temp\0ec8c814-55da-41a5-b69d-fa251c113653_StabilityMatrix-win-x64.zip.653\Data\Assets\Python310\python.exe: No module named virtualenv

Could not install stable-diffusion-webui (StabilityMatrix.Core.Exceptions.ProcessException: Venv creation failed with code 1
   at StabilityMatrix.Core.Python.PyVenvRunner.Setup(Boolean existsOk, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))

```
![image](https://github.com/LykosAI/StabilityMatrix/assets/70941852/24c2199e-a088-4d42-bca7-9d8f446f5ab9)
[Stable Diffusion WebUI Folder]
![image](https://github.com/LykosAI/StabilityMatrix/assets/70941852/bc0b4f00-32a5-4298-ad06-9bf2311c992a)
[Stable Diffusion WebUI Folder / venv]
![image](https://github.com/LykosAI/StabilityMatrix/assets/70941852/f202a82a-093c-4393-be6d-7825f48fe812)

<Environment>

- OS: Windows 10
- Python(stability matrix): 3.10.11
- Stability matrix version: 2.9.0

**Comment by p-veloso** [comment]
I am not sure what the official solution is, but it seems that your Python does not have the [virtualenv](https://pypi.org/project/virtualenv/) library, so it is not able to create a custom environment for the package. You can try to install it manually in your command line with pip.

`pip install virtualenv`

**Comment by ratzorizzo69** [comment]
same problem here for v 2.9.0
