### ISSUE TITLE
Stable diffusion model failed to load

### ISSUE THREAD

**Issue by zeonos** [LykosAI/StabilityMatrix#51]
I am running the portable install on a AMD 6900 XT and using Stabel Diffusion WebUI v1.5.1, i tried to install a new package but get the same error.

I tried removing the model it mentions, but then it just shows another model and come with the same error.

I also tried with version 1.5.0 but got the same result.

I tried with ComfyUI and SD.Next and both works.

Before trying out StabilityMatrix i was using a Automatic1111 install without any issues.

```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.5.1
Commit hash: <none>
Installing clip
Cloning Stable Diffusion into C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\stable-diffusion-stability-ai...
Cloning into 'C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\stable-diffusion-stability-ai'...
Cloning Stable Diffusion XL into C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\generative-models...
Cloning into 'C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\generative-models'...
Cloning K-diffusion into C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\k-diffusion...
Cloning into 'C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\k-diffusion'...
Cloning CodeFormer into C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\CodeFormer...
Cloning into 'C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\CodeFormer'...
Cloning BLIP into C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\BLIP...
Cloning into 'C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\BLIP'...
Installing requirements for CodeFormer
Launching Web UI with arguments: --api --skip-torch-cuda-test --skip-python-version-check
C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Exception in thread Thread-21 (first_time_calculation):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\devices.py", line 167, in first_time_calculation
    linear(x)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions-builtin\Lora\networks.py", line 361, in network_Linear_forward
    return torch.nn.Linear_forward_before_network(self, input)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
Calculating sha256 for C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\models\Stable-diffusion\Anime\animesh_PrunedV21.safetensors: Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 50.9s (launcher: 36.9s, import torch: 3.8s, import gradio: 1.4s, setup paths: 1.5s, other imports: 1.6s, setup codeformer: 0.1s, list SD models: 0.2s, load scripts: 4.8s, create ui: 0.2s, gradio launch: 0.2s).
8bf3cc2354364cdf16dfcf7aaff1587ced86a718734807067830f4a14651ae70
Loading weights [8bf3cc2354] from C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\models\Stable-diffusion\Anime\animesh_PrunedV21.safetensors
Creating model from config: C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: InvokeAI... done.
Calculating sha256 for C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\embeddings\Clutter-Home.pt: af80173633cf9b9deee468a752acefbb9dcfca41a1adc315058104183a693532
Calculating sha256 for C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\embeddings\Clutter-Mechanical.pt: 7bfdb20388cd3511db6fb0b0d0f2868729b9fca121a1314c7ebb1b180fa6b43d
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\webui.py", line 318, in load_model
    shared.sd_model  # noqa: B018
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\shared.py", line 754, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_models.py", line 439, in get_sd_model
    load_model()
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_models.py", line 536, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_models.py", line 460, in get_empty_cond
    return sd_model.cond_stage_model([""])
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_hijack_clip.py", line 271, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_hijack_clip.py", line 324, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
    return self.text_model(
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 721, in forward
    encoder_outputs = self.encoder(
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 650, in forward
    layer_outputs = encoder_layer(
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 378, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\modules\normalization.py", line 190, in forward
    return F.layer_norm(
  File "C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'


Stable diffusion model failed to load

```

**Comment by ionite34** [comment]
Do you know if you were using ROCm PyTorch with A1111 before on your machine?

**Comment by zeonos** [comment]
That gave me the following and i still get the error, i am running on Windows 10.

```
C:\Users\zeonos\Downloads\StabilityMatrix-win-x64\Data\Packages\Automatic1111>venv\Scripts\python.exe -m pip install --upgrade --force-reinstall torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/rocm5.1.1
Collecting torch
  Using cached torch-2.0.1-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision
  Using cached torchvision-0.15.2-cp310-cp310-win_amd64.whl (1.2 MB)
Collecting filelock (from torch)
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/00/45/ec3407adf6f6b5bf867a4462b2b0af27597a26bd3cd6e2534cb6ab029938/filelock-3.12.2-py3-none-any.whl.metadata
  Using cached filelock-3.12.2-py3-none-any.whl.metadata (2.7 kB)
Collecting typing-extensions (from torch)
  Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
  Downloading typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Collecting sympy (from torch)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx (from torch)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting jinja2 (from torch)
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting numpy (from torchvision)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/8d/07/cab4129005dba3f170dd1a2cfa312fc71100f0e26b91f7fc659b6b5abbdc/numpy-1.25.1-cp310-cp310-win_amd64.whl.metadata
  Downloading numpy-1.25.1-cp310-cp310-win_amd64.whl.metadata (5.7 kB)
Collecting requests (from torchvision)
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Obtaining dependency information for pillow!=8.3.*,>=5.3.0 from https://files.pythonhosted.org/packages/d0/4f/faebe1180e5e6ad6330c539dda7f6081182157393ba6816a438f759a0e59/Pillow-10.0.0-cp310-cp310-win_amd64.whl.metadata
  Downloading Pillow-10.0.0-cp310-cp310-win_amd64.whl.metadata (9.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Obtaining dependency information for MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/84/a8/c4aebb8a14a1d39d5135eb8233a0b95831cdc42c4088358449c3ed657044/MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl.metadata
  Downloading MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Collecting charset-normalizer<4,>=2 (from requests->torchvision)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/5c/f2/f3faa20684729d3910af2ee142e30432c7a46a817eadeeab87366ed87bbb/charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl.metadata
  Downloading charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl.metadata (31 kB)
Collecting idna<4,>=2.5 (from requests->torchvision)
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->torchvision)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl.metadata
  Downloading urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests->torchvision)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting mpmath>=0.19 (from sympy->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached Pillow-10.0.0-cp310-cp310-win_amd64.whl (2.5 MB)
Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Using cached numpy-1.25.1-cp310-cp310-win_amd64.whl (15.0 MB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
   ---------------------------------------- 158.3/158.3 kB ? eta 0:00:00
Using cached charset_normalizer-3.2.0-cp310-cp310-win_amd64.whl (96 kB)
Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.16
    Uninstalling urllib3-1.26.16:
      Successfully uninstalled urllib3-1.26.16
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.5.0
    Uninstalling Pillow-9.5.0:
      Successfully uninstalled Pillow-9.5.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
  Attempting uninstall: networkx
    Found existing installation: networkx 3.1
    Uninstalling networkx-3.1:
      Successfully uninstalled networkx-3.1
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 2.1.3
    Uninstalling MarkupSafe-2.1.3:
      Successfully uninstalled MarkupSafe-2.1.3
  Attempting uninstall: idna
    Found existing installation: idna 3.4
    Uninstalling idna-3.4:
      Successfully uninstalled idna-3.4
  Attempting uninstall: filelock
    Found existing installation: filelock 3.12.2
    Uninstalling filelock-3.12.2:
      Successfully uninstalled filelock-3.12.2
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.2.0
    Uninstalling charset-normalizer-3.2.0:
      Successfully uninstalled charset-normalizer-3.2.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2023.7.22
    Uninstalling certifi-2023.7.22:
      Successfully uninstalled certifi-2023.7.22
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.2
    Uninstalling Jinja2-3.1.2:
      Successfully uninstalled Jinja2-3.1.2
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1
    Uninstalling torch-2.0.1:
      Successfully uninstalled torch-2.0.1
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.15.2
    Uninstalling torchvision-0.15.2:
      Successfully uninstalled torchvision-0.15.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 10.0.0 which is incompatible.
google-auth 2.22.0 requires urllib3<2.0, but you have urllib3 2.0.4 which is incompatible.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.25.1 which is incompatible.
Successfully installed MarkupSafe-2.1.3 certifi-2023.7.22 charset-normalizer-3.2.0 filelock-3.12.2 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.25.1 pillow-10.0.0 requests-2.31.0 sympy-1.12 torch-2.0.1 torchvision-0.15.2 typing-extensions-4.7.1 urllib3-2.0.4
```

**Comment by zeonos** [comment]
> 

I used this guide to set it up

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs

**Comment by ionite34** [comment]
Closing as stale or unable to reproduce, please try latest release and create a new issue if needed: https://github.com/LykosAI/StabilityMatrix/releases/latest
