### ISSUE TITLE
Can't open ComfyUI after new SM update (2.9.1)

### ISSUE THREAD

**Issue by Tromazing** [LykosAI/StabilityMatrix#517]
Since updating, I now get the following information when trying to launch ComfyUI:

** ComfyUI startup time: 2024-03-13 10:57:17.384048
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\StableDiffusion\Packages\ComfyUI\venv\Scripts\python.exe
** Log path: D:\StableDiffusion\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\StableDiffusion\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\StableDiffusion\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "D:\StableDiffusion\Packages\ComfyUI\main.py", line 76, in <module>
    import execution
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "D:\StableDiffusion\Packages\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "D:\StableDiffusion\Packages\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\StableDiffusion\Packages\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "D:\StableDiffusion\Packages\ComfyUI\comfy\model_management.py", line 38, in <module>
    import torch_directml
  File "D:\StableDiffusion\Packages\ComfyUI\venv\lib\site-packages\torch_directml\__init__.py", line 16, in <module>
    import torch_directml_native
ImportError: DLL load failed while importing torch_directml_native: The specified procedure could not be found.

Process finished with exit code 1

**Comment by ionite34** [comment]
What GPU are you using and did you know if you were using torch DirectML originally?

**Comment by Tromazing** [comment]
AMD 6700XT, and yes I think I was. I haven't changed any settings, just updated SM.
