### ISSUE TITLE
SD.Next / ComfyUI Install: Unexpected Error

### ISSUE THREAD

**Issue by PresTrembleyIIIEsq** [LykosAI/StabilityMatrix#54]
I'm on a fresh Manjaro installation with everything up to date, and I ran `git clone https://github.com/LykosAI/StabilityMatrix`, then downloaded and ran the .AppImage file. I left the default settings (including leaving Portable Mode off), but when I try to install either SD.Next or ComfyUI, I get the error below.

The last section calls out /root/.config/StabilityMatrix/Assets/Python310/lib/libpython3.10.so, but on my system it looks like that file is located at /home/[myuser]/.config/StabilityMatrix/Assets/Python310/lib/libpython.310.so - did I install or set this up incorrectly?

----

An unexpected error occured
`TypeInitializationException`

Details
`The type initializer for 'Delegates' threw an exception.`

Callstack
   ```
at Python.Runtime.Runtime.Delegates.get_Py_SetPythonHome()
   at Python.Runtime.Runtime.Py_SetPythonHome(IntPtr home)
   at Python.Runtime.PythonEngine.<>c.<set_PythonHome>b__27_0()
   at Python.Runtime.Runtime.<>c__DisplayClass106_0.<TryUsingDll>b__0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.TryUsingDll(Action op)
   at Python.Runtime.PythonEngine.set_PythonHome(String value)
   at StabilityMatrix.Core.Python.PyRunner.Initialize()
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPythonIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallAllIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.DoInstall()
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.Install()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.The type initializer for 'Delegates' threw an exception.11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```

Inner exception
```
System.DllNotFoundException: Could not load /root/.config/StabilityMatrix/Assets/Python310/lib/libpython3.10.so with flags RTLD_NOW | RTLD_GLOBAL: libcrypt.so.1: cannot open shared object file: No such file or directory
   at Python.Runtime.Platform.PosixLoader.Load(String dllToLoad)
   at Python.Runtime.Runtime.Delegates.GetUnmanagedDll(String libraryName)
   at Python.Runtime.Runtime.Delegates..cctor()
```

**Comment by ionite34** [comment]
Hi, it seems python is missing a shared library, try installing `libxcrypt-compat` using your package manager of choice <https://archlinux.org/packages/core/x86_64/libxcrypt-compat/>

**Comment by PresTrembleyIIIEsq** [comment]
Looks like that did it - thanks!

**Comment by Shadow8472** [comment]
Thanks! This fix worked for me as well. While researching this issue, I found many references to the same error for different applications on Arch-based systems (EndeavourOS, Manjaro, and of course Arch [by the way]).
