### ISSUE TITLE
Error while trying to install interface while first use: InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by Maveyyl** [LykosAI/StabilityMatrix#545]
Hello,

I'm on Windows 11

I tried to install with the windows installer. It shows me a screen to install an interface. Any item I click ends up with the error:

InvalidOperationException: Sequence contains no matching element

at System.Linq.ThrowHelper.ThrowNoMatchException()
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
at StabilityMatrix.Avalonia.ViewModels.Dialogs.RecommendedModelsViewModel.<>c.<OnLoadedAsync>b__20_0(CivitModel model)
at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
at DynamicData.Cache.Internal.CacheUpdater`2.AddOrUpdate(IEnumerable`1 items) in /_/src/DynamicData/Cache/Internal/CacheUpdater.cs:line 58

It closes and I don't have time to copy more of the stack trace.

I've looked in the logs, and first there were an error that said \Assets\Python310\get-pip.pyc was missing. I retrieved it from the sources and put the file where it should be. Then I get a different error in the logs:

2024-03-27 02:07:32.7955|DEBUG|StabilityMatrix.Core.Processes.ProcessRunner|Starting process 'C:\Users\me\AppData\Roaming\StabilityMatrix\Assets\Python310\python.exe' with arguments '-m pip install virtualenv'
2024-03-27 02:07:32.7955|DEBUG|StabilityMatrix.Core.Helper.ProcessTracker|Adding process '"python"' [10356] to job object
2024-03-27 02:07:32.8412|ERROR|StabilityMatrix.Avalonia.Extensions.NotificationServiceExtensions|Error Installing Package|StabilityMatrix.Core.Exceptions.ProcessException: Process python exited with code 1. {StdOut = , StdErr = C:\Users\me\AppData\Roaming\StabilityMatrix\Assets\Python310\python.exe: No module named pip
}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Core.Python.PyRunner.InstallPackage(String package)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallVirtualenvIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.InstallPackageRequirements(List`1 prerequisites, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)

**Comment by LovelornKnight** [comment]
same error

**Comment by LovelornKnight** [comment]
Did you install Python before SM? I did. Maybe that's the problem I guess.

**Comment by AJpon** [comment]
This only seems to happen when using the setup interface for the first time.
You can work around the problem by cleaning up your environment and setting it up manually

Please uninstall and reinstall the software.
After that, please try the steps in the following video

https://github.com/LykosAI/StabilityMatrix/assets/49616225/b55426e7-da8e-4f9d-88fd-fe17a8df64ba

 1. Skip Setup
 2. Go Settings
 3. Check "Embedded Python" Version
 4. Go Packages and install any package you like!
 5. Enjoy!

**Comment by Maveyyl** [comment]
Thanks for your reply. With your instructions it worked!

**Comment by mohnjiles** [comment]
Also, to clarify, installing Python manually should not be necessary, Stability Matrix should handle that for you.

**Comment by CCCP1997** [comment]
EN_hello everyone, I've been honestly puzzling over this error for 8 days and tried it. I found the Pluto version on the receipt and just downloaded it.  
https://github.com/LykosAI/StabilityMatrix/tree/main/StabilityMatrix
 and I threw everything into the StabilityMatrix and I got the start of a setup at least for focus
RU _
всем привет   по поводу этой ошибке  честно 8 день   ломал голову пробовал  . нашимал на чек версию плутона и в этоге  просто скачал  
https://github.com/LykosAI/StabilityMatrix/tree/main/StabilityMatrix
 и кинул все в  StabilityMatrix  и   уменя начало  устоновка хотябы фоокуса
