### ISSUE TITLE
Missing ICU package in AppImage

### ISSUE THREAD

**Issue by kelvinhammond** [LykosAI/StabilityMatrix#554]
On nixos when I run `appimage-run ./StabilityMatrix.AppImage` I get the following error. I've tried installing the icu packages (all of them) and none of them seem to provide what is needed. Which package ICU package is required for the app image on Linux?

```
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.MemoryExtensions.ToLowerInvariant(System.ReadOnlySpan`1<Char>, System.Span`1<Char>)
   at System.UriHelper+<>c.<SpanToLowerInvariantString>b__0_0(System.Span`1<Char>, IntPtr)
   at System.String.Create[[System.IntPtr, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, IntPtr, System.Buffers.SpanAction`2<Char,IntPtr>)
   at System.UriHelper.SpanToLowerInvariantString(System.ReadOnlySpan`1<Char>)
   at System.Uri.CheckSchemeSyntax(System.ReadOnlySpan`1<Char>, System.ParsingError ByRef)
   at System.Uri.ParseSchemeCheckImplicitFile(System.String, System.ParsingError ByRef, Flags ByRef, System.UriParser ByRef)
   at System.Uri.ParseScheme(System.String, Flags ByRef, System.UriParser ByRef)
   at System.Uri.CreateThis(System.String, Boolean, System.UriKind, System.UriCreationOptions ByRef)
   at System.Uri..ctor(System.String)
   at StabilityMatrix.Avalonia.Program..cctor()
   at StabilityMatrix.Avalonia.Program.Main(System.String[])
````

I can get it to run via `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY=false appimage-run ./StabilityMatrix.AppImage` with the latest version ([v2.9.2](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.9.2)) though.

However I get this error after closing the model selection on first run, 
I selected to install `Stable Diffusion Web UI` and it failed.

```
Unpacking resources
Unpacking resources
Download complete!
Error: System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
 ---> System.DllNotFoundException: Could not load /tmp/stability-matrix/Assets/Python310/lib/libpython3.10.so with flags RTLD_NOW | RTLD_GLOBAL: libcrypt.so.1: cannot open shared object file: No such file or directory
   at Python.Runtime.Platform.PosixLoader.Load(String dllToLoad)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.PythonEngine.<>c.<set_PythonHome>b__27_0()
   at Python.Runtime.Runtime.<>c__DisplayClass106_0.<TryUsingDll>b__0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.TryUsingDll(Action op)
   at Python.Runtime.PythonEngine.set_PythonHome(String value)
   at StabilityMatrix.Core.Python.PyRunner.Initialize()
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPythonIfNecessary(IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPackageRequirements(List`1 prerequisites, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

**Comment by nozpheratu** [comment]
@kelvinhammond  You need libcrypt under your shared libraries, specifically an older version of libcrypt so you get libcrypt.so.1 under you path. [libxcrypt-legacy](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=libxcrypt) has that.

Try this nix shell:

```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  buildInputs = [
    #pkgs.libxcrypt
    pkgs.libxcrypt-legacy
  ];

  shellHook = ''
    export LD_LIBRARY_PATH=${pkgs.libxcrypt-legacy}/lib:$LD_LIBRARY_PATH
    echo "LD_LIBRARY_PATH is set to $LD_LIBRARY_PATH"
  '';
}
```

**Comment by UnclePsymon** [comment]
> @kelvinhammond You need libcrypt under your shared libraries, specifically an older version of libcrypt so you get libcrypt.so.1 under you path. [libxcrypt-legacy](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=libxcrypt) has that.
> 
> Try this nix shell:
> 
> ```nix
> { pkgs ? import <nixpkgs> {} }:
> pkgs.mkShell {
>   buildInputs = [
>     #pkgs.libxcrypt
>     pkgs.libxcrypt-legacy
>   ];
> 
>   shellHook = ''
>     export LD_LIBRARY_PATH=${pkgs.libxcrypt-legacy}/lib:$LD_LIBRARY_PATH
>     echo "LD_LIBRARY_PATH is set to $LD_LIBRARY_PATH"
>   '';
> }
> ```

I tried your shell on NixOS and StableMatrix launches. But it gets me this error in StableMatrix:
```

## Exception
```ArgumentOutOfRangeException: The path '/tmp/nix-shell-197430-0/nix-shell-198613-0/nix-shell-200945-0/nix-shell-210642-0/nix-shell-215713-0/nix-shell-220488-0/CoreFxPipe_StabilityMatrix' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 108 characters, inclusive. (Parameter 'path')
Actual value was /tmp/nix-shell-197430-0/nix-shell-198613-0/nix-shell-200945-0/nix-shell-210642-0/nix-shell-215713-0/nix-shell-220488-0/CoreFxPipe_StabilityMatrix.```
### Sentry ID
[`abfd6b03`](https://stability-matrix.sentry.io/issues/?query=id%3Aabfd6b039aee4e57956603e34b24d870&referrer=sm-app-ex&statsPeriod=90d)
### Stack Trace
```   at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path, String boundFileName)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount, Boolean isFirstPipeInstance)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount, PipeOptions pipeOptions)
   at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
   at MessagePipe.Interprocess.Workers.NamedPipeWorker.<CreateLazyServerStream>b__13_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at MessagePipe.Interprocess.Workers.NamedPipeWorker.StartReceiver()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at StabilityMatrix.Avalonia.ViewModels.MainWindowViewModel.OnInitialLoadedAsync()
   at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException](Task task, Boolean continueOnCapturedContext, Action`1 onException)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)```
```

**Comment by XDM-Inc** [comment]
> [libxcrypt-legacy](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=libxcrypt) has that.
> 

i had the same issue here in fedora, installing that fixed it! looks like linux devs depreciated libxcrypt too soon it seems, the new replacement is NOT ready and is NOT backwards compatible.

**Comment by kelvinhammond** [comment]
I tried `libxcrypt-legacy` and it still didn't work. I get the same icu error.

**Comment by UnclePsymon** [comment]
I can run it with the `shell.nix` file, but I still have to do this from the cmd: `export DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY=false && export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`. There are still a few error messages here and there, but it works for now :)

**Comment by AuricViolet** [comment]
Don't know if you are still having this issue, but I was able to get mine to run by installing FUSE from the nix packages and re-downloading / extracting the appimage.

`  environment.systemPackages = [
    pkgs.fuse
  ];`

Then I ran `appimage-run StabilityMatrix.AppImage` in the directory my app image extracted to.

In addition to that I added the following pkgs to configuration.nix - not sure they had any effect though.
`  pkgs.icu
  pkgs.libxcrypt
  pkgs.libxcrypt-legacy
`

Hope this helps! :)

**Comment by AuricViolet** [comment]
After days of searching for a way to run this and a few other AppImages, I found a better solution from someone on another thread.

You can specify extra libraries to look for when running AppImages directly in your configuration.nix with:

    programs.appimage.package

Running the AppImage with execute permissions and the following code in my configuration.nix just works:

  ```
programs.appimage.enable = true;
  programs.appimage.binfmt = true;
  programs.appimage.package = pkgs.appimage-run.override { extraPkgs = pkgs: [
  pkgs.icu
  pkgs.libxcrypt-legacy
  pkgs.python312
  pkgs.python312Packages.torch
  ]; };

```

And also this further down the config under environment.systemPackages:

```
environment.systemPackages = with pkgs; [
   pkgs.appimage-run
];
```

No issues, no warnings, and I just run the AppImage with ./yourappimagenamehere or by double clicking it from the file browser. If I ever see a missing lib again when running an AppImage, I'll just add it to this extraPkgs list.

This should work for any AppImage file as well.

Hope this helps!  :)

**Comment by abowen** [comment]
> After days of searching for a way to run this and a few other AppImages, I found a better solution from someone on another thread.
> 
> You can specify extra libraries to look for when running AppImages directly in your configuration.nix with:
> 
> ```
> programs.appimage.package
> ```
> 
> Running the AppImage with execute permissions and the following code in my configuration.nix just works:
> 
> ```
> programs.appimage.enable = true;
> programs.appimage.binfmt = true;
> programs.appimage.package = pkgs.appimage-run.override { extraPkgs = pkgs: [
> pkgs.icu
> pkgs.libxcrypt-legacy
> pkgs.python312
> pkgs.python312Packages.torch
> ]; };
> ```
> 
> And also this further down the config under environment.systemPackages:
> 
> ```
> environment.systemPackages = with pkgs; [
>    pkgs.appimage-run
> ];
> ```
> 
> No issues, no warnings, and I just run the AppImage with ./yourappimagenamehere or by double clicking it from the file browser. If I ever see a missing lib again when running an AppImage, I'll just add it to this extraPkgs list.
> 
> This should work for any AppImage file as well.
> 
> Hope this helps! :)

Thankyou, this certainly got me further but I can't download ComfyUI, etc. 

Getting the following error

```
System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
 ---> System.DllNotFoundException: Could not load /home/ai/lykos/Data/Assets/Python310/lib/libpython3.10.so with flags RTLD_NOW | RTLD_GLOBAL: libcrypt.so.1: cannot open shared object file: No such file or directory
   at Python.Runtime.Platform.PosixLoader.Load(String dllToLoad)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.PythonEngine.<>c.<set_PythonHome>b__27_0()
   at Python.Runtime.Runtime.<>c__DisplayClass106_0.<TryUsingDll>b__0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.TryUsingDll(Action op)
   at Python.Runtime.PythonEngine.set_PythonHome(String value)
   at StabilityMatrix.Core.Python.PyRunner.InitializeWithInstallation(PyInstallation installation)
   at StabilityMatrix.Core.Python.PyRunner.Initialize()
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallVirtualenvIfNecessary(PyVersion version, IProgress`1 progress)
   at StabilityMatrix.Avalonia.Helpers.UnixPrerequisiteHelper.InstallPackageRequirements(List`1 prerequisites, Nullable`1 pyVersion, IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.SetupPrerequisitesStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps)
```

It seems `libxcrypt-legacy` is the correct approach

e.g.

- https://github.com/LykosAI/StabilityMatrix/issues/484
- https://github.com/LykosAI/StabilityMatrix/issues/742

But it doesn't seem to work for me.

Also tried

`nix-shell -p libxcrypt-legacy`

and

```
programs.nix-ld.enable = true;
programs.nix-ld.libraries = with pkgs; [
    libxcrypt-legacy
 ];
```

But neither worked

**Comment by SmarakNayak** [comment]
@abowen based on this thread, I put together a Nix flake that packages the StabilityMatrix AppImage with the required dependencies (icu, libxcrypt-legacy, uv) already included, so no manual configuration needed:

[stability-matrix-nix](  https://github.com/SmarakNayak/stability-matrix-nix
)

It auto-updates hourly via GitHub Actions. Feedback welcome!
