### ISSUE TITLE
Getting this issue while trying to fetch metadate of the Lora or when I am trying to browse the lora in checkpoints section

### ISSUE THREAD

**Issue by saadkhan955** [LykosAI/StabilityMatrix#559]
## Exception
ArgumentException: Unable to load bitmap from provided data
### Sentry ID
```
376de1a90ff748908486172164a4e7b7
```
### Stack Trace
```
   at Avalonia.Skia.ImmutableBitmap..ctor(Stream stream)
   at Avalonia.Skia.PlatformRenderInterface.LoadBitmap(String fileName)
   at Avalonia.Labs.Controls.AsyncImage.SetSource(Object source) in /_/src/Avalonia.Labs.Controls/AsyncImage/AsyncImage.cs:line 141
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```

**Comment by mohnjiles** [comment]
Thanks for the repot! It seems to happen when the default thumbnail for a model is a video instead of an image. If you delete the offending image/video file in the Models directory it should fix it for now, though we'll have a permanent fix in the next update.
