### ISSUE TITLE
No such file or directory: 'requirements_windows_torch2.txt'

### ISSUE THREAD

**Issue by radecic** [LykosAI/StabilityMatrix#569]
when installing kohya_ss from the 2.9.3 version ... the install bombs out due to not able to ifnd the requriments file. 

`
  File "C:\Users\rad\Downloads\stabilityMatrix\Packages\kohya_ss\setup\setup_sm.py", line 4, in <module>

    setup_common.install_requirements('requirements_windows_torch2.txt', check_no_verify_flag=False)

  File "C:\Users\rad\Downloads\stabilityMatrix\Packages\kohya_ss\setup\setup_common.py", line 641, in install_requirements

    with open(requirements_file, 'r', encoding='utf8') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'requirements_windows_torch2.txt'

Could not install kohya_ss (StabilityMatrix.Core.Exceptions.ProcessException: install script failed with code 1: 'Traceback (most recent call last):\r\n  File "C:\Users\rad\Downloads\stabilityMatrix\Packages\kohya_ss\setup\setup_sm.py", line 4, in <module>\r\n    setup_common.install_requirements('requirements_windows_torch2.txt', check_no_verify_flag=False)\r\n  File "C:\Users\rad\Downloads\stabilityMatrix\Packages\kohya_ss\setup\setup_common.py", line 641, in install_requirements\r\n    with open(requirements_file, 'r', encoding='utf8') as f:\r\nFileNotFoundError: [Errno 2] No such file or directory: 'requirements_windows_torch2.txt'\r\n'`

**Comment by radecic** [comment]
if i modify the setup_sm.py file it is overwritten from the GUI every time the install is triggered.

**Comment by radecic** [comment]
awesome! now working in the latest 2.10 release! THANK YOU!!
