### ISSUE TITLE
Mac OS v2.1.0 stable: after a crash the comfyui process is still active

### ISSUE THREAD

**Issue by thetrebor** [LykosAI/StabilityMatrix#577]
When the application hard crashes, eg when you drag a jpeg into an image area, the webserver is not terminated properly.  You need to go into the terminal, find the process with the port open, and kill it manually.
Ideally the application would recognize that 8188 is taken and can probably tell it was an orphan from a previous instantiation of stability matrix

Traceback (most recent call last):
  File "/Users/TheTrebor/Projects/SDModels/Packages/ComfyUI/main.py", line 246, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "/Users/TheTrebor/Projects/SDModels/Assets/Python310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/TheTrebor/Projects/SDModels/Packages/ComfyUI/main.py", line 148, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "/Users/TheTrebor/Projects/SDModels/Packages/ComfyUI/server.py", line 633, in start
    await site.start()
  File "/Users/TheTrebor/Projects/SDModels/Packages/ComfyUI/venv/lib/python3.10/site-packages/aiohttp/web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "/Users/TheTrebor/Projects/SDModels/Assets/Python310/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 8188): address already in use

**Comment by thetrebor** [comment]
for people who find this from the web

lsof -i tcp:8188
kill [PID]
