### ISSUE TITLE
[Windows v2.10.0 stable] A1111/Forge Dependency Installation Errors ('distutils.core' import failed?)

### ISSUE THREAD

**Issue by bosconian-dynamics** [LykosAI/StabilityMatrix#578]
This is my first time using StabilityMatrix, but I can't seem to get past installing the basic dependencies for either the "Stable Diffusion WebUI" or "Stable Diffusion WebUI Forge" packages. Other package installations have been successful, however (ComfyUI, InvokeAI).

Both package installations fail in the "Package Modification" dialogue detailing the following error:
```
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
...
python setup.py egg_info did not run successfully
...
        File "X:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 57, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: X:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\Scripts\python310.zip\distutils\core.pyc
...
× Encountered error while generating package metadata.
...
pip install failed with code 1
```
For A1111 this error occurs under the `Collecting filterpy (from facexlib==0.3.0)` entry. For Forge, `Collecting basicsr==1.4.2`.

**EDIT:** [Potential Work-around](#issuecomment-2052444485)

# Environment #

- **OS**
  Windows 10 Pro x64, Version 22H2, Build 19045.4170, Feature Experience Pack 1000.19054.1000.0
- **StabilityMatrix version**
  2.10.0 (stable)
- **StabilityMatrix config**
  Fresh installation, portable, executable path `X:\StabilityMatrix\StabilityMatrix.exe`
- **Environment**
  Other versions of Python, mingw, git, and pip are installed on my system and available on my system path, if that might be relevant.

# Package Info #

- **Stable Diffusion WebUI**
  **Releases:** ✔
  **Version:** v1.8.0
- **Stable Diffusion WebUI Forge**
  **Branch:** main

# Error Logs #
The log/errors I receive within the "Package Modification" dialogues, truncated to what I believe to be the relevant bits. The full "Package Modification" logs in their entirety are available below via links to a paste site.

## A1111/Stable Diffusion WebUI (v1.8.0 release) ##
[Full Log](https://gdl.space/danarituwu.py)
```py
Collecting filterpy (from facexlib==0.3.0)
  Using cached filterpy-1.4.5.zip (177 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "X:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\setuptools\__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
        File "X:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "X:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 70, in do_override
          ensure_local_distutils()
        File "X:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 57, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: X:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI\venv\Scripts\python310.zip\distutils\core.pyc
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

```py
(StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1:

...

   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))
```

## Stable Diffusion WebUI Forge (main branch) ##
[Full Log](https://gdl.space/emitidovoh.sql)
```py
Collecting basicsr==1.4.2
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "X:\StabilityMatrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\setuptools\__init__.py", line 7, in <module>
          import _distutils_hack.override  # noqa: F401
        File "X:\StabilityMatrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "X:\StabilityMatrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\_distutils_hack\__init__.py", line 70, in do_override
          ensure_local_distutils()
        File "X:\StabilityMatrix\Data\Packages\stable-diffusion-webui-forge\venv\lib\site-packages\_distutils_hack\__init__.py", line 57, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: X:\StabilityMatrix\Data\Packages\stable-diffusion-webui-forge\venv\Scripts\python310.zip\distutils\core.pyc
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

```py
Error: StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1:

...

   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.SDWebForge.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.SDWebForge.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

**Comment by MrPropre** [comment]
I have the exact same problem

**Comment by Liso7150** [comment]
i have same problem

**Comment by bosconian-dynamics** [comment]
I might have found a functional work-around, but I'll preface this by saying that I'm not at familiar with Python and stumbled upon this by blindly poking at things. I have no idea if changing this setting could have any broader consequence or complication.

1. Close StabilityMatrix if it is open.
2. Set the environment variable `SETUPTOOLS_USE_DISTUTILS` to `stdlib`.
3. Open StabilityMatrix and install one of the problematic packages.
4. Close StabilityMatrix.
5. Delete the `SETUPTOOLS_USE_DISTUTILS` environment variable.

**Alternately (untested, but I think it should work):**
1. Delete your pip package caches (evidently `%LOCALAPPDATA%/pip` and `%LOCALAPPDATA%/pypa` on my system).
2. Install the ComfyUI SM package.
3. Install the problematic SM packages.

The environment variable forces the package installation to use a version of "distutils" distributed with Python rather than one from the `setuptools` package, which appears to alleviate the issue for me 🤷.

It looks like performing a single installation with the environment variable set affects the pip package cache such that it may not be necessary to keep the environment variable set for subsequent SM package installations. [The v2.10.0 release notes](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.10.0) mention having made this the default setting for the ComfyUI package to rectify installation issues with that specific package, but apparently the issue and that solution may be more broadly applicable.

Since the setting seemingly affects the pip cache, it looks like installing ComfyUI on a fresh SM installation prior to any other package may forego the problem entirely.

**Comment by mohnjiles** [comment]
Thanks for the detailed report and work-around! We should have a permanent fix coming soon, but feel free to use the environment variable workaround in the meantime.

**Comment by Liso7150** [comment]
where is stdlib?
