### ISSUE TITLE
Mac 2.10.1: Crashes when typing in the packages terminal window

### ISSUE THREAD

**Issue by thetrebor** [LykosAI/StabilityMatrix#589]
Application crash when typing in the packages terminal window

![Screenshot 2024-04-14 at 7 07 34 PM](https://github.com/LykosAI/StabilityMatrix/assets/305910/3b56e6fa-6612-4a24-9bd8-7d85d81456f9)

## Exception
IOException:

 Broken pipe
### Sentry ID
```
8349a3213cde4e259308506cf21e24f4
```
### Stack Trace
```
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.IO.StreamWriter.WriteAsyncInternal(ReadOnlyMemory`1 source, Boolean appendNewLine, CancellationToken cancellationToken)
   at StabilityMatrix.Avalonia.ViewModels.RunningPackageViewModel.SendToConsole() in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Avalonia/ViewModels/RunningPackageViewModel.cs:line 153
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnPlatformThreadingInterfaceEventsVTable.Signaled(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Avalonia/Program.cs:line 126
```
## Inner Exception
SocketException: Broken pipe
### Stack Trace
```
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.SendAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.StreamWriter.<FlushAsyncInternal>g__Core|76_0(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.IO.StreamWriter.FlushAsyncInternal(Boolean flushStream, Boolean flushEncoder, CancellationToken cancellationToken)
   at System.IO.StreamWriter.WriteAsyncInternal(ReadOnlyMemory`1 source, Boolean appendNewLine, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.StreamWriter.WriteAsyncInternal(ReadOnlyMemory`1 source, Boolean appendNewLine, CancellationToken cancellationToken)
   at System.IO.StreamWriter.WriteLineAsync(String value)
   at StabilityMatrix.Avalonia.ViewModels.RunningPackageViewModel.SendToConsole() in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Avalonia/ViewModels/RunningPackageViewModel.cs:line 151
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at StabilityMatrix.Avalonia.ViewModels.RunningPackageViewModel.SendToConsole()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.ExecuteAsync(Object parameter)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.RootDefaultKeyDown(Object sender, KeyEventArgs e)
   at InvokeStub_Action`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Native.WindowBaseImpl.RawKeyEvent(AvnRawKeyEventType type, UInt64 timeStamp, AvnInputModifiers modifiers, AvnKey key, AvnPhysicalKey physicalKey, String keySymbol)
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.RawKeyEvent(AvnRawKeyEventType type, UInt64 timeStamp, AvnInputModifiers modifiers, AvnKey key, AvnPhysicalKey physicalKey, String keySymbol)
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.RawKeyEvent(Void* this, AvnRawKeyEventType type, UInt64 timeStamp, AvnInputModifiers modifiers, AvnKey key, AvnPhysicalKey physicalKey, Byte* keySymbol)
   at Avalonia.Native.Interop.Impl.__MicroComIAvnPlatformThreadingInterfaceProxy.RunLoop(IAvnLoopCancellation cancel)
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Avalonia/Program.cs:line 126
--- End of stack trace from previous location ---
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
```

**Comment by thetrebor** [comment]
UPDATE:
typing into most search boxes causes the application to CTD
