### ISSUE TITLE
SD Next > Models directories getting reset in config.json

### ISSUE THREAD

**Issue by demoran23** [LykosAI/StabilityMatrix#60]
I've modified my config.json (which can happen through the SD.Next webui in Settings) to point to a drive that holds my models.  These are getting overwritten by StabilityMatrix on startup, pointing back to the AppData folders.

Perhaps drawing this up as a configuration setting for Stability Matrix would be appropriate.

**Comment by ionite34** [comment]
We'll look to add to all packages a config for setting the shared folder link to `config / symlink / disabled`

**Comment by yakesakabanbo** [comment]
Launch
03
Stable Diffusion WebUl
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v. 1929 64 bit (AMD64)]
Version: 1.5.1
Commit hash: <none>
Installing clip
Cloning Stable Diffusion into D: \STDWUI\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion
WebUI\repositories\stable-diffusion-stability-ai.
' "C: \Program Files\Git' OADODOOROZOOOhO DODOODOROLDOODOA
Traceback (most recent call last):
File "D: \STDWUI\StabilityMatrix-win-×64\Data\Packages\Stable Diffusion WebUI\launch.py", line 39, in <module>
main0)
File "D: \STDWUI\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\launch.py", line 30, in main prepare_environment ()
File "D: \STDWUI\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\launch_utils.py", line 345, in prepare_environment
git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
File "D: \STDWUI\StabilityMatrix-win x64\Data\Packages \Stable Diffusion WebUI\modules\launch_utils.py", line 159, in git_clone
run(f'"{git]" clone "furl]" "{dir}"', f'Cloning {name} into {dir}
...",
f"Couldn't clone {name}", live=True)
File "D: \STDWUI\StabilityMatrix-win-×64\Data\Packages \Stable Diffusion WebUI\modules \launch_utils.py", line 113, in run raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't clone Stable Diffusion.
Command: "C: \Program Files\Git" clone "https://github.com/Stability-AI/stablediffusion.git"
"D: \STDWUI\StabilityMatrix-win-×64\Data\ Packages \Stable Diffusion WebUI\repositories\stable-diffusion-stability-ai"
Error code: 1
Process finished with exit code 1


When I installed the launcher, I got the above error. I would like to know how to deal with this.

**Comment by ionite34** [comment]
Closing for now since switched from config to symlinks for SD.Next in https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.2.1
