### ISSUE TITLE
Forge UI not working 

### ISSUE THREAD

**Issue by Salamala893** [LykosAI/StabilityMatrix#602]
ImportError: cannot import name 'Undefined' from 'pydantic.fields'

I also have installed Fooocus, Automatic1111 and ComfyUI

**Comment by SkGirlUru** [comment]
same problem

**Comment by dhstsw** [comment]
Same.
Complete starting logs:

`Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Installing clip
Cloning assets into H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\stable-diffusion-webui-assets...
Cloning into 'H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\stable-diffusion-webui-assets'...
Cloning Stable Diffusion into H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\stable-diffusion-stability-ai...
Cloning into 'H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\stable-diffusion-stability-ai'...
Cloning Stable Diffusion XL into H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\generative-models...
Cloning into 'H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\generative-models'...
Cloning K-diffusion into H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\k-diffusion...
Cloning into 'H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\k-diffusion'...
Cloning BLIP into H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\BLIP...
Cloning into 'H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\repositories\BLIP'...
H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Installing forge_legacy_preprocessor requirement: fvcore
Installing forge_legacy_preprocessor requirement: mediapipe
Installing forge_legacy_preprocessor requirement: onnxruntime
Installing forge_legacy_preprocessor requirement: svglib
Installing forge_legacy_preprocessor requirement: insightface
Installing forge_legacy_preprocessor requirement: handrefinerportable
Installing forge_legacy_preprocessor requirement: depth_anything
H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --gradio-allowed-path H:\SM\SMData\Images
Total VRAM 16376 MB, total RAM 32644 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Traceback (most recent call last):
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\launch.py", line 51, in <module>
    main()
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\launch.py", line 47, in main
    start()
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\modules\launch_utils.py", line 541, in start
    import webui
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\webui.py", line 19, in <module>
    initialize.imports()
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\modules\initialize.py", line 35, in imports
    import gradio  # noqa: F401
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "H:\SM\SMData\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (H:\SM\SMData\Packages\Stable Diffusion WebUI `Forge\venv\lib\site-packages\pydantic\fields.py)``

**Comment by ionite34** [comment]
Seems to related to one of their upstream dependencies breaking it by updating pydantic to a version that's too new https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/674

Easiest way to fix is probably by adding a strict version requirement for pydantic in their requirements txt file (since the install and update is done at runtime by them after our initial install)

But if Forge upstream doesn't issue a fix soon we can look to do a file edit when installing to fix it on our end for now.

**Comment by vova2698** [comment]
If the problem is still here change the pydantic version from 2.7.1 to 2.7 in python package

**Comment by Koitenshin** [comment]
Issue is still here as of June 10th, 2024 but thanks to vova2698's image instructions, it was easily remedied.
