### ISSUE TITLE
HttpRequestException

### ISSUE THREAD

**Issue by Ippephyx** [LykosAI/StabilityMatrix#620]
Hi, I keep having an HttpRequestException each and everytime an http request is needed : I can't install an interface : it will kill the app with the exception, I can't "check" the "embedded python" : same exception.
The only thing it lets me is check CivitAI API and / or connect to Lykos Account, but that's about it.

Any help will be greatly appreciated.

Thanks 
![image](https://github.com/LykosAI/StabilityMatrix/assets/59560947/bb2be1cb-f9c7-45f0-8880-9022f2ce666a)

**Comment by camilo1505** [comment]
Same problem:
`## Exception
TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
### Sentry ID
a2856db33d464ff78d037e7f2d696952
### Stack Trace
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_02.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 256
--- End of stack trace from previous location ---
   at StabilityMatrix.Avalonia.ViewModels.OpenArtBrowserViewModel.DoSearch(Int32 page)
   at AsyncAwaitBestPractices.SafeFireAndForgetExtensions.HandleSafeFireAndForget[TException](Task task, Boolean continueOnCapturedContext, Action1 onException)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
## Inner Exception
TimeoutException: A task was canceled.`
