### ISSUE TITLE
(Bug)When trying to install Prompt expansion V2 for inference an Error Appears

### ISSUE THREAD

**Issue by LadyFlames** [LykosAI/StabilityMatrix#634]
ERROR: Could not install packages due to an OSError: [WinError 5] Access Denied: 'D:\\Stability Matrix\\Packages\\ComfyUI\\venv\\Lib\\site-packages\\onnxruntime\\capi\\onnxruntime_providers_shared.dll'
Check the permissions.

Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py", line 38, in <module>
    main()
  File "D:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py", line 29, in main
    pip_install(["-e", ".[cuda-12]"])
  File "D:\Stability Matrix\Packages\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\install.py", line 11, in pip_install
    subprocess.check_call(
  File "subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['D:\\Stability Matrix\\Packages\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-e', '.[cuda-12]']' returned non-zero exit status 1.
Error: StabilityMatrix.Core.Exceptions.ProcessException: install.py for ComfyUI-Inference-Core-Nodes exited with code 1
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.PostInstallAsync(InstalledPackage installedPackage, IEnumerable`1 installedDirs, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.PostInstallAsync(InstalledPackage installedPackage, IEnumerable`1 installedDirs, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.InstallExtensionAsync(PackageExtension extension, InstalledPackage installedPackage, PackageExtensionVersion version, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
i get this error when trying to install Prompt Expansion V2 straight from inference tab or from Comfy UI Extensions Tab and  im using Win11 could that be it 
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion'
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
  File "D:\Stability Matrix\Packages\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Stability Matrix\Packages\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Inference_Core_PromptExpansion' more errors

**Comment by LadyFlames** [comment]
lets hope this gets fixed someday

**Comment by id1740** [comment]
> lets hope this gets fixed someday

up

**Comment by airtonix** [comment]
I feel like you should be able to download the models manually from https://huggingface.co/LykosAI/GPT-Prompt-Expansion-Fooocus-v2/tree/main and put them "somewhere?"

**Comment by thill3132** [comment]
Yes, you can in your models folder under PromptExpansion.

Truthfully though, it doesn't help much with your prompt (I think that's why they are adding LLM enhancement) the better workflow I've had has been using Wan2GP's prompt enhancer then just copying and pasting that into ComfyUI or inference to generate better images. 

The GPT-Prompt_expansion that you linked, I have tried and it just adds a few things that don't really help but can cause my intended image to go somewhere else entirely. However, if you'd like to try it, just place the contents of your link in your model directory -> PromptExpansion

Then it should show up in the list to use. You can rename the .bin to be GPT-Prompt-Expansion-Fooocus-v2.bin

If you use it and get really good results, let us know how you did it haha
