### ISSUE TITLE
Install of Automatic11111 fails to start

### ISSUE THREAD

**Issue by lludlow** [LykosAI/StabilityMatrix#647]
First time install, no extensions. I tried with release and branch, both resulted in the same issue.

Install directly from git there is no issue.

> 

Python 3.10.11 (main, May  7 2023, 19:26:31) [Clang 16.0.3 ]
Version: v1.9.3
Commit hash: 1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0
Launching Web UI with arguments: --api --listen --enable-insecure-extension-access --gradio-allowed-path /ai/StabilityMatrix/Images
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/launch.py", line 48, in <module>
    main()
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/launch.py", line 44, in main
    start()
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/launch_utils.py", line 465, in start
    import webui
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/webui.py", line 13, in <module>
    initialize.imports()
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/initialize.py", line 39, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/hypernetworks/hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/textual_inversion/dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/modules/sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/repositories/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/repositories/k-diffusion/k_diffusion/evaluation.py", line 6, in <module>
    import clip
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/clip/clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (/ai/StabilityMatrix/Packages/Stable Diffusion WebUI/venv/lib/python3.10/site-packages/pkg_resources/__init__.py)

**Comment by mohnjiles** [comment]
Sorry about that, seems one of its' dependencies updated recently & caused this issue. While we wait on a fix from the upstream dependencies, you can downgrade the `setuptools` package to version `69.5.1` via the Python Packages menu (in the 3-dots menu on the Packages tab).

**Comment by mohnjiles** [comment]
This was fixed with v1.9.4 of Stable Diffusion WebUI - https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15882 - please try updating and re-open this issue if it still occurs. Thanks!
