### ISSUE TITLE
stable diffusion launch error 

### ISSUE THREAD

**Issue by 37OMKAR** [LykosAI/StabilityMatrix#652]
cant launch stable diffusion, 

have updated, 

have stable version of stability matrix, 

cant restart system, 

have NVDIA grafic card 2060 12 gb 

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.9.3
Commit hash: 1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0
Launching Web UI with arguments: --medvram-sdxl --xformers --api --autolaunch --skip-torch-cuda-test --skip-python-version-check --skip-install --gradio-allowed-path F:\StabilityMatrix-win-x64\Data\Images
Traceback (most recent call last):
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\launch.py", line 48, in <module>
    main()
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\launch.py", line 44, in main
    start()
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\launch_utils.py", line 465, in start
    import webui
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\webui.py", line 13, in <module>
    initialize.imports()
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\initialize.py", line 39, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\processing.py", line 18, in <module>
    import modules.sd_hijack
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\hypernetworks\hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\textual_inversion\dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\k-diffusion\k_diffusion\__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\repositories\k-diffusion\k_diffusion\evaluation.py", line 6, in <module>
    import clip
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\clip\__init__.py", line 1, in <module>
    from .clip import *
  File "F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\clip\clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (F:\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\pkg_resources\__init__.py)

**Comment by mohnjiles** [comment]
This was fixed with v1.9.4 of Stable Diffusion WebUI - https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15882 - please try updating and re-open this issue if it still occurs. Thanks!
