### ISSUE TITLE
[Feature Request] Search bar for installed Python Packages

### ISSUE THREAD

**Issue by bobcate** [LykosAI/StabilityMatrix#666]
Title.
![image](https://github.com/LykosAI/StabilityMatrix/assets/34423403/d354f9e5-f096-445a-ae8d-1fb3b07dd0b2)

**Comment by mohnjiles** [comment]
This was added in [v2.11.0](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.11.0)! Thank you for the suggestion!

**Comment by bobcate** [comment]
Nice! Thank you. But there seems to be a problem.
Sometimes, typing a little too fast in the search bar, causes the program to crash with the following log:
## Exception
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
### Sentry ID
```
319363d5edd64c4ea8f782574f712e5c
```
### Stack Trace
```
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Avalonia.Controls.ItemsSourceView`1.GetAt(Int32 index)
   at Avalonia.Controls.Selection.SelectedItems`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Avalonia.Controls.Selection.InternalSelectionModel.OnSelectionChanged(Object sender, SelectionModelSelectionChangedEventArgs e)
   at Avalonia.Controls.Selection.SelectionModel`1.CommitOperation(Operation operation, Boolean raisePropertyChanged)
   at Avalonia.Controls.Selection.SelectionNodeBase`1.<set_Source>g__OnPostChanged|5_2(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Controls.Utils.CollectionChangedEventManager.Entry.<Avalonia.Utilities.IWeakEventSubscriber<System.Collections.Specialized.NotifyCollectionChangedEventArgs>.OnEvent>g__Notify|6_0(INotifyCollectionChanged incc, NotifyCollectionChangedEventArgs args, WeakReference`1[] listeners)
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```
