### ISSUE TITLE
[v2.10.3] Package Modification Failed - git -  Filename too long

### ISSUE THREAD

**Issue by KMaheshBhat** [LykosAI/StabilityMatrix#672]
I am using the portable version v2.10.3 and while using the Prompt Expansion feature, it attempted to install additional ComfyUI packages but failed with a git error of 'Filenames too long'.

Below is log as captured under 'More Details':

```
Cloning https://github.com/LykosAI/ComfyUI-Inference-Core-Nodes
Error: StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'ComfyUI-Inference-Core-Nodes'...
error: unable to create file src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/depth_anything/torchhub/facebookresearch_dinov2_main/CODE_OF_CONDUCT.md: Filename too long
fatal: cannot create directory at 'src/inference_core_nodes/controlnet_preprocessors/src/controlnet_aux/depth_anything/torchhub/facebookresearch_dinov2_main/dinov2': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
   at StabilityMatrix.Core.Helper.IPrerequisiteHelper.CloneGitRepository(String rootDir, String repositoryUrl, GitVersion version)
   at StabilityMatrix.Core.Models.Packages.Extensions.GitPackageExtensionManager.InstallExtensionAsync(PackageExtension extension, InstalledPackage installedPackage, PackageExtensionVersion version, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.InstallExtensionAsync(PackageExtension extension, InstalledPackage installedPackage, PackageExtensionVersion version, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps)
```

I did attempt to run a `git config --system core.longpaths true` but that (obviously) would note work because I think StableMatrix uses the `Data\PortableGit` (I assume).

Any way to configure long filenames under Windows?

**Comment by KMaheshBhat** [comment]
Ok - I have fixed it for myself by adding `	longpaths = true` under `[core]` section of `.../Data/PortableGit/etc/gitconfig`.

**Comment by arrichman227** [comment]
> Ok - я исправил это для себя, добавив ` longpaths = true` в `[core]` раздел `.../Data/PortableGit/etc/gitconfig`.

how you open it?
