### ISSUE TITLE
StabilityMatrix 2.11.0 - InvokeAI won't install

### ISSUE THREAD

**Issue by coreykinard** [LykosAI/StabilityMatrix#685]
I have been unable to install InvokeAI via StabilityMatrix, however other packages install properly. Each time the install pulls down the git repo to the Packages/InvokeAI folder, but never progresses to the installation phase.

System Info: Windows 11

Some additional details: 
- Add Package > InvokeAI > InvokeAI 4.2.4
- Show Details:  Unpacking Resources
- Download: 100% Unpacking Resources
- Packages/InvokeAI: 407mb

Log file:
`2024-06-14 09:24:45.6764|DEBUG|StabilityMatrix.Core.Services.TrackedDownloadService|Indexing in-progress downloads at ...
2024-06-14 09:24:45.7267|INFO|StabilityMatrix.Core.Services.ModelIndexService|Loading models from database...
2024-06-14 09:24:45.7936|DEBUG|StabilityMatrix.Avalonia.Services.InferenceClientManager|Model index changed, reloading shared properties for Inference
2024-06-14 09:24:45.8552|INFO|StabilityMatrix.Core.Services.ModelIndexService|Loaded 23 models from database in 128.05ms
2024-06-14 09:24:45.8552|INFO|StabilityMatrix.Core.Services.ModelIndexService|Refreshing model index...
2024-06-14 09:24:46.3173|INFO|StabilityMatrix.Core.Services.ModelIndexService|Model index refreshed with 23 entries, took 60.18ms (401.19ms db)
2024-06-14 09:24:46.3173|DEBUG|StabilityMatrix.Avalonia.Services.InferenceClientManager|Model index changed, reloading shared properties for Inference
2024-06-14 09:24:46.3445|INFO|StabilityMatrix.Avalonia.ViewModels.MainWindowViewModel|App started (1.55s)
2024-06-14 09:25:04.3328|DEBUG|StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper|Python already installed at "S:\StabilityMatrix\Assets\Python310\python310.dll"
2024-06-14 09:25:04.3328|DEBUG|StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper|Git already installed at "S:\StabilityMatrix\PortableGit\bin\git.exe"
2024-06-14 09:25:04.3328|DEBUG|StabilityMatrix.Core.Processes.ProcessRunner|Starting process 'S:\StabilityMatrix\PortableGit\bin\git.exe' with arguments 'clone --branch v4.2.3 https://github.com/invoke-ai/InvokeAI S:\StabilityMatrix\Packages\InvokeAI'
2024-06-14 09:25:04.3408|DEBUG|StabilityMatrix.Core.Helper.ProcessTracker|Creating Job Object "SM_ProcessTracker_35736"
2024-06-14 09:25:04.3408|DEBUG|StabilityMatrix.Core.Helper.ProcessTracker|Adding Process "git" [31688] to Job Object "SM_ProcessTracker_35736"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnApplicationLifetimeExit: {"ApplicationExitCode":0}
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Preparing to Dispose 7 Services
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Disposing "InstalledWorkflowsViewModel"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Disposing "InferenceClientManager"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Disposing "NotificationService"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Disposing "RunningPackageService"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Disposing "TrackedDownloadService"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Disposing "DiscordRichPresenceService"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Disposing "LiteDbContext"
2024-06-14 09:28:03.4812|DEBUG|StabilityMatrix.Avalonia.App|OnExit: Finished`

**Comment by nyukers** [comment]
Stability Matrix v2.13.3
Unpacking resources
Unpacking resources
Could not install InvokeAI (StabilityMatrix.Core.Exceptions.ProcessException: Process git exited with code 128. {StdOut = , StdErr = Cloning into 'D:\Matrix\Data\Packages\InvokeAI'...
fatal: unable to access 'https://github.com/invoke-ai/InvokeAI/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
}
   at StabilityMatrix.Core.Processes.ProcessResult.EnsureSuccessExitCode()
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(ProcessArgs args, String workingDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.DownloadPackage(String installLocation, DownloadPackageOptions options, IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps))

**Comment by rowild** [comment]
Any chance to fix this?

**Comment by unphased** [comment]
invokeai installs fine. it launches "fine" too but does not work. the log just kinda trails off after it says it should be ready while/after it "installs" a bunch of models that i have linked in to make available.

Has anyone gotten invoke to run under stability matrix?
