### ISSUE TITLE
Outside of ComfyUI all packages failing to install

### ISSUE THREAD

**Issue by BrechtCorbeel** [LykosAI/StabilityMatrix#688]
Now this is recent, but anything outside of my comfyui which is already installed for a while is failing to install, throwing errors every step of the way. these are just a couple along the way the last one is because I already tried and it failed so the app is there as a folder, which I deleted and continue to get one failure after the other.

![image](https://github.com/LykosAI/StabilityMatrix/assets/68238477/90220c4e-8fb8-4433-bd30-7a56e78590db)

![image](https://github.com/LykosAI/StabilityMatrix/assets/68238477/bcdff005-9e9f-417c-b9bd-edd0a781aba2)

## Exception
IOException: Failed to delete directory W:\smatrix\Data\Packages\Stable Diffusion WebUI\venv\Lib\site-packages
### Sentry ID
```
ca409cf6352c4655b501ee1073c4b553
```
### Stack Trace
```
   at StabilityMatrix.Core.Extensions.DirectoryPathExtensions.DeleteVerbose(DirectoryPath directory, ILogger logger, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Extensions.DirectoryPathExtensions.DeleteVerbose(DirectoryPath directory, ILogger logger, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Extensions.DirectoryPathExtensions.DeleteVerbose(DirectoryPath directory, ILogger logger, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Extensions.DirectoryPathExtensions.DeleteVerbose(DirectoryPath directory, ILogger logger, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at StabilityMatrix.Core.Extensions.DirectoryPathExtensions.<>c__DisplayClass0_0.<<DeleteVerboseAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at StabilityMatrix.Avalonia.ViewModels.PackageManager.PackageInstallDetailViewModel.Install()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```
## Inner Exception
IOException: The directory is not empty. : 'W:\smatrix\Data\Packages\Stable Diffusion WebUI\venv\Lib\site-packages'
### Stack Trace
```
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at StabilityMatrix.Core.Extensions.DirectoryPathExtensions.DeleteVerbose(DirectoryPath directory, ILogger logger, CancellationToken cancellationToken)
```

**Comment by ionite34** [comment]
Hm, I think a package is running or still open in your install directory. Can you try with a different name or restart your pc first to ensure nothing else is running?

**Comment by BrechtCorbeel** [comment]
> Hm, I think a package is running or still open in your install directory. Can you try with a different name or restart your pc first to ensure nothing else is running?

I did that a bunch already, it's still happening literally nothing outside of comfyui is installing.
I have my folder over a networked drive, I think it might be portable install, it creates all the files and folders but I end up with this at max:

![image](https://github.com/LykosAI/StabilityMatrix/assets/68238477/1274326b-8e83-4a58-be92-e35cd80a84a3)

**Comment by BrechtCorbeel** [comment]
I just installed on windows 11 on a different computer, both are installed and using a repository on an external drive, on this new pc, new install exact same issue.
