### ISSUE TITLE
 Cant launch Fooocus 2.5.0 ModuleNotFoundError: No module named 'groundingdino.util'

### ISSUE THREAD

**Issue by yundin2000** [LykosAI/StabilityMatrix#767]
[System ARGV] ['C:\\StableDIFFUSION\\Packages\\Fooocus\\launch.py']
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.5.0
[Cleanup] Attempting to delete content of temp dir C:\Users\yundi\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 12288 MB, total RAM 131019 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "C:\StableDIFFUSION\Packages\Fooocus\launch.py", line 147, in <module>
    from webui import *
  File "C:\StableDIFFUSION\Packages\Fooocus\webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "C:\StableDIFFUSION\Packages\Fooocus\modules\async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "C:\StableDIFFUSION\Packages\Fooocus\extras\inpaint_mask.py", line 6, in <module>
    from extras.GroundingDINO.util.inference import default_groundingdino
  File "C:\StableDIFFUSION\Packages\Fooocus\extras\GroundingDINO\util\inference.py", line 11, in <module>
    from groundingdino.util.inference import Model
ModuleNotFoundError: No module named 'groundingdino.util'

**Comment by orangpelupa** [comment]
anyone found a fix? maybe related to this? https://github.com/lllyasviel/Fooocus/discussions/3289
