### ISSUE TITLE
IOException when installing AUTOMATIC first time

### ISSUE THREAD

**Issue by plovlover** [LykosAI/StabilityMatrix#77]
I tried Portable install. Error is happening on this moment of install:

![image](https://github.com/LykosAI/StabilityMatrix/assets/107027997/db2775e9-df24-42d5-b900-560c08be8643)

Unable to create junction point G:\StabilityMatrix\Data\Packages\stable-diffusion-webui\models/Stable-diffusion -> G:\StabilityMatrix\Data\Models\StableDiffusion

Workaround: Move whole folder to another drive. In my case moving whole folder from G: to D: solved an issue.

Callstack:
```
at StabilityMatrix.Core.ReparsePoints.Junction.ThrowLastWin32Error(String message)
   at StabilityMatrix.Core.ReparsePoints.Junction.Create(String junctionPoint, String targetDir, Boolean overwrite)
   at StabilityMatrix.Core.Helper.SharedFolders.CreateLinkOrJunction(String junctionDir, String targetDir, Boolean overwrite)
   at StabilityMatrix.Core.Helper.SharedFolders.SetupLinks(Dictionary`2 definitions, DirectoryPath modelsDirectory, DirectoryPath installDirectory)
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.SetupModelFolders(DirectoryPath installDirectory)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.DoInstall()
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.Install()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```

Inner exception:
`System.Runtime.InteropServices.COMException (0x80070001): Incorrect function. (0x80070001)`

**Comment by ionite34** [comment]
Hm, do you know if your G drive was exFAT/FAT? Since Junctions / Symbolic links aren't supported on those formats. Should  probably do a check before installing so you know ahead of time though.

**Comment by plovlover** [comment]
G: was exFAT while D: was NTFS, correct! It would be great if before installing program checked that and gave a warning. I didn't knew about that really. Thanks a lot!

**Comment by mohnjiles** [comment]
We added a warning to the installer in [v2.3.2](https://github.com/LykosAI/StabilityMatrix/releases/tag/v2.3.2), thank you for the feedback! We're also working on compatibility for these drives in the future, just not sure on the timeline.
