### ISSUE TITLE
My Fooocus package suddenly can't update

### ISSUE THREAD

**Issue by kimnamwook1** [LykosAI/StabilityMatrix#791]
1. Unicode ERROR ? 
It happened when I update Fooocus in "main" branch, update target commit number "c2dc17e"

I uninstall Fooocus package and try to reinsntall, but they print same error with below. (all commits)

I also change my region and language to US but also print same error (I live in South Korea) 

>"UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 2876:"

the main error text is like below:

```
Collecting groundingdino-py==0.4.0
  Using cached groundingdino-py-0.4.0.tar.gz (82 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\79223\AppData\Local\Temp\pip-install-73kys9xn\groundingdino-py_858751cb98c24564a9ee53490f5aa563\setup.py", line 41, in <module>
          readme = readme_file.read()
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 2876: illegal multibyte sequence
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

and Final Error Message is below:
```
Could not install Fooocus (StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121\r\nCollecting torch==2.1.0\r\n  Using cached https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)\r\nCollecting torchvision==0.16.0\r\n  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-win_amd64.whl (5.8 MB)\r\nCollecting torchsde==0.2.6\r\n  Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)\r\nCollecting einops==0.8.0\r\n  Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)\r\nCollecting transformers==4.42.4\r\n  Using cached transformers-4.42.4-py3-none-any.whl.metadata (43 kB)\r\nCollecting safetensors==0.4.3\r\n  Using cached safetensors-0.4.3-cp310-none-win_amd64.whl.metadata (3.9 kB)\r\nCollecting accelerate==0.32.1\r\n  Using cached accelerate-0.32.1-py3-none-any.whl.metadata (18 kB)\r\nCollecting pyyaml==6.0.1\r\n  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)\r\nCollecting pillow==10.4.0\r\n  Using cached pillow-10.4.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)\r\nCollecting scipy==1.14.0\r\n  Using cached scipy-1.14.0-cp310-cp310-win_amd64.whl.metadata (60 kB)\r\nCollecting tqdm==4.66.4\r\n  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)\r\nCollecting psutil==6.0.0\r\n  Using cached psutil-6.0.0-cp37-abi3-win_amd64.whl.metadata (22 kB)\r\nCollecting pytorch_lightning==2.3.3\r\n  Using cached pytorch_lightning-2.3.3-py3-none-any.whl.metadata (21 kB)\r\nCollecting omegaconf==2.3.0\r\n  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)\r\nCollecting gradio==3.41.2\r\n  Using cached gradio-3.41.2-py3-none-any.whl.metadata (17 kB)\r\nCollecting pygit2==1.15.1\r\n  Using cached pygit2-1.15.1-cp310-cp310-win_amd64.whl.metadata (3.4 kB)\r\nCollecting opencv-contrib-python-headless==4.10.0.84\r\n  Using cached opencv_contrib_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)\r\nCollecting httpx==0.27.0\r\n  Using cached httpx-0.27.0-py3-none-any.whl.metadata (7.2 kB)\r\nCollecting onnxruntime==1.18.1\r\n  Using cached onnxruntime-1.18.1-cp310-cp310-win_amd64.whl.metadata (4.5 kB)\r\nCollecting timm==1.0.7\r\n  Using cached timm-1.0.7-py3-none-any.whl.metadata (47 kB)\r\nCollecting numpy==1.26.4\r\n  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)\r\nCollecting tokenizers==0.19.1\r\n  Using cached tokenizers-0.19.1-cp310-none-win_amd64.whl.metadata (6.9 kB)\r\nCollecting packaging==24.1\r\n  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)\r\nCollecting rembg==2.0.57\r\n  Using cached rembg-2.0.57-py3-none-any.whl.metadata (16 kB)\r\nCollecting groundingdino-py==0.4.0\r\n  Using cached groundingdino-py-0.4.0.tar.gz (82 kB)\r\n  Preparing metadata (setup.py): started\r\n  Preparing metadata (setup.py): finished with status 'error'\r\n  error: subprocess-exited-with-error\r\n  \r\n  \u00d7 python setup.py egg_info did not run successfully.\r\n  \u2502 exit code: 1\r\n  \u2570\u2500> [6 lines of output]\r\n      Traceback (most recent call last):\r\n        File "<string>", line 2, in <module>\r\n        File "<pip-setuptools-caller>", line 34, in <module>\r\n        File "C:\Users\79223\AppData\Local\Temp\pip-install-73kys9xn\groundingdino-py_858751cb98c24564a9ee53490f5aa563\setup.py", line 41, in <module>\r\n          readme = readme_file.read()\r\n      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 2876: illegal multibyte sequence\r\n      [end of output]\r\n  \r\n  note: This error originates from a subprocess, and is likely not a problem with pip.\r\nerror: metadata-generation-failed\r\n\r\n\u00d7 Encountered error while generating package metadata.\r\n\u2570\u2500> See above for output.\r\n\r\nnote: This is an issue with the package mentioned above, not pip.\r\nhint: See above for details.\r\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.Fooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.Fooocus.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))
```
Config picture is like below: 
![image](https://github.com/user-attachments/assets/d902ba08-c990-49b8-b649-dc20aafe558b)

Please help me to solve this problem. 

2. How to install package fro m github manually? 
I want to install Fooocus version 2.5 but I cant clone package directly to "StabilityMatrix -> Package" Folder

**Comment by AdnaneSaber** [comment]
@kimnamwook1  I believe this is occuring because of the korean language of the OS you're running on, I also live in South Korea, but if I run it on my personal device works but not on a PC bang.
