### ISSUE TITLE
Installing Forge WEBUI or Automatic1111 gives error (SOLVED)

### ISSUE THREAD

**Issue by Diamondofdevil** [LykosAI/StabilityMatrix#803]
Hi,
I have spent last 4 hours trying to solve this problem,
-i installed COMFYUI without any issues but,

-installing forgeUI or Automatic1111 results in this error: 

I never had any issues before. 

LOG:

emp\pip-install-vns00wx4\matplotlib_f7ac5944aa99411da34b1f340dc6b6a1\.mesonpy-r7vr7q5w\r\n      Build type: native build\r\n      Program python3 found: YES\r\n      Project name: matplotlib\r\n      Project version: 3.9.1\r\n      Activating VS 16.11.36\r\n      C compiler for the host machine: cl (msvc 19.29.30154 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64")\r\n      C linker for the host machine: link link 14.29.30154.0\r\n      C++ compiler for the host machine: cl (msvc 19.29.30154 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64")\r\n      C++ linker for the host machine: link link 14.29.30154.0\r\n      Host machine cpu family: x86_64\r\n      Host machine cpu: x86_64\r\n      Program python found: YES (C:\Users\Johny\AppData\Roaming\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\Scripts\python.exe)\r\n      Could not find Python3 library 'C:\\Users\\Johny\\AppData\\Roaming\\StabilityMatrix\\Packages\\Stable Diffusion WebUI\\venv\\Scripts\\libs\\python310.lib'\r\n      Run-time dependency python found: NO (tried sysconfig)\r\n      \r\n      ..\meson.build:37:14: ERROR: Python dependency not found\r\n      \r\n      A full log can be found at C:\Users\Johny\AppData\Local\Temp\pip-install-vns00wx4\matplotlib_f7ac5944aa99411da34b1f340dc6b6a1\.mesonpy-r7vr7q5w\meson-logs\meson-log.txt\r\n      [end of output]\r\n  \r\n  note: This error originates from a subprocess, and is likely not a problem with pip.\r\nerror: metadata-generation-failed\r\n\r\n\u00d7 Encountered error while generating package metadata.\r\n\u2570\u2500> See above for output.\r\n\r\nnote: This is an issue with the package mentioned above, not pip.\r\nhint: See above for details.\r\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.Packages.A3WebUI.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps))

**Comment by AlexWolfe95** [comment]
Exact same problem here.

**Comment by Diamondofdevil** [comment]
Oh man after hours of frustration and smashing the poor desk , ive found a SOLUTION 
This is how i fixed it :

Removed python completely including cache folders : 
-installed python-3.10.6-amd64.exe + added to path via 
![image](https://github.com/user-attachments/assets/9dc296f9-e4fa-4df0-aec0-9f2ea2982c8e)

-installed matplotlib manually through CMD 
python -m pip install -U pip
python -m pip install -U matplotlib

restart Stability matrix install your favorite packages and enjoy!

**Comment by mohnjiles** [comment]
An easier solution (while waiting on [the underlying issues](https://github.com/matplotlib/matplotlib/issues/28551) to be fixed) may be to go to `Settings > Environment Variables > Edit` and then add `PIP_ONLY_BINARY` with value `matplotlib`, then Save & retry the install.

![image](https://github.com/user-attachments/assets/29ff91d6-daa5-4e02-86b9-04bd50ff6fc6)

**Comment by tacaswell** [comment]
The 3.9.1 wheels on windows would, depending on import order, cause segfaults, see https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266699619.

We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel.  We have now yanked the whole 3.9.1 release to fix these problems and will get 3.9.2 out as quick as we can.

To prevent this sort of thing in the future (trying to build something from source when you are not prepared to do so) I suggest using `matplotlib --only-binary "matplotlib" ` in your requirements file (which may be a good practice for all wheels that have extensions).

Sorry for the trouble.

**Comment by mohnjiles** [comment]
> The 3.9.1 wheels on windows would, depending on import order, cause segfaults, see [matplotlib/matplotlib#28551 (comment)](https://github.com/matplotlib/matplotlib/issues/28551#issuecomment-2266699619).
> 
> We deleted the bad wheels to avoid segfaults (which seemed like a good idea) but failed to anticipate that this would cause downstream projects to start trying to build mpl from source instead of pulling the 3.9.0 wheel. We have now yanked the whole 3.9.1 release to fix these problems and will get 3.9.2 out as quick as we can.
> 
> To prevent this sort of thing in the future (trying to build something from source when you are not prepared to do so) I suggest using `matplotlib --only-binary "matplotlib" ` in your requirements file (which may be a good practice for all wheels that have extensions).
> 
> Sorry for the trouble.

No worries, thanks for the update!

**Comment by twopiearr** [comment]
Any idea how to solve this on a Mac? (M2, Sonoma 14.5)

Tried using the environment above and it went further, but still errored out. It IS going into a /Data/ directory on an external volume of that matters; it seems to install correctly on the startup volume, but for various reasons that's not desirable. Error:

```
Building wheels for collected packages: basicsr
  Building wheel for basicsr (setup.py): started
  Building wheel for basicsr (setup.py): finished with status 'error'
  error: subprocess-exited-with-error  Running setup.py clean for basicsr

  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
        warnings.warn(
      /Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4h/7dw6_n2n6v94y51smzfs8n780000gn/T/pip-install-_nn8f3pr/basicsr_cd2ea32cf4d140cb95b40f6a6e88dc19/setup.py", line 147, in <module>
          setup(
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/dist.py", line 641, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 889, in resolve
          dist = self._resolve_dist(
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 925, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1256, in best_match
          return self.obtain(req, installer)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1292, in obtain
          return installer(requirement) if installer else None
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 122, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 130, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Volumes/AI/Data/Packages/Stable Diffusion WebUI Forge/venv/lib/python3.10/site-packages/setuptools/wheel.py", line 175, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/4h/7dw6_n2n6v94y51smzfs8n780000gn/T/pip-install-_nn8f3pr/basicsr_cd2ea32cf4d140cb95b40f6a6e88dc19/.eggs/torch-2.4.0-py3.10-macosx-11.0-arm64.egg/torch-2.4.0.dist-info' -> '/private/var/folders/4h/7dw6_n2n6v94y51smzfs8n780000gn/T/pip-install-_nn8f3pr/basicsr_cd2ea32cf4d140cb95b40f6a6e88dc19/.eggs/torch-2.4.0-py3.10-macosx-11.0-arm64.egg/EGG-INFO'
      [end of output]
```

**Comment by raisindetre** [comment]
Also Mac (M2, Sonoma 14.5) and get the "Building wheel for basicsr (setup.py): finished with status 'error'" but am installing onto the startup disk. @twopiearr  did you find a fix?

**Comment by twopiearr** [comment]
> @twopiearr did you find a fix?

Nope. Works when I install to startup, does not work when I install to data.

I did investigate the URL that was reported as "not an empty directory" and was sort of surprised to discover that the directory doesn't exist. The directory reported in the error as "not empty" is:

/private/var/folders/4h/7dw6_n2n6v94y51smzfs8n780000gn/T/pip-install-_nn8f3pr/basicsr_cd2ea32cf4d140cb95b40f6a6e88dc19/.eggs/torch-2.4.0-py3.10-macosx-11.0-arm64.egg/torch-2.4.0.dist-info' -> '/private/var/folders/4h/7dw6_n2n6v94y51smzfs8n780000gn/T/pip-install-_nn8f3pr/basicsr_cd2ea32cf4d140cb95b40f6a6e88dc19/.eggs/torch-2.4.0-py3.10-macosx-11.0-arm64.egg/EGG-INFO'

However, on my system, it only seemed to go as deep as /private/var/folders/4h/7dw6_n2n6v94y51smzfs8n780000gn/T/ - everything from the pip-install directory down is missing.

**Comment by twopiearr** [comment]
Update - 2.11.8 now seems to install correctly.
