### ISSUE TITLE
Package Modification Failed

### ISSUE THREAD

**Issue by duoadmin** [LykosAI/StabilityMatrix#806]
Since yesterday Package-Installation fails on Mac. 
Doesn't matter witch Package. Always fails with following Message:

Unpacking resources
Unpacking resources
Download Complete
Traceback (most recent call last):
  File "/Applications/Data/Assets/Python310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Data/Assets/Python310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 11, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 10, in <module>
    from pip._internal.cli import cmdoptions
  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 29, in <module>
    from pip._internal.models.target_python import TargetPython
ModuleNotFoundError: No module named 'pip._internal.models.target_python'
Error: StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'Traceback (most recent call last):\n  File "/Applications/Data/Assets/Python310/lib/python3.10/runpy.py", line 196, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/Applications/Data/Assets/Python310/lib/python3.10/runpy.py", line 86, in _run_code\n    exec(code, run_globals)\n  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/__main__.py", line 22, in <module>\n    from pip._internal.cli.main import main as _main\n  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 11, in <module>\n    from pip._internal.cli.autocompletion import autocomplete\n  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>\n    from pip._internal.cli.main_parser import create_main_parser\n  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 10, in <module>\n    from pip._internal.cli import cmdoptions\n  File "/Applications/Data/Packages/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 29, in <module>\n    from pip._internal.models.target_python import TargetPython\nModuleNotFoundError: No module named 'pip._internal.models.target_python'\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Python/PyVenvRunner.cs:line 241
   at StabilityMatrix.Core.Models.Packages.SDWebForge.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/SDWebForge.cs:line 160
   at StabilityMatrix.Core.Models.Packages.SDWebForge.InstallPackage(String installLocation, TorchVersion torchVersion, SharedFolderMethod selectedSharedFolderMethod, DownloadPackageVersionOptions versionOptions, IProgress`1 progress, Action`1 onConsoleOutput) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/SDWebForge.cs:line 192
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/PackageModification/InstallPackageStep.cs:line 22
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/PackageModification/PackageModificationRunner.cs:line 35

**Comment by duoadmin** [comment]
Found a solution.
target_python.py is missing in .../venv/lib/python3.10/site-packages/pip/_internal/models
Downloaded it from [here](https://github.com/pypa/pip/blob/main/src/pip/_internal/models/target_python.py) put it in the mentioned folder and everything works fine.

**Comment by al-ship** [comment]
I have the same problem on arch linux. Where is dir .../venv/lib/python3.10/site-packages/pip/_internal/models?
I have Data/Assets/Python310/lib/python3.10/site-packages/pip/_internal/models and it contains target_python.py

**Comment by duoadmin** [comment]
It's inside the Package (...Data/Package/"WhateverPackageYoureUsing"/venv).
Try to add a new Package. It will most likely fail. Close Stability Matrix and reopen it. Now the Package should show with a Import-Button.
Now put the missing file inside the folder and hit the Import-Button. When you launch the Package it will install all dependencies.

**Comment by al-ship** [comment]
When I install stable-diffusion-webui i got this error and dir is emty

**Comment by cammelspit** [comment]
This solution unfortunately doesn't work. I am on Arch Linux and wanted to have a clean install, swapped drives, and I simply cannot install anything. Is there any indication as to why this is happening?
