### ISSUE TITLE
Error Running ComfyUI

### ISSUE THREAD

**Issue by carmaz54** [LykosAI/StabilityMatrix#851]
ComfyUI was working fine, now it won't start and throws the following error.

OSError: [WinError 126] The specified module could not be found. Error loading "D:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

Uninstalled and reinstalled ComfyUI but didn't resolve the issue.

**Comment by Jojo-xqt** [comment]
Try right-clicking on the D:\StabilityMatrix\Data\Packages\ComfyUI\venv\ folder and selecting "Take Ownership" with administrator privileges.

**Comment by carmaz54** [comment]
Fixed the error on one of my computers but not my laptop is getting this error when running comfyui.

ModuleNotFoundError: No module named 'torchsde'

**Comment by carmaz54** [comment]
Here's what I get launching ComfyUI:

pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\main.py", line 86, in <module>
    import execution
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 22, in <module>
    import comfy.samplers
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\comfy\samplers.py", line 1, in <module>
    from .k_diffusion import sampling as k_diffusion_sampling
  File "D:\StabilityMatrix\Data\Packages\ComfyUI\comfy\k_diffusion\sampling.py", line 6, in <module>
    import torchsde
ModuleNotFoundError: No module named 'torchsde'
