### ISSUE TITLE
IOException can´t launch ComfyUI nor Fooocus

### ISSUE THREAD

**Issue by Trollypoopy** [LykosAI/StabilityMatrix#864]
Hey I am new to Stability Matrix and also to SD and was trying to generate images locally. But after installing Comfy UI and Fooocus trough the add package this error appears when I try to launch them. 
ComfyUI: 
```
## Exception
```IOException: Unable to create junction point E:\Stability Matrix\Data\Packages\ComfyUI\output -> E:\Stability Matrix\Data\Images\Text2Img```
```COMException: Função incorreta. (0x80070001)```
### Sentry ID
[`8796be15`](https://stability-matrix.sentry.io/issues/?query=id%3A8796be157fd2400185dd1cef554d3367&referrer=sm-app-ex&statsPeriod=90d)
### Stack Trace
```   at StabilityMatrix.Core.ReparsePoints.Junction.ThrowLastWin32Error(String message)
   at StabilityMatrix.Core.ReparsePoints.Junction.Create(String junctionPoint, String targetDir, Boolean overwrite)
   at StabilityMatrix.Core.Helper.SharedFolders.CreateOrUpdateLink(DirectoryPath sourceDir, DirectoryPath destinationDir, Boolean overwrite, Boolean recursiveDelete)
   at StabilityMatrix.Core.Helper.SharedFolders.UpdateLinksForPackage[T](Dictionary`2 sharedFolders, DirectoryPath modelsDirectory, DirectoryPath installDirectory, Boolean recursiveDelete)
   at StabilityMatrix.Avalonia.Services.RunningPackageService.StartPackage(InstalledPackage installedPackage, String command)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.InferenceConnectionHelpViewModel.LaunchSelectedPackage()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)
```
Fooocus: Says something similar to ComfyUI error. 

Thank you in advance for any help, also sorry if I may have done some mistakes.

**Comment by mohnjiles** [comment]
Hi, unfortunately symlinks/junctions do not appear to be supported on the filesystem of your E: drive (may be FAT32/exFAT). You can try changing the "Model Sharing" option to "Config" instead of "Symlink" to avoid this, or you can move your Stability Matrix install to a different drive that does support symlinks/junctions. Sorry about that!
