### ISSUE TITLE
Git.exe failed

### ISSUE THREAD

**Issue by ElHeoff** [LykosAI/StabilityMatrix#88]
![Screenshot (7629)](https://github.com/LykosAI/StabilityMatrix/assets/143294295/04998931-b065-4935-a97e-9bf68d13219a)
I have git no clue what be causing this
at StabilityMatrix.Core.Processes.ProcessRunner.ValidateExitConditionAsync(Process process, Int32 expectedExitCode, String stdout, String stderr)
   at StabilityMatrix.Core.Processes.ProcessRunner.WaitForExitConditionAsync(Process process, Int32 expectedExitCode, CancellationToken cancelToken)
   at StabilityMatrix.Avalonia.Helpers.WindowsPrerequisiteHelper.RunGit(String workingDirectory, String[] args)
   at StabilityMatrix.Core.Models.Packages.VladAutomatic.DownloadPackage(String version, Boolean isCommitHash, String branch, IProgress`1 progress)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.DownloadPackage(String version)
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.DoInstall()
   at StabilityMatrix.Avalonia.ViewModels.Dialogs.OneClickInstallViewModel.Install()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)

**Comment by ionite34** [comment]
Closing as stale or unable to reproduce, please try latest release with better error reports in these subprocesses and create a new issue with more details if needed: https://github.com/LykosAI/StabilityMatrix/releases/latest
