### ISSUE TITLE
Invoke Update Impossible

### ISSUE THREAD

**Issue by osmoz01** [LykosAI/StabilityMatrix#916]
### Package

InvokeAI

### When did the issue occur?

Updating the Package

### What GPU / hardware type are you using?

Macbook M3 Max 36Go - MacOs Sequoia 15.0

### What happened?

Hello,
Impossible to update Invoke v5 on mac.
I got the message "Install failed, could not update InvokeAI".

<img width="358" alt="Capture d’écran 2024-09-27 à 20 47 20" src="https://github.com/user-attachments/assets/b8921038-b120-4adb-a0c6-376207683e2c">

### Console output

 WARN  using --force I sure hope you know what you are doing
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +1389
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1389, reused 1386, downloaded 0, added 53
Progress: resolved 1389, reused 1386, downloaded 0, added 111
Progress: resolved 1389, reused 1386, downloaded 0, added 152
Progress: resolved 1389, reused 1386, downloaded 0, added 184
Progress: resolved 1389, reused 1386, downloaded 0, added 216
Progress: resolved 1389, reused 1386, downloaded 0, added 255
Progress: resolved 1389, reused 1386, downloaded 0, added 322
Progress: resolved 1389, reused 1386, downloaded 0, added 351
Progress: resolved 1389, reused 1386, downloaded 0, added 423
Progress: resolved 1389, reused 1386, downloaded 0, added 471
Progress: resolved 1389, reused 1386, downloaded 0, added 548
Progress: resolved 1389, reused 1386, downloaded 0, added 623
Progress: resolved 1389, reused 1386, downloaded 0, added 674
Progress: resolved 1389, reused 1386, downloaded 0, added 721
Progress: resolved 1389, reused 1386, downloaded 0, added 784
Progress: resolved 1389, reused 1386, downloaded 0, added 888
Progress: resolved 1389, reused 1386, downloaded 0, added 988
Progress: resolved 1389, reused 1386, downloaded 0, added 1060
Progress: resolved 1389, reused 1386, downloaded 0, added 1151
Progress: resolved 1389, reused 1386, downloaded 0, added 1235
Progress: resolved 1389, reused 1386, downloaded 0, added 1293
Progress: resolved 1389, reused 1386, downloaded 0, added 1324
Progress: resolved 1389, reused 1386, downloaded 0, added 1331
Progress: resolved 1389, reused 1386, downloaded 0, added 1353
Progress: resolved 1389, reused 1386, downloaded 0, added 1365
Progress: resolved 1389, reused 1386, downloaded 0, added 1381
Progress: resolved 1389, reused 1386, downloaded 0, added 1388
Progress: resolved 1389, reused 1386, downloaded 0, added 1389
Progress: resolved 1389, reused 1386, downloaded 0, added 1389, done

Done in 28.7s
vite v5.4.8 building for production...
transforming...
✓ 3110 modules transformed.
rendering chunks...
computing gzip size...
dist/index.html                                                0.68 kB │ gzip:   0.40 kB
dist/assets/worker-Dywf1EVc.js                                 1.01 kB
dist/assets/inter-vietnamese-wght-normal-CBcvBZtf.woff2       10.25 kB
dist/assets/inter-greek-ext-wght-normal-CGAr0uHJ.woff2        11.20 kB
dist/assets/inter-cyrillic-wght-normal-CMZtQduZ.woff2         18.74 kB
dist/assets/inter-greek-wght-normal-CaVNZxsx.woff2            19.07 kB
dist/assets/inter-cyrillic-ext-wght-normal-B2xhLi22.woff2     25.89 kB
dist/assets/inter-latin-wght-normal-C2S99t-D.woff2            48.44 kB
dist/assets/inter-latin-ext-wght-normal-CFHvXkgd.woff2        74.33 kB
dist/assets/commercial-license-bg-C_dHp7on.png               179.02 kB
dist/assets/App-DEu4J2pT.css                                   7.32 kB │ gzip:   1.60 kB
dist/assets/ThemeLocaleProvider-B2NxUfIp.css                  15.30 kB │ gzip:   3.11 kB
dist/assets/ThemeLocaleProvider-CxWPQAx2.js                    1.05 kB │ gzip:   0.40 kB
dist/assets/App-C2uiTKz4.js                                1,250.52 kB │ gzip: 360.67 kB
dist/assets/index-ByE8g2nn.js                              1,739.36 kB │ gzip: 554.64 kB

(!) Some chunks are larger than 1500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 14.18s
ERROR: You must give at least one requirement to install (see "pip help install")
Could not update InvokeAI (StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'ERROR: You must give at least one requirement to install (see "pip help install")\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Python/PyVenvRunner.cs:line 241
   at StabilityMatrix.Core.Models.Packages.InvokeAI.InstallPackage(String installLocation, InstalledPackage installedPackage, InstallPackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/InvokeAI.cs:line 219
   at StabilityMatrix.Core.Models.Packages.InvokeAI.InstallPackage(String installLocation, InstalledPackage installedPackage, InstallPackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/InvokeAI.cs:line 226
   at StabilityMatrix.Core.Models.Packages.BaseGitPackage.Update(String installLocation, InstalledPackage installedPackage, UpdatePackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/BaseGitPackage.cs:line 432
   at StabilityMatrix.Core.Models.PackageModification.UpdatePackageStep.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/PackageModification/UpdatePackageStep.cs:line 21
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/PackageModification/PackageModificationRunner.cs:line 35)

### Version

v2.12.0

### What Operating System are you using?

macOS

**Comment by 3Vmedia** [comment]
same for windows 11, 20.12.2024
v5.4.3 -> v5.5.0 or v5.50rc1
