### ISSUE TITLE
Error after computer crashes.

### ISSUE THREAD

**Issue by Qbaner** [LykosAI/StabilityMatrix#917]
### What happened?

StabilityMatrix was running and starting a package and suddenly the computer crashes.

## JsonException

**Details**
'fal□□' is an invalid JSON literal. Expected the literal 'false'. Path: $.HideEarlyAccessModels | LineNumber: 692 | BytePositionInLine: 30.

**Callstack**
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Stream utf8Json)
   at StabilityMatrix.Core.Services.SettingsManager.LoadSettings(CancellationToken cancellationToken)
   at StabilityMatrix.Core.Services.SettingsManager.TryFindLibrary(Boolean forceReload)
   at StabilityMatrix.Avalonia.App.ConfigureServiceProvider()
   at StabilityMatrix.Avalonia.App.OnFrameworkInitializationCompleted()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)

**Inner Exception**
System.Text.Json.JsonReaderException: 'fal□□' is an invalid JSON literal. Expected the literal 'false'. LineNumber: 692 | BytePositionInLine: 30.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ThrowInvalidLiteral(ReadOnlySpan`1 span)
   at System.Text.Json.Utf8JsonReader.CheckLiteral(ReadOnlySpan`1 span, ReadOnlySpan`1 literal)
   at System.Text.Json.Utf8JsonReader.ConsumeLiteral(ReadOnlySpan`1 literal, JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.ReadAheadPropertyValue(ReadStack& state, Utf8JsonReader& reader, JsonPropertyInfo jsonPropertyInfo)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

### Version

2.12.0

### What Operating System are you using?

Windows

**Comment by Qbaner** [comment]
I had to edit line 693 and 694 in settings.json.

>  693  "HideEarlyAccessModels": false
>  694 }

This solved the problem
