### ISSUE TITLE
is there problems with Gradio by any chance never had this happen before

### ISSUE THREAD

**Issue by LadyFlames** [LykosAI/StabilityMatrix#94]
Task exception was never retrieved
future: <Task finished name='hcxsvpdckmw_615' coro=<Queue.process_events() done, defined at D:\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "D:\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "asyncio\tasks.py", line 445, in wait_for
  File "D:\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "D:\StabilityMatrix\Packages\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006

**Comment by ionite34** [comment]
Should be resolved in newer package versions?
