### ISSUE TITLE
HIP error: no kernel image is available for execution on the device on ComfyUI with AMD GPU 

### ISSUE THREAD

**Issue by Freakyfox20** [LykosAI/StabilityMatrix#941]
### What happened?

**What Happened**
When I install ComfyUI and run Queue prompt, I get an HIP Error saying no kernel image is available for execution on the device.  It is a fresh install. No manager, no custom nodes. 

**What I expected to happen**
The image to generate. 

**GPU and Operating System**
AMD 7900XTX on EndeavourOS.  

### Steps to reproduce

1. Install ComfyUI
2. Launch ComfyUI
3. Click Queue Prompt

### Relevant logs

```shell
# ComfyUI Error Report
## Error Details
- **Node Type:** CLIPTextEncode
- **Exception Type:** RuntimeError
- **Exception Message:** HIP error: no kernel image is available for execution on the device
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

## Stack Trace

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/nodes.py", line 65, in encode
    output = clip.encode_from_tokens(tokens, return_pooled=True, return_dict=True)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd.py", line 125, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sdxl_clip.py", line 60, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd1_clip.py", line 41, in encode_token_weights
    o = self.encode(to_encode)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd1_clip.py", line 229, in encode
    return self(tokens)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd1_clip.py", line 201, in forward
    outputs = self.transformer(tokens, attention_mask_model, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/clip_model.py", line 136, in forward
    x = self.text_model(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/clip_model.py", line 100, in forward
    x = self.embeddings(input_tokens, dtype=dtype)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/clip_model.py", line 81, in forward
    return self.token_embedding(input_tokens, out_dtype=dtype) + comfy.ops.cast_to(self.position_embedding.weight, dtype=dtype, device=input_tokens.device)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/ops.py", line 211, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/ops.py", line 207, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)

  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

```
## System Information
- **ComfyUI Version:** v0.2.2-98-g25eac1d
- **Arguments:** /mnt/linux/AI/Stability Matrix/Packages/ComfyUI/main.py --preview-method auto --disable-xformers
- **OS:** posix
- **Python Version:** 3.10.11 (main, May  7 2023, 19:26:31) [Clang 16.0.3 ]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+rocm6.1
## Devices

- **Name:** cuda:0 AMD Radeon RX 7900 XTX : native
  - **Type:** cuda
  - **VRAM Total:** 25753026560
  - **VRAM Free:** 23880475648
  - **Torch VRAM Total:** 1734344704
  - **Torch VRAM Free:** 84091904

## Logs
```
2024-10-10 11:55:19,995 - root - INFO - Total VRAM 24560 MB, total RAM 63942 MB
2024-10-10 11:55:19,995 - root - INFO - pytorch version: 2.4.1+rocm6.1
2024-10-10 11:55:19,995 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-10 11:55:19,995 - root - INFO - Device: cuda:0 AMD Radeon RX 7900 XTX : native
2024-10-10 11:55:20,338 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-10-10 11:55:20,697 - root - INFO - [Prompt Server] web root: /mnt/linux/AI/Stability Matrix/Packages/ComfyUI/web
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path checkpoints /mnt/linux/AI/Stability Matrix/Models/StableDiffusion
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path vae /mnt/linux/AI/Stability Matrix/Models/VAE
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path loras /mnt/linux/AI/Stability Matrix/Models/Lora
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path loras /mnt/linux/AI/Stability Matrix/Models/LyCORIS
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path upscale_models /mnt/linux/AI/Stability Matrix/Models/ESRGAN
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path upscale_models /mnt/linux/AI/Stability Matrix/Models/RealESRGAN
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path upscale_models /mnt/linux/AI/Stability Matrix/Models/SwinIR
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path embeddings /mnt/linux/AI/Stability Matrix/Models/TextualInversion
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path hypernetworks /mnt/linux/AI/Stability Matrix/Models/Hypernetwork
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path controlnet /mnt/linux/AI/Stability Matrix/Models/ControlNet
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path controlnet /mnt/linux/AI/Stability Matrix/Models/T2IAdapter
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path clip /mnt/linux/AI/Stability Matrix/Models/CLIP
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path clip_vision /mnt/linux/AI/Stability Matrix/Models/InvokeClipVision
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path diffusers /mnt/linux/AI/Stability Matrix/Models/Diffusers
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path gligen /mnt/linux/AI/Stability Matrix/Models/GLIGEN
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path vae_approx /mnt/linux/AI/Stability Matrix/Models/ApproxVAE
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path ipadapter /mnt/linux/AI/Stability Matrix/Models/IpAdapter
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path ipadapter /mnt/linux/AI/Stability Matrix/Models/InvokeIpAdapters15
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path ipadapter /mnt/linux/AI/Stability Matrix/Models/InvokeIpAdaptersXl
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path prompt_expansion /mnt/linux/AI/Stability Matrix/Models/PromptExpansion
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path ultralytics /mnt/linux/AI/Stability Matrix/Models/Ultralytics
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path ultralytics_bbox /mnt/linux/AI/Stability Matrix/Models/Ultralytics/bbox
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path ultralytics_segm /mnt/linux/AI/Stability Matrix/Models/Ultralytics/segm
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path sams /mnt/linux/AI/Stability Matrix/Models/Sams
2024-10-10 11:55:20,699 - root - INFO - Adding extra search path diffusion_models /mnt/linux/AI/Stability Matrix/Models/unet
2024-10-10 11:55:20,869 - root - INFO - 
Import times for custom nodes:
2024-10-10 11:55:20,869 - root - INFO -    0.0 seconds: /mnt/linux/AI/Stability Matrix/Packages/ComfyUI/custom_nodes/websocket_image_save.py
2024-10-10 11:55:20,869 - root - INFO - 
2024-10-10 11:55:20,872 - root - INFO - Starting server

2024-10-10 11:55:20,872 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-10 11:55:36,785 - root - INFO - got prompt
2024-10-10 11:55:36,876 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-10 11:55:36,876 - root - INFO - model_type EPS
2024-10-10 11:55:37,262 - root - INFO - Using split attention in VAE
2024-10-10 11:55:37,263 - root - INFO - Using split attention in VAE
2024-10-10 11:55:37,626 - root - INFO - Requested to load SDXLClipModel
2024-10-10 11:55:37,626 - root - INFO - Loading 1 new model
2024-10-10 11:55:37,893 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-10 11:55:37,897 - root - ERROR - !!! Exception during processing !!! HIP error: no kernel image is available for execution on the device
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

2024-10-10 11:55:37,898 - root - ERROR - Traceback (most recent call last):
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/nodes.py", line 65, in encode
    output = clip.encode_from_tokens(tokens, return_pooled=True, return_dict=True)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd.py", line 125, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sdxl_clip.py", line 60, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd1_clip.py", line 41, in encode_token_weights
    o = self.encode(to_encode)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd1_clip.py", line 229, in encode
    return self(tokens)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/sd1_clip.py", line 201, in forward
    outputs = self.transformer(tokens, attention_mask_model, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/clip_model.py", line 136, in forward
    x = self.text_model(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/clip_model.py", line 100, in forward
    x = self.embeddings(input_tokens, dtype=dtype)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/clip_model.py", line 81, in forward
    return self.token_embedding(input_tokens, out_dtype=dtype) + comfy.ops.cast_to(self.position_embedding.weight, dtype=dtype, device=input_tokens.device)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/ops.py", line 211, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/comfy/ops.py", line 207, in forward_comfy_cast_weights
    return torch.nn.functional.embedding(input, weight, self.padding_idx, self.max_norm, self.norm_type, self.scale_grad_by_freq, self.sparse).to(dtype=output_dtype)
  File "/mnt/linux/AI/Stability Matrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: HIP error: no kernel image is available for execution on the device
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.


2024-10-10 11:55:37,898 - root - INFO - Prompt executed in 1.11 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":9,"last_link_id":9,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":{"0":413,"1":389},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":6,"type":"CLIPTextEncode","pos":{"0":415,"1":186},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":5,"type":"EmptyLatentImage","pos":{"0":473,"1":609},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":3,"type":"KSampler","pos":{"0":863,"1":186},"size":{"0":315,"1":262},"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[749813392907085,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":{"0":1209,"1":188},"size":{"0":210,"1":46},"flags":{},"order":5,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":{"0":1451,"1":189},"size":{"0":210,"1":58},"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":26,"1":474},"size":{"0":315,"1":98},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["NUKEPonyPixarStyle_v2S.safetensors"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[492,2]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Version

v2.12.1

### What Operating System are you using?

Linux

**Comment by Freakyfox20** [comment]
I fixed it. Problem was that it wasn't in portable mode. Putting it in portable allowed me generate.
