### ISSUE TITLE
ModuleNotFoundError: No module named 'torch': 'vite' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by gerroon** [LykosAI/StabilityMatrix#949]
### Package

SDFX

### When did the issue occur?

Installing the Package

### What GPU / hardware type are you using?

NVIDIA RTX  2070

### What happened?

I tried to install SDFX first time, and this is the error I am getting in the console

### Console output

```
Loading...
███████╗██████╗ ███████╗██╗  ██╗
██╔════╝██╔══██╗██╔════╝╚██╗██╔╝
███████╗██║  ██║█████╗   ╚███╔╝ 
╚════██║██║  ██║██╔══╝   ██╔██╗ 
███████║██████╔╝██║     ██╔╝ ██╗
╚══════╝╚═════╝ ╚═╝     ╚═╝  ╚═╝
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies. (GitPython)

> sdfx@0.8.8 start
> npm run dev:app


> sdfx@0.8.8 dev:app
> vite --config ./vite.config.app.ts --host


'vite' is not recognized as an internal or external command,
operable program or batch file.
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.9.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.9.0>
npm notice Run `npm install -g npm@10.9.0` to update!
npm notice 
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-12 13:50:19.470925
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\StabilityMatrix-win-x64\Data\Packages\SDFX\venv\Scripts\python.exe
** ComfyUI Path: C:\StabilityMatrix-win-x64\Data\Packages\SDFX\ComfyUI
** Log path: C:\StabilityMatrix-win-x64\Data\Packages\SDFX\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\StabilityMatrix-win-x64\Data\Packages\SDFX\ComfyUI\custom_nodes\SDFXBridgeForComfyUI
 707.0 seconds: C:\StabilityMatrix-win-x64\Data\Packages\SDFX\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\StabilityMatrix-win-x64\Data\Packages\SDFX\ComfyUI\main.py", line 88, in <module>
    import comfy.utils
  File "C:\StabilityMatrix-win-x64\Data\Packages\SDFX\ComfyUI\comfy\utils.py", line 20, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

```

### Version

2.12.2

### What Operating System are you using?

Windows

**Comment by gerroon** [comment]
> This issue was closed because it has been stale for 5 days with no activity.

fuck you
