### ISSUE TITLE
It seems the Python installed by StabilityMatrix is an incomplete installation, and it lacks distutils

### ISSUE THREAD

**Issue by shivdbz2010** [LykosAI/StabilityMatrix#954]
### Package

Python

### When did the issue occur?

Installing the Package

### What GPU / hardware type are you using?

4090

### What happened?

https://github.com/woct0rdho/triton-windows/issues/1
It seems the Python installed by StabilityMatrix is an incomplete installation, and it lacks distutils. Please ask the authors of StabilityMatrix to fix that.

### Console output

est fails in my case (Python 3.10 in venv, didn't add "include_libs")

Traceback (most recent call last):
  File "d:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\test.py", line 2, in <module>
    import triton
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\__init__.py", line 44, in _discover_backends
    driver = _load_module(name, os.path.join(root, name, 'driver.py'))
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\amd\driver.py", line 7, in <module>
    from triton.runtime.build import _build
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\build.py", line 8, in <module>
    import setuptools
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\setuptools\__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\Scripts\python310.zip\distutils\core.py

### Version

latest i guess

### What Operating System are you using?

Windows

**Comment by shivshankar11** [comment]
feature request- force stablixtymatrix to use existing venv,  why it must replace venv. very annoying. i want to use complete python 3.11/3.12. not incomplete python environments.

**Comment by kimnzl** [comment]
If you set the environment variable SETUPTOOLS_USE_DISTUTILS=stdlib you should be past that distutil error.

I used:
```
Install requirements VS and CUDA
C&P Python 3.10 include and libs folders into one of the paths listed in the error - in the venv for me. I have attached them in a zip.
I c&p include and libs folders into:
Data\Packages\ComfyUI\venv and Data\Packages\ComfyUI\venv\Scripts


run cmd.exe
set SETUPTOOLS_USE_DISTUTILS=stdlib
cd /d <StabilityMatrixFolder>\Data\Packages\ComfyUI

:: Pick one of the following
:: VS2022 build tools
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"
:: VS2022 Community
call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

call venv\Scripts\activate.bat

pip install --upgrade setuptools

pip install <path to where downloaded>\triton-3.1.0-cp310-cp310-win_amd64.whl
```
[Python310_includes_libs.zip](https://github.com/user-attachments/files/17428520/Python310_includes_libs.zip)

**Comment by scruffynerf** [comment]
```
source venv/bin/activate
export SETUPTOOLS_USE_DISTUTILS=stdlib
StabilityMatrix/Data/Packages/ComfyUI/venv/bin/python3 StabilityMatrix/Data/Packages/ComfyUI/main.py (args as needed)
```

With this, you can remotely restart ComfyUI, when it's crashed, and only way to reset it is via SM (which isn't accessibly remotely)

**Comment by thiagojramos** [comment]
> feature request- force stablixtymatrix to use existing venv, why it must replace venv. very annoying. i want to use complete python 3.11/3.12. not incomplete python environments.

I've tried several times to request features like this to use newer versions of python, and I've even seen several requests around here, but the devs ignore them and the posts end up being closed due to inactivity for so many days... 🤷🏼‍♂️

**Comment by extra2AB** [comment]
if you are here after trying to install sageattention 2.0.1 and it still fails after doing the above steps.

do

set SETUPTOOLS_USE_DISTUTILS=setuptools

in the above steps

**Comment by Profileiche** [comment]
Yes... I tried to install insightface over the python packeages option and it stalled on lackign Include. Is there are reason why SM runs it on Python 3.10?

**Comment by shivshankar11** [comment]
Because stabilitymatrix’s devloper dont allow to uses another python version? I don’t know why they hate other python versions or why they force embedded python version?  Why can’t we use env created with standard python? Windows version of Triton never work with ComfyUI because of this. It will be not fixed because SM creator simiply doesn’t care. Its opensource afterall you can fix it.

**Comment by mohnjiles** [comment]
> Yes... I tried to install insightface over the python packeages option and it stalled on lackign Include. Is there are reason why SM runs it on Python 3.10?

It was what was most compatible when we initially built the project. We do have a fix in the works for this specific issue (distutils stuff). On Windows we're currently using the embedded Python which lacks certain things from the main Python install, switching to the "regular" python is on the to-do list, along with letting people select their own versions.

 



> Because stabilitymatrix’s devloper dont allow to uses another python version? I don’t know why they hate other python versions or why they force embedded python version? Why can’t we use env created with standard python? Windows version of Triton never work with ComfyUI because of this. It will be not fixed because SM creator simiply doesn’t care. Its opensource afterall you can fix it.

Every time someone complains about it we delay it two weeks. The current ETA is October 22, 2038.
