### ISSUE TITLE
Crash while managing checkpoints

### ISSUE THREAD

**Issue by halr9000** [LykosAI/StabilityMatrix#982]
### What happened?

Crash seems to happen while in Checkpoint Manager view, but I am unable to provide a good repro. I suspect it is related to the presence of SD3.5 models in my lora folder, but that could be unrelated. Perhaps related, when viewing this one folder, 3 of the model preview photos will show a different image for a moment, flicker and then change to what is seen in this screenshot. I sometimes see this behavior in other folders, but not to this extent.

![image](https://github.com/user-attachments/assets/6bd5145c-f23a-4d2a-8560-9b038a84a7ee)

Crash has happened 3x in 24 hours, so it's getting bad.

Following are contents of my lora folder. Can provide more info if requested.

```

    Directory: D:\hal\stable-diffusion\Models\Lora

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           11/1/2024  6:58 AM                flux
d----          10/14/2024 10:57 PM                SD15
d----          10/23/2024 10:54 PM                SD3
d----          10/14/2024 10:59 PM                SDXL
d----           11/1/2024  7:00 AM                util
-a---          10/29/2024  1:44 PM            952 cgµªéσ┐╡ΘúÄ_sd35_lora=.cm-info.json
-a---          10/29/2024  1:44 PM          51739 cgµªéσ┐╡ΘúÄ_sd35_lora=.preview.jpeg
-a---          10/29/2024  1:44 PM      146762485 cgµªéσ┐╡ΘúÄ_sd35_lora=.safetensors
-a---          10/14/2024 10:43 PM           1597 Hyper-SD15-8steps-CFG-lora.cm-info.json
-a---          10/14/2024 10:43 PM          51845 Hyper-SD15-8steps-CFG-lora.preview.jpeg
-a---           9/22/2024  3:23 PM      269127064 Hyper-SD15-8steps-CFG-lora.safetensors
-a---            4/7/2024  1:27 PM            904 ip-adapter-faceid_sd15_lora.civitai.info
-a---            4/7/2024  1:27 PM            283 ip-adapter-faceid_sd15_lora.json
-a---            4/6/2024 11:32 PM       51059544 ip-adapter-faceid_sd15_lora.safetensors
-a---            4/7/2024  1:27 PM            905 ip-adapter-faceid_sdxl_lora.civitai.info
-a---            4/7/2024  1:27 PM            283 ip-adapter-faceid_sdxl_lora.json
-a---            4/6/2024 11:33 PM      371842896 ip-adapter-faceid_sdxl_lora.safetensors
-a---           5/13/2024 11:09 AM           3402 ip-adapter-faceid-plusv2_sd15_lora.civitai.info
-a---          10/14/2024 10:43 PM           1133 ip-adapter-faceid-plusv2_sd15_lora.cm-info.json
-a---            4/6/2024  8:06 PM            455 ip-adapter-faceid-plusv2_sd15_lora.json
-a---          10/14/2024 10:43 PM          55039 ip-adapter-faceid-plusv2_sd15_lora.preview.jpeg
-a---            4/6/2024  8:22 PM        4706220 ip-adapter-faceid-plusv2_sd15_lora.preview.png
-a---           3/18/2024  8:02 AM       51059544 ip-adapter-faceid-plusv2_sd15_lora.safetensors
-a---           5/13/2024 11:09 AM           3405 ip-adapter-faceid-plusv2_sdxl_lora.civitai.info
-a---          10/14/2024 10:43 PM           1134 ip-adapter-faceid-plusv2_sdxl_lora.cm-info.json
-a---            4/6/2024  8:06 PM            456 ip-adapter-faceid-plusv2_sdxl_lora.json
-a---          10/14/2024 10:43 PM          55039 ip-adapter-faceid-plusv2_sdxl_lora.preview.jpeg
-a---            4/6/2024  8:22 PM        4706220 ip-adapter-faceid-plusv2_sdxl_lora.preview.png
-a---           3/18/2024  8:03 AM      371842896 ip-adapter-faceid-plusv2_sdxl_lora.safetensors
-a---           5/13/2024 11:09 AM           5960 lcm-lora-sdv1-5.civitai.info
-a---          10/14/2024 10:43 PM           3283 lcm-lora-sdv1-5.cm-info.json
-a---            4/6/2024  8:06 PM           1536 lcm-lora-sdv1-5.json
-a---          10/14/2024 10:43 PM          37772 lcm-lora-sdv1-5.preview.jpeg
-a---            4/6/2024  8:06 PM        1495577 lcm-lora-sdv1-5.preview.png
-a---           3/18/2024  8:02 AM      134621556 lcm-lora-sdv1-5.safetensors
-a---           5/13/2024 11:09 AM          16543 lcm-lora-sdxl.civitai.info
-a---          10/14/2024 10:43 PM           2845 lcm-lora-sdxl.cm-info.json
-a---            4/6/2024  8:06 PM           1131 lcm-lora-sdxl.json
-a---          10/14/2024 10:43 PM          72911 lcm-lora-sdxl.preview.jpeg
-a---            4/6/2024  8:06 PM        1496132 lcm-lora-sdxl.preview.png
-a---           3/18/2024  8:02 AM      393855224 lcm-lora-sdxl.safetensors
-a---           9/30/2024 10:08 PM         679936 model_metadata-log.ldb
-a---            3/9/2024  2:17 PM           8192 model_metadata.ldb
-a---           5/13/2024 11:09 AM           6433 sd_v15_dpo_lora_v1.civitai.info
-a---          10/14/2024 10:43 PM           4556 sd_v15_dpo_lora_v1.cm-info.json
-a---            4/6/2024  8:06 PM           1905 sd_v15_dpo_lora_v1.json
-a---          10/14/2024 10:43 PM          29883 sd_v15_dpo_lora_v1.preview.jpeg
-a---            1/7/2024  9:27 PM      269127676 sd_v15_dpo_lora_v1.safetensors
-a---           5/13/2024 11:09 AM           3895 sd_xl_offset_example-lora_1.0.civitai.info
-a---          10/14/2024 10:43 PM           1057 sd_xl_offset_example-lora_1.0.cm-info.json
-a---            4/6/2024  8:06 PM            444 sd_xl_offset_example-lora_1.0.json
-a---          10/14/2024 10:43 PM          26369 sd_xl_offset_example-lora_1.0.preview.jpeg
-a---            4/6/2024  8:06 PM         101818 sd_xl_offset_example-lora_1.0.preview.png
-a---           2/25/2024 11:00 PM       49553604 sd_xl_offset_example-lora_1.0.safetensors
-a---          10/29/2024  1:43 PM           2491 sd35_blowjob_lora_v1.cm-info.json
-a---          10/29/2024  1:43 PM          36685 sd35_blowjob_lora_v1.preview.jpeg
-a---          10/29/2024  1:43 PM      146762497 sd35_blowjob_lora_v1.safetensors
-a---          10/29/2024  1:43 PM           2621 sd35-ancient_style_v1.cm-info.json
-a---          10/29/2024  1:43 PM          45974 sd35-ancient_style_v1.preview.jpeg
-a---          10/29/2024  1:43 PM      146762568 sd35-ancient_style_v1.safetensors
-a---           5/13/2024 11:09 AM          17443 sdxl_lcm_lora.civitai.info
-a---            4/6/2024  8:06 PM           1037 sdxl_lcm_lora.json
-a---          10/29/2024  1:44 PM           1075 µ£║µó░µÿåΦÖ½_sd35_lora.cm-info.json
-a---          10/29/2024  1:44 PM          64257 µ£║µó░µÿåΦÖ½_sd35_lora.preview.jpeg
-a---          10/29/2024  1:44 PM      146762490 µ£║µó░µÿåΦÖ½_sd35_lora.safetensors
```

## Exception
```ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')```
### Sentry ID
[`68731459`](https://stability-matrix.sentry.io/issues/?query=id%3A6873145999054a878afcc79d774c62b7&referrer=sm-app-ex&statsPeriod=90d)
### Stack Trace
```   at Avalonia.Layout.FlowLayoutAlgorithm.RaiseLineArranged()
   at Avalonia.Layout.FlowLayoutAlgorithm.Measure(Size availableSize, VirtualizingLayoutContext context, Boolean isWrapping, Double minItemSpacing, Double lineSpacing, Int32 maxItemsPerLine, ScrollOrientation orientation, Boolean disableVirtualization, String layoutId)
   at Avalonia.Layout.UniformGridLayout.MeasureOverride(VirtualizingLayoutContext context, Size availableSize)
   at Avalonia.Controls.ItemsRepeater.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at Avalonia.Media.MediaContext.RenderCore()
   at Avalonia.Media.MediaContext.Render()
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at StabilityMatrix.Avalonia.Program.Main(String[] args)```


### Version

2.12.2

### What Operating System are you using?

Windows

**Comment by halr9000** [comment]
Here's an archive of all the metadata and preview image files in that folder. Everything but the models themselves.
[lora_metadata.zip](https://github.com/user-attachments/files/17599150/lora_metadata.zip)
