### ISSUE TITLE
Invoke fails after Update

### ISSUE THREAD

**Issue by drdancm** [LykosAI/StabilityMatrix#99]
I'm afraid I don't know much programming so I need help to see how to solve this.
It was working fine prior to the update.

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\app\api_app.py", line 22, in <module>
    from ..backend.util.logging import InvokeAILogger
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\__init__.py", line 5, in <module>
    from .model_management import ModelManager, ModelCache, BaseModelType, ModelType, SubModelType, ModelInfo
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\model_management\__init__.py", line 4, in <module>
    from .model_manager import ModelManager, ModelInfo, AddModelResult, SchedulerPredictionType
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\model_management\model_manager.py", line 249, in <module>
    from .model_cache import ModelCache, ModelLocker
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\model_management\model_cache.py", line 31, in <module>
    from .models import BaseModelType, ModelType, SubModelType, ModelBase
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\model_management\models\__init__.py", line 21, in <module>
    from .vae import VaeModel
  File "D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\invokeai\backend\model_management\models\vae.py", line 8, in <module>
    from diffusers.utils import is_safetensors_available
ImportError: cannot import name 'is_safetensors_available' from 'diffusers.utils' (D:\STABLEDIFF\Data\Packages\InvokeAI\venv\lib\site-packages\diffusers\utils\__init__.py)

Process finished with exit code 1

**Comment by drdancm** [comment]
This is no longer a problem because an newer update from Invoke fixed the issue.

**Comment by drdancm** [comment]
This is no longer a problem because an newer update from Invoke fixed the issue.
