### ISSUE TITLE
The latest version of Webui reForge crashes upon startup

### ISSUE THREAD

**Issue by antrobot1234** [LykosAI/StabilityMatrix#992]
### Package

WebUI reForge

### When did the issue occur?

Running the Package

### What GPU / hardware type are you using?

Nvidia 3060TI

### What happened?

After updating webUI reForge to the latest stable branch, it crashes on startup.

### Console output

``` Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.0.5-v1.10.1RC-latest-729-g818effd9
Commit hash: 818effd96e5abbd248901f1fd1cabf6c6fd3cdaf
Installing requirements
C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_legacy_preprocessors\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\extensions-builtin\sd_forge_controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --gradio-allowed-path 'C:\Users\antro\Documents\Matrix\Images'
Total VRAM 8192 MB, total RAM 65462 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention
*** Error loading script: SC_pipeline.py
    Traceback (most recent call last):
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\extensions-builtin\StableCascade-for-webUI-main\scripts\SC_pipeline.py", line 27, in <module>
        from diffusers.models import StableCascadeUNet
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\huggingface_hub\__init__.py)

---
*** Error loading script: stablecascade_diffusers.py
    Traceback (most recent call last):
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\extensions-builtin\StableCascade-for-webUI-main\scripts\stablecascade_diffusers.py", line 1, in <module>
        from diffusers.utils import check_min_version
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\huggingface_hub\__init__.py)

---
ControlNet preprocessor location: C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\models\ControlNetPreprocessor
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\huggingface_hub\__init__.py)

---
Traceback (most recent call last):
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\launch.py", line 51, in <module>
    main()
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\launch.py", line 47, in main
    start()
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\launch_utils.py", line 542, in start
    import webui
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\webui.py", line 23, in <module>
    initialize.initialize()
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\initialize.py", line 89, in initialize
    initialize_rest(reload_script_modules=False)
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\initialize.py", line 133, in initialize_rest
    modelloader.load_upscalers()
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\modelloader.py", line 108, in load_upscalers
    scaler = cls(commandline_model_path)
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\dat_model.py", line 22, in __init__
    if model.name in opts.dat_enabled_models:
  File "C:\Users\antro\Documents\Matrix\Packages\Stable Diffusion WebUI reForge\modules\options.py", line 142, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'dat_enabled_models'
```

### Version

v2.12.3

### What Operating System are you using?

Windows

**Comment by mohnjiles** [comment]
Please update reForge again, this was fixed as part of https://github.com/Panchovix/stable-diffusion-webui-reForge/issues/168
